"""
Specialized Track Specifications for SkillTwin.
Contains comprehensive 18-node curricula for:
- blockchain (18 nodes)
- game-developer (18 nodes)
- server-side-game-developer (18 nodes)
- dsa_problem_solving (18 nodes)
"""

from typing import Dict, Any, List


def make_node(slug: str, key: str, title: str, subtitle: str, phase: str, tier: str, imp: str, diff: str, order: int, mins: int, prereqs: List[str], obj: List[str], feyn: List[str], misc: List[str]) -> Dict[str, Any]:
    return {
        "id": f"cnode_{slug}_{key}",
        "concept_id": f"concept_{slug}_{key}",
        "title": title,
        "subtitle": subtitle,
        "phase": phase,
        "tier": tier,
        "importance": imp,
        "difficulty": diff,
        "order": order,
        "estimated_minutes": mins,
        "prerequisites": [f"concept_{slug}_{p}" for p in prereqs],
        "learning_objectives": obj,
        "feynman_prompts": feyn,
        "key_misconceptions": misc,
        "recommended_resources": [],
    }


def get_specialized_specs() -> List[Dict[str, Any]]:
    # 1. BLOCKCHAIN (18 nodes)
    bc = [
        ("cryptography_foundations", "Cryptographic Foundations of Blockchains", "Cryptographic hashes (SHA-256, Keccak-256), public-key cryptography (secp256k1), digital signatures", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Explain how asymmetric key pairs (private/public key) enable trustless digital signatures", "Analyze cryptographic collision resistance and one-way hash properties"],
         ["Explain how digital signatures verify the sender without revealing the private key."],
         ["Assuming blockchain encryption hides transaction amounts by default (public blockchains are transparent)"]),
        ("distributed_ledger_merkle", "Distributed Ledgers & Merkle Trees", "Blocks, headers, Merkle roots, SPV proofs, transaction immutability, peer-to-peer gossip", "Foundations", "foundation", "essential", "beginner", 25, ["cryptography_foundations"],
         ["Construct a Merkle tree and generate lightweight cryptographic proofs of inclusion", "Explain how peer-to-peer gossip networks propagate transactions without a central coordinator"],
         ["Why does tampering with a transaction in an early block invalidate all subsequent block hashes?"],
         ["Believing a Merkle tree stores the entire database rather than cryptographic verification fingerprints"]),
        ("consensus_mechanisms", "Consensus Mechanisms (PoW, PoS & BFT)", "Proof of Work (difficulty adjustment, 51% attack), Proof of Stake (slashing, validators, finality), BFT", "Foundations", "foundation", "essential", "intermediate", 30, ["distributed_ledger_merkle"],
         ["Contrast the resource incentives of Proof of Work with Proof of Stake slashing conditions", "Explain Byzantine Fault Tolerance (BFT) and the 2/3 validator consensus requirement"],
         ["What prevents a rich validator from reversing transactions in Proof of Stake?"],
         ["Assuming Proof of Stake has zero environmental or financial security cost"]),
        ("ethereum_evm_architecture", "Ethereum & EVM Architecture", "EVM state machine, gas mechanics, opcodes, memory vs storage vs calldata, account model vs UTXO", "Foundations", "foundation", "essential", "intermediate", 30, ["consensus_mechanisms"],
         ["Model Ethereum state transitions, account nonce management, and gas calculation", "Distinguish EVM memory (ephemeral) from storage (persistent, expensive) and calldata (read-only)"],
         ["Why is writing to EVM storage significantly more expensive in gas than reading from memory?"],
         ["Confusing Bitcoin's UTXO model with Ethereum's account-based state model"]),
        ("solidity_fundamentals", "Solidity Smart Contract Fundamentals", "Data types, mappings, structs, modifiers, visibility (public, external, internal, private), constructors", "Core", "core", "essential", "intermediate", 35, ["ethereum_evm_architecture"],
         ["Write clean Solidity smart contracts with proper visibility modifiers and custom error types", "Manage contract state variables and enforce access control with custom modifiers"],
         ["Explain why custom errors (`error Unauthorized()`) save gas compared to `require(..., 'string')`."],
         ["Assuming `private` variables in Solidity cannot be read by anyone (all blockchain data is public)"]),
        ("token_standards_erc", "ERC Token Standards (ERC-20, ERC-721, ERC-1155)", "ERC-20 fungible tokens, ERC-721 non-fungible tokens, ERC-1155 multi-tokens, safeTransferFrom, approvals", "Core", "core", "essential", "intermediate", 30, ["solidity_fundamentals"],
         ["Implement secure ERC-20 and ERC-721 tokens utilizing OpenZeppelin contracts", "Safely handle token approval mechanics and prevent allowance race conditions"],
         ["Why is the standard `approve` and `transferFrom` two-step pattern required for smart contract interaction?"],
         ["Assuming transferring NFTs is fundamentally different from updating a mapping index"]),
        ("hardhat_foundry_toolchain", "Development Toolchains: Foundry & Hardhat", "Forge, Anvil, Cast, Solidity-based testing, fuzz testing, deployment scripts, gas profiling", "Core", "core", "essential", "intermediate", 35, ["solidity_fundamentals"],
         ["Write fast unit and fuzz tests in Foundry using native Solidity", "Profile contract gas consumption and simulate deployments against local Anvil forks"],
         ["Why is fuzz testing in Foundry superior to hardcoded unit test assertions for math edge cases?"],
         ["Deploying smart contracts to mainnet without extensive local test suite simulation"]),
        ("web3_frontend_integration", "Web3 Frontend Integration (viem, wagmi, ethers)", "Wallet connection (MetaMask, WalletConnect), provider vs signer, ABI encoding, transaction receipts", "Core", "core", "essential", "intermediate", 30, ["token_standards_erc"],
         ["Connect modern frontend apps to Ethereum nodes using viem and wagmi React hooks", "Handle pending transaction states, gas estimations, and user signature rejections gracefully"],
         ["Explain the difference between a read-only node call (`eth_call`) and a state-modifying transaction (`eth_sendRawTransaction`)."],
         ["Assuming transaction submission guarantees immediate state confirmation without waiting for block receipts"]),
        ("smart_contract_security", "Smart Contract Security & Attack Vectors", "Reentrancy attacks, integer overflow, flash loan exploits, frontrunning/MEV, access control flaws", "Core", "core", "essential", "advanced", 35, ["solidity_fundamentals", "hardhat_foundry_toolchain"],
         ["Identify and remediate reentrancy vulnerabilities using Checks-Effects-Interactions and ReentrancyGuard", "Protect contracts against sandwich attacks and frontrunning price manipulations"],
         ["Walk through how the classic DAO reentrancy exploit worked line by line."],
         ["Believing that using modern Solidity >=0.8 automatic overflow checks solves all security vulnerabilities"]),
        ("defi_primitives_amms", "DeFi Primitives: AMMs & Lending Protocols", "Automated Market Makers (x*y=k), liquidity pools, impermanent loss, collateralized lending, liquidations", "Core", "core", "essential", "advanced", 35, ["token_standards_erc", "smart_contract_security"],
         ["Deconstruct the constant product formula (x * y = k) used by Uniswap v2", "Calculate impermanent loss and model collateralization ratios for decentralized lending"],
         ["Explain why impermanent loss occurs for liquidity providers when prices diverge."],
         ["Assuming automated market makers have zero slippage for large orders"]),
        ("oracles_chainlink", "Decentralized Oracles & Chainlink", "The Oracle problem, Chainlink price feeds, VRF (verifiable random function), CCIP, staleness checks", "Advanced", "advanced", "essential", "intermediate", 30, ["defi_primitives_amms"],
         ["Integrate Chainlink price feeds with heartbeat and round staleness validation checks", "Generate provably fair random numbers in smart contracts using Chainlink VRF v2"],
         ["Why cannot a smart contract make a direct HTTP request to fetch an off-chain stock price?"],
         ["Failing to validate price feed round timestamp, leading to stale pricing exploits"]),
        ("layer2_rollups_scaling", "Layer 2 Scaling: Optimistic & ZK Rollups", "State bloat, Optimistic Rollups (Arbitrum, Optimism, fraud proofs), ZK-Rollups (Starknet, zkSync, validity proofs)", "Advanced", "advanced", "essential", "intermediate", 30, ["ethereum_evm_architecture"],
         ["Explain the architectural difference between fraud proofs (optimistic) and validity proofs (zero-knowledge)", "Bridge assets and interact with smart contracts on Layer 2 networks"],
         ["Why do Optimistic Rollups have a 7-day challenge window for mainnet withdrawals while ZK-Rollups do not?"],
         ["Assuming Layer 2 networks operate as completely separate independent blockchains without L1 security"]),
        ("zero_knowledge_proofs", "Zero-Knowledge Proofs (ZKP) Fundamentals", "zk-SNARKs, zk-STARKs, arithmetic circuits, Circom, non-interactive proofs, privacy & verification", "Advanced", "advanced", "recommended", "advanced", 35, ["layer2_rollups_scaling"],
         ["Author basic arithmetic circuits in Circom to generate verifiable proofs of knowledge", "Verify zero-knowledge proofs on-chain inside a Solidity smart contract"],
         ["Explain how a zero-knowledge proof proves knowledge of a secret without revealing the secret."],
         ["Confusing zero-knowledge data privacy with data encryption"]),
        ("decentralized_storage_indexing", "Decentralized Storage & Indexing (IPFS, The Graph)", "IPFS content addressing (CIDs), Pinata/Filecoin, GraphQL subgraphs, indexing event logs", "Advanced", "advanced", "recommended", "intermediate", 30, ["web3_frontend_integration"],
         ["Deploy Subgraphs on The Graph protocol to index and query contract event logs via GraphQL", "Host metadata and immutable assets on IPFS using content identifiers (CIDs)"],
         ["Why is querying contract state via a Graph indexer thousands of times faster than direct RPC node calls?"],
         ["Storing large files or images directly on-chain inside EVM smart contract storage"]),
        ("smart_contract_auditing", "Smart Contract Auditing & Static Analysis", "Slither, Mythril, Certora formal verification, manual audit methodology, creating audit reports", "Advanced", "advanced", "recommended", "advanced", 35, ["smart_contract_security"],
         ["Run static analysis tools (Slither, Mythril) in CI to detect vulnerabilities pre-deployment", "Perform rigorous manual security code audits documenting vulnerability severity and remediation"],
         ["What types of logical flaws can human manual auditing catch that automated scanners miss?"],
         ["Assuming a 100% clean Slither static analysis run guarantees a contract is hack-proof"]),
        ("daos_governance_multisig", "DAOs, Governance & Multi-Sig Infrastructure", "Safe (Gnosis Safe), timelocks, Governor contracts, quorum, voting weight, proposal lifecycles", "Advanced", "advanced", "recommended", "advanced", 30, ["token_standards_erc"],
         ["Deploy multi-signature treasury vaults using Safe and establish secure sign-off thresholds", "Implement on-chain governance workflows with timelock delays to prevent flash loan hijacking"],
         ["Why must on-chain governance proposals enforce an immutable timelock delay before execution?"],
         ["Allowing immediate execution of governance proposals without timelock protection"]),
        ("mev_flashbots_architecture", "MEV (Maximal Extractable Value) & Flashbots", "Searchers, builders, proposers, sandwich attacks, private mempools, Flashbots Protect, MEV-Boost", "Mastery", "capstone", "recommended", "expert", 35, ["defi_primitives_amms", "smart_contract_security"],
         ["Explain the MEV supply chain from searchers identifying arbitrage to block builders and validators", "Protect user transactions from predatory frontrunning using private RPC endpoints and MEV-Boost"],
         ["How do searchers use private mempools to execute atomic risk-free DEX arbitrage?"],
         ["Assuming miners/validators only order transactions purely by gas fee timestamp"]),
        ("web3_dapp_capstone", "Full-Stack Web3 DApp Production Capstone", "End-to-end dApp: audited smart contracts, L2 deployment, subgraph indexing, wagmi UI, Safe treasury", "Mastery", "capstone", "essential", "expert", 40, ["web3_frontend_integration", "smart_contract_security", "decentralized_storage_indexing"],
         ["Architect and deploy an enterprise-grade decentralized protocol with multi-sig administration", "Integrate automated CI testing, gas profiling, subgraph indexing, and production Web3 UI"],
         ["What are the critical deployment checklist steps required before releasing contracts to Ethereum mainnet?"],
         ["Failing to renounce ownership or transfer admin keys to a multi-sig vault post-deployment"])
    ]

    # 2. GAME DEVELOPER (18 nodes)
    gd = [
        ("game_math_vectors", "Game Math & Physics Foundations", "2D/3D vectors, dot product, cross product, vector normalization, radians, coordinate spaces", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Calculate angles, directions, and distances between game objects using vector math", "Apply dot products to determine field-of-view visibility and directional facing"],
         ["Explain what the dot product of two normalized vectors reveals about their direction."],
         ["Mixing up local coordinate space with global world coordinate space"]),
        ("game_loop_architecture", "Game Loop Architecture & Delta Time", "FixedUpdate vs Update, variable vs fixed timestep, delta time, frame rate independence, vsync", "Foundations", "foundation", "essential", "beginner", 25, ["game_math_vectors"],
         ["Implement frame-rate-independent character movement using delta time", "Distinguish physics simulation ticks (fixed timestep) from visual rendering ticks"],
         ["Why does moving an object by speed without multiplying by delta time break at different FPS?"],
         ["Placing physics calculations inside the variable-rate render loop"]),
        ("collision_detection_2d", "Collision Detection & 2D Physics", "AABB (Axis-Aligned Bounding Box), Circle-Circle collision, SAT (Separating Axis Theorem), raycasting", "Foundations", "foundation", "essential", "beginner", 30, ["game_math_vectors"],
         ["Implement AABB and circle collision detection algorithms from scratch", "Perform raycasts to detect ground surfaces, obstacles, and line-of-sight in 2D/3D"],
         ["Explain how Separating Axis Theorem (SAT) detects collisions between rotated convex polygons."],
         ["Assuming bounding boxes must always be oriented along the screen axes (ignoring rotation)"]),
        ("engine_fundamentals_csharp", "Game Engine Fundamentals: Unity / Godot / Unreal", "Game objects, actors, components, transforms, prefabs/scenes, script lifecycles (Awake, Start, Update)", "Foundations", "foundation", "essential", "beginner", 30, ["game_loop_architecture"],
         ["Structure game entities using component composition over rigid object-oriented inheritance", "Instantiate and configure dynamic game object prefabs at runtime"],
         ["Why is composition (adding components) superior to deep class inheritance in game architecture?"],
         ["Creating monolithic God-classes that handle input, audio, rendering, and physics all in one script"]),
        ("input_handling_game_feel", "Input Systems & Player Controller 'Juice'", "New Input System, action maps, buffering, coyote time, jump apex gravity tuning, screenshake", "Core", "core", "essential", "intermediate", 30, ["engine_fundamentals_csharp"],
         ["Tune player controller physics with jump buffering, coyote time, and variable jump height", "Add 'game juice' (screen shake, hit-stop freeze frames, particle bursts) to heighten responsiveness"],
         ["What is coyote time and why does it make platformer jump controls feel fair to players?"],
         ["Relying strictly on realistic raw physics equations without tuning for game feel and responsiveness"]),
        ("state_machines_gameplay", "Game State Management & Finite State Machines (FSM)", "FSM architecture, character state machines (Idle, Run, Jump, Attack, Hurt), hierarchical state machines", "Core", "core", "essential", "intermediate", 30, ["engine_fundamentals_csharp"],
         ["Build clean finite state machines for complex player character and enemy state management", "Prevent illegal animation and logic transitions (e.g. attacking while dodging) using explicit FSM states"],
         ["Why does using boolean flags (`isJumping`, `isAttacking`, `isDead`) quickly lead to spaghetti code?"],
         ["Allowing multiple conflicting character states to be active simultaneously"]),
        ("animation_systems_blending", "Animation Systems & Blend Trees", "Skeletal animation, state machine transitions, blend trees, inverse kinematics (IK), root motion", "Core", "core", "essential", "intermediate", 30, ["state_machines_gameplay"],
         ["Configure 1D and 2D animation blend trees for smooth locomotion transitions (walk to sprint)", "Apply two-bone Inverse Kinematics (IK) to anchor character feet to uneven ground geometry"],
         ["Explain how animation blend trees interpolate between multiple directional movement clips."],
         ["Hard-snapping between animations without transition cross-fading"]),
        ("game_audio_fmod_wwise", "Game Audio Architecture & Adaptive Sound", "Audio listeners, 3D spatial sound, audio mixers, ducking, adaptive music layering, sound cues", "Core", "core", "recommended", "intermediate", 25, ["engine_fundamentals_csharp"],
         ["Implement 3D spatial attenuation and sound occlusion based on room geometry", "Design dynamic music systems that transition stems based on combat intensity"],
         ["How does dynamic audio ducking prevent sound clipping during intense explosion sequences?"],
         ["Playing repetitive sound effects at constant volume and pitch without subtle random variations"]),
        ("pathfinding_ai_navigation", "Game AI & Pathfinding: A* and NavMesh", "A* algorithm, heuristic functions, navigation meshes (NavMesh), agent steering, avoidance", "Core", "core", "essential", "intermediate", 35, ["game_math_vectors", "engine_fundamentals_csharp"],
         ["Implement the A* pathfinding algorithm on grid and node graph representations", "Bake dynamic NavMeshes and configure AI agent obstacle avoidance in 3D worlds"],
         ["Explain how the heuristic function in A* guides the search towards the target faster than Dijkstra."],
         ["Recalculating complete pathfinding routes every single frame for dozens of enemies"]),
        ("ai_behavior_trees", "Advanced AI: Behavior Trees & Utility AI", "Behavior trees (Sequencer, Selector, Decorators, Blackboard), utility AI, sensory perception", "Core", "core", "essential", "intermediate", 35, ["pathfinding_ai_navigation"],
         ["Design modular behavior trees with composite nodes and decorators for intelligent enemy AI", "Implement sensory perception systems (hearing footsteps, field-of-view cone detection)"],
         ["Why are behavior trees more scalable for complex game AI than massive finite state machines?"],
         ["Hardcoding AI logic directly into game update loops instead of blackboard data"]),
        ("shaders_graphics_pipeline", "Graphics Pipeline, Shaders & Materials", "Vertex & fragment shaders, HLSL/Shader Graph, PBR materials, normal maps, lighting models", "Advanced", "advanced", "essential", "intermediate", 35, ["game_math_vectors"],
         ["Write custom fragment shaders for rim lighting, dissolve effects, and water surfaces", "Configure Physically Based Rendering (PBR) materials with albedo, metallic, roughness, and normal maps"],
         ["Explain the difference in responsibility between vertex shaders and fragment/pixel shaders."],
         ["Executing expensive mathematical calculations in fragment shaders that could be computed once in vertex shaders"]),
        ("vfx_particle_systems", "VFX & Particle Systems (VFX Graph / Niagara)", "GPU particles, emitter modules, forces, turbulence, sprite sheets, particle collision", "Advanced", "advanced", "recommended", "intermediate", 25, ["shaders_graphics_pipeline"],
         ["Author high-performance GPU particle simulations for spells, fire, and weather effects", "Trigger context-aware impact particle effects matched to surface physical materials"],
         ["Why do GPU particle systems handle millions of particles while CPU systems choke on thousands?"],
         ["Spawning separate particle game objects dynamically instead of recycling via object pooling"]),
        ("level_design_spatial_flow", "Level Design, Whiteboxing & Environmental Storytelling", "Grayboxing/whiteboxing, sightlines, breadcrumbing, choke points, pacing, lighting cues", "Advanced", "advanced", "recommended", "intermediate", 30, ["engine_fundamentals_csharp"],
         ["Block out playable 3D levels using primitive geometry to test pacing and player metrics", "Guide player navigation naturally using architectural lighting, leading lines, and color contrast"],
         ["Why should gameplay levels be thoroughly playtested in graybox before any 3D art is created?"],
         ["Decorating an unplayable, confusing level with final high-poly art assets"]),
        ("save_systems_serialization", "Save Systems, Persistence & Serialization", "JSON/binary serialization, save versioning, encryption, cloud saves, state persistence", "Advanced", "advanced", "essential", "intermediate", 30, ["state_machines_gameplay"],
         ["Architect robust save/load systems capable of serializing dynamic world and inventory state", "Implement save file versioning and migration to prevent breaking user saves on game patches"],
         ["How do you prevent players from modifying local plaintext save files to cheat progression?"],
         ["Attempting to serialize raw game engine objects directly instead of clean data transfer DTOs"]),
        ("game_optimization_profiling", "Game Optimization, Profiling & Memory Management", "CPU/GPU profiler, draw calls, dynamic/static batching, LODs, occlusion culling, garbage collection", "Advanced", "advanced", "essential", "advanced", 35, ["shaders_graphics_pipeline"],
         ["Profile frame spikes, identify GC memory allocations, and eliminate runtime heap churn", "Reduce draw calls using GPU instancing, texture atlases, and occlusion culling"],
         ["Explain how garbage collection pauses cause noticeable micro-stutters during high-speed gameplay."],
         ["Instantiating and destroying hundreds of projectiles per minute instead of using an Object Pool"]),
        ("multiplayer_networking_client", "Multiplayer Fundamentals & Client-Side Prediction", "Client-server architecture, client-side prediction, server reconciliation, entity interpolation", "Advanced", "advanced", "recommended", "advanced", 35, ["game_loop_architecture"],
         ["Implement client-side movement prediction with server authoritative snapshot reconciliation", "Interpolate remote player positions smoothly across variable network latency"],
         ["Why must the server remain authoritative over player position and health in multiplayer games?"],
         ["Trusting the client to report when it takes damage or where it moves"]),
        ("game_ui_localization", "Game UI, Accessibility & Localization", "Canvas scalability, screen-safe areas, gamepad navigation, input glyph rebinding, localization tables", "Mastery", "capstone", "essential", "intermediate", 25, ["input_handling_game_feel"],
         ["Design responsive game HUDs and menus that scale across ultrawide and handheld resolutions", "Implement full gamepad navigation, UI audio feedback, and dynamic subtitle font scaling"],
         ["Why must UI layouts be designed with flexible text bounding boxes for international localization?"],
         ["Hardcoding string text directly inside UI scripts and buttons"]),
        ("full_game_release_capstone", "Full Game Polish & Release Capstone", "Vertical slice development, platform SDKs (Steamworks/Console), bug hunting, build pipelines", "Mastery", "capstone", "essential", "expert", 40, ["game_optimization_profiling", "save_systems_serialization"],
         ["Build, profile, and package a polished commercial vertical slice game demo", "Integrate platform SDKs (achievements, cloud saves, leaderboards) and automated build pipelines"],
         ["What differentiates a completed, polished game from an unfinished prototype?"],
         ["Spending years adding feature after feature to a game without ever locking scope and polishing"])
    ]

    # 3. SERVER-SIDE GAME DEVELOPER (18 nodes)
    ssgd = [
        ("game_server_foundations", "Server-Side Game Architecture Foundations", "Dedicated vs listen servers, authoritative vs peer-to-peer, tick rates, fixed timestep updates", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Contrast dedicated authoritative server topologies with peer-to-peer lockstep models", "Configure a deterministic server tick loop running at fixed simulation intervals (e.g. 64Hz)"],
         ["Why do competitive multiplayer games always rely on dedicated authoritative servers?"],
         ["Allowing game clients to execute authoritative game simulation logic"]),
        ("networking_udp_vs_tcp", "Low-Latency Game Networking (UDP, TCP & WebSockets)", "Transport protocols, UDP packet reliability layers, packet loss handling, header overhead, MTU", "Foundations", "foundation", "essential", "beginner", 30, ["game_server_foundations"],
         ["Build custom reliable-UDP sequencing and acknowledgment protocols over raw UDP sockets", "Explain why TCP head-of-line blocking makes standard TCP unsuitable for fast-action games"],
         ["What is Head-of-Line blocking in TCP and how does UDP avoid it?"],
         ["Using HTTP REST APIs for real-time multiplayer combat synchronization"]),
        ("binary_serialization_protocols", "Binary Serialization & Network Bandwidth Optimization", "Bit packing, delta compression, Protobuf, FlatBuffers, quantization, bandwidth budgeting", "Foundations", "foundation", "essential", "intermediate", 30, ["networking_udp_vs_tcp"],
         ["Quantize floating-point vector coordinates into compact integers to reduce packet payloads", "Implement delta compression transmitting only mutated entity components per tick"],
         ["Why is sending raw JSON over sockets unacceptable for high-frequency game server ticks?"],
         ["Sending full entity transforms every tick instead of compressed delta states"]),
        ("spatial_partitioning_grids", "Spatial Partitioning & Area of Interest (AoI)", "Grid hashing, quadtrees, octrees, area of interest management, entity filtering", "Foundations", "foundation", "essential", "intermediate", 35, ["binary_serialization_protocols"],
         ["Implement 2D grid hashing and quadtrees to broadcast updates only to relevant nearby players", "Filter out-of-vision server snapshots to reduce both server CPU and network egress"],
         ["Explain how spatial hashing prevents an O(N^2) entity broadcast explosion in dense game worlds."],
         ["Broadcasting every entity's position to every connected player across the entire map"]),
        ("authoritative_simulation_reconciliation", "Server Authoritative Physics & Reconciliation", "Simulating physics server-side, inputs queue, server tick snapshots, rollback reconciliation", "Core", "core", "essential", "intermediate", 35, ["spatial_partitioning_grids"],
         ["Execute deterministic gameplay physics on the server decoupled from graphical rendering", "Validate sequence numbers and generate authoritative state snapshots for client rollback"],
         ["How does server authority prevent speed hacks and position teleportation cheats?"],
         ["Simulating physics only on client machines and letting the server passively trust results"]),
        ("lag_compensation_rewind", "Lag Compensation & Server Time-Rewind", "Hit registration, server history buffer, rewinding player hitboxes, ping advantage mitigation", "Core", "core", "essential", "advanced", 35, ["authoritative_simulation_reconciliation"],
         ["Implement server-side lag compensation by rewinding target hitboxes to the client's fire timestamp", "Cap maximum rewind thresholds to prevent extreme 'getting shot around walls' experiences"],
         ["Explain step-by-step how an authoritative server validates a sniper hit from a 100ms ping player."],
         ["Rewinding server history indefinitely, which penalizes low-ping players"]),
        ("matchmaking_rating_systems", "Matchmaking Systems & Skill Rating Algorithms", "Elo, Glicko-2, TrueSkill, matchmaking queues, ticket expansion, ping vs skill balancing", "Core", "core", "essential", "intermediate", 30, ["game_server_foundations"],
         ["Implement rating update algorithms (Elo/Glicko) and queue expansion rules", "Balance queue wait times against latency and skill rating variance"],
         ["Why do matchmaking systems gradually widen MMR search radius over queue wait duration?"],
         ["Matching players strictly on level/playtime rather than latent skill rating"]),
        ("server_orchestration_agones", "Dedicated Game Server Orchestration (Agones & K8s)", "Agones on Kubernetes, fleet scaling, game server lifecycles (Allocated, Ready, Shutdown)", "Core", "core", "essential", "advanced", 35, ["game_server_foundations"],
         ["Deploy containerized game server binaries on Kubernetes using Google Agones", "Manage game server allocation requests from matchmakers without killing active matches"],
         ["How does Agones prevent Kubernetes from terminating a container with an active 40-minute match?"],
         ["Treating stateful dedicated game servers as stateless microservices"]),
        ("distributed_state_redis", "Player Sessions & Ephemeral State with Redis", "Presence tracking, active match routing, distributed locks, session tokens, heartbeat timeouts", "Core", "core", "essential", "intermediate", 30, ["matchmaking_rating_systems"],
         ["Manage global player presence and active game server routing tables using Redis", "Implement distributed locks and heartbeats to cleanly evict dropped player sessions"],
         ["Why is an in-memory store like Redis required for matchmaking queues rather than relational DBs?"],
         ["Relying on database polling every second to check player online status"]),
        ("game_economy_inventory_db", "Player Inventories, Economy & Transactional Databases", "ACID transactions, PostgreSQL, item minting, dupe glitch prevention, currency ledgers", "Core", "core", "essential", "intermediate", 30, ["distributed_state_redis"],
         ["Design double-entry bookkeeping ledgers for virtual currencies preventing duplication glitches", "Enforce strict database transactions with optimistic locking during item trades"],
         ["Explain how asynchronous inventory saving can lead to item duplication during sudden server crashes."],
         ["Modifying player inventory balances without strict database row locks"]),
        ("anti_cheat_server_validation", "Anti-Cheat Architecture & Server-Side Heuristics", "Heuristic anomaly detection, speed/teleport validation, aimbot statistical analysis, fog-of-war", "Advanced", "advanced", "essential", "advanced", 35, ["authoritative_simulation_reconciliation"],
         ["Implement server-side velocity clamping and geometric raycast validation to block wallhacks", "Detect statistical anomalies in aimbot angular acceleration and impossible reaction times"],
         ["Why is server-side validation the only foolproof defense against game memory manipulation?"],
         ["Believing client-side anti-cheat software alone is enough to prevent cheating"]),
        ("chat_social_voice_backend", "In-Game Chat, Social Graphs & Voice Services", "Pub/Sub chat channels, profanity filtering, friend lists, party systems, WebRTC voice signaling", "Advanced", "advanced", "recommended", "intermediate", 30, ["distributed_state_redis"],
         ["Architect scalable real-time chat servers utilizing Redis Pub/Sub and Kafka", "Manage party invites, presence notifications, and WebRTC voice channel handshakes"],
         ["How do you route group voice packets efficiently without overloading the game simulation server?"],
         ["Running audio encoding and voice streaming directly through the game tick server thread"]),
        ("dynamic_liveops_content", "LiveOps, Dynamic Configuration & Content Delivery", "Remote config, feature flags, hot patching game data, seasonal events, CDN asset bundles", "Advanced", "advanced", "recommended", "intermediate", 25, ["game_economy_inventory_db"],
         ["Build remote configuration systems to adjust weapon balance parameters without client updates", "Distribute seasonal game asset bundles securely via global Content Delivery Networks (CDNs)"],
         ["Why should game design balance parameters be dynamically configurable from the server?"],
         ["Hardcoding game balance values directly into compiled client executables"]),
        ("game_telemetry_analytics", "Game Telemetry, Logging & Analytics at Scale", "Event ingestion, Kafka, ClickHouse, kill heatmaps, retention funnels, combat balance telemetry", "Advanced", "advanced", "recommended", "advanced", 35, ["dynamic_liveops_content"],
         ["Stream high-volume player gameplay telemetry events into Kafka and ClickHouse", "Generate spatial heatmaps of player deaths and weapon usage to identify balance anomalies"],
         ["Why is columnar storage (ClickHouse) optimal for analyzing billions of game telemetry events?"],
         ["Logging high-frequency player movement events directly into the transactional inventory database"]),
        ("load_testing_bot_simulations", "Load Testing Game Servers with Headless Bots", "Simulated virtual players, stress testing tick rates, simulating network jitter, benchmarking egress", "Advanced", "advanced", "essential", "advanced", 35, ["networking_udp_vs_tcp", "server_orchestration_agones"],
         ["Build headless bot clients simulating hundreds of concurrent players firing and moving", "Benchmark server CPU tick stability, memory allocation, and bandwidth under heavy combat"],
         ["What metrics indicate that a game server tick loop is suffocating under load?"],
         ["Testing server capacity with simple HTTP requests instead of realistic UDP socket simulations"]),
        ("zero_downtime_fleet_updates", "Fleet Rolling Updates & Zero-Downtime Deployments", "Multi-version game client support, draining old fleets, Blue/Green game server migrations", "Advanced", "advanced", "recommended", "advanced", 30, ["server_orchestration_agones"],
         ["Coordinate fleet updates allowing older game clients to finish matches while new versions deploy", "Drain game server instances gracefully without disrupting active matches"],
         ["How do you manage client-server version compatibility when deploying a hotfix patch?"],
         ["Force-terminating running game instances during a fleet software update"]),
        ("multi_region_cloud_routing", "Global Multi-Region Architecture & Anycast Routing", "Edge routing, Anycast, minimizing player RTT, cross-region matchmaking, DDoS mitigation", "Mastery", "capstone", "essential", "expert", 35, ["server_orchestration_agones", "matchmaking_rating_systems"],
         ["Deploy game server clusters across multiple global cloud regions with latency-based routing", "Mitigate large-scale UDP amplification DDoS attacks targeting game server ports"],
         ["How does Anycast DNS/BGP routing direct players to the closest physical server cluster?"],
         ["Centralizing all dedicated servers in a single geographic data center for global players"]),
        ("server_side_game_capstone", "Full Multiplayer Backend Architecture Capstone", "Complete stack: matchmaking, Agones fleet, dedicated UDP server, Redis state, inventory DB & liveops", "Mastery", "capstone", "essential", "expert", 40, ["multi_region_cloud_routing", "anti_cheat_server_validation"],
         ["Architect and deploy a scalable, resilient backend infrastructure supporting real-time multiplayer games", "Integrate automated matchmaking, container orchestration, server reconciliation, and telemetry pipelines"],
         ["What are the key operational runbooks required for operating an online multiplayer game launch?"],
         ["Launching an online game without capacity headroom, automated fleet scaling, or DDoS protection"])
    ]

    # 4. DSA PROBLEM SOLVING (18 nodes)
    dsa = [
        ("complexity_analysis_big_o", "Complexity Analysis & Big-O Foundations", "Time vs Space complexity, asymptotic analysis (O, Omega, Theta), amortized analysis, recursion tree", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Calculate exact Big-O time and space complexity for iterative and recursive algorithms", "Analyze amortized time complexity for dynamic arrays and hash tables"],
         ["Explain the difference between O(1) amortized insertion and O(N) worst-case insertion in a dynamic array."],
         ["Assuming that fewer lines of code automatically equals faster Big-O execution time"]),
        ("arrays_two_pointers", "Arrays, Strings & Two-Pointer Techniques", "Opposite-direction pointers, same-direction pointers, palindrome verification, trapped rainwater, in-place swaps", "Foundations", "foundation", "essential", "beginner", 30, ["complexity_analysis_big_o"],
         ["Apply two-pointer patterns to solve search and partition problems in O(N) time and O(1) space", "Solve classic problems: Two Sum II, Container With Most Water, In-place Duplicate Removal"],
         ["Why is the two-pointer approach optimal for sorted array target search compared to nested loops?"],
         ["Allocating extra array memory when an in-place two-pointer swap is achievable"]),
        ("sliding_window_prefix_sums", "Sliding Window & Prefix Sum Patterns", "Fixed-size window, dynamic-size window, subarray sum equals K, longest substring without repeats", "Foundations", "foundation", "essential", "beginner", 30, ["arrays_two_pointers"],
         ["Maintain running window state to solve dynamic contiguous subarray and substring problems", "Precompute prefix sum arrays to answer range sum queries in O(1) time"],
         ["Explain how the sliding window technique reduces an O(N^2) brute-force check to O(N) linear time."],
         ["Recomputing entire window sums from scratch instead of adding incoming and subtracting outgoing elements"]),
        ("linked_lists_fast_slow", "Linked Lists & Fast/Slow Pointer Pattern", "Singly/doubly linked lists, cycle detection (Floyd's algorithm), middle of list, list reversal", "Foundations", "foundation", "essential", "beginner", 25, ["complexity_analysis_big_o"],
         ["Reverse singly and doubly linked lists iteratively and recursively in O(1) auxiliary space", "Detect cycles and locate cycle entry points using Floyd's Tortoise and Hare algorithm"],
         ["Why does Floyd's fast/slow pointer algorithm guarantee meeting inside a cycle?"],
         ["Losing reference pointers during node swaps, causing memory leaks or infinite loops"]),
        ("stacks_queues_monotonic", "Stacks, Queues & Monotonic Stack Patterns", "LIFO/FIFO mechanics, parentheses matching, monotonic increasing/decreasing stacks, next greater element", "Foundations", "foundation", "essential", "intermediate", 30, ["linked_lists_fast_slow"],
         ["Utilize monotonic stacks to find Next Greater Element and Largest Rectangle in Histogram in O(N)", "Implement queue functionality using two stacks with amortized O(1) operations"],
         ["Explain how a monotonic stack maintains sorted order while finding nearest greater elements."],
         ["Using nested loops to search for next greater elements, resulting in O(N^2) timeouts"]),
        ("recursion_backtracking", "Recursion & Combinatorial Backtracking", "Recursion stack, call frames, permutations, subsets, combination sum, N-Queens, pruning state trees", "Core", "core", "essential", "intermediate", 35, ["stacks_queues_monotonic"],
         ["Model problem search spaces as state trees and prune invalid search paths early", "Generate all permutations, subsets, and combinations with correct backtracking state restoration"],
         ["What is backtracking state restoration and why must changes be undone after the recursive call?"],
         ["Passing copies of large arrays at every recursion step instead of backtracking in-place"]),
        ("hashing_collision_resolution", "Hash Tables & Hash Map Optimization", "Hash functions, collision resolution (chaining vs open addressing), load factor, amortized lookup", "Core", "core", "essential", "beginner", 25, ["complexity_analysis_big_o"],
         ["Analyze how hash table resizing and load factor impact amortized O(1) operations", "Leverage hash maps and sets for frequency counting and O(1) membership lookups"],
         ["What happens to hash table performance when a bad hash function produces frequent collisions?"],
         ["Assuming hash table operations are strictly O(1) in the worst-case (they degrade to O(N))"]),
        ("binary_search_advanced", "Binary Search & Search Space Reduction", "Binary search template, search in rotated sorted array, binary search on answer space (Koko eating bananas)", "Core", "core", "essential", "intermediate", 30, ["arrays_two_pointers"],
         ["Apply binary search templates avoiding off-by-one errors (left <= right vs left < right)", "Solve optimization problems using binary search on answer spaces (monotonic feasibility functions)"],
         ["How do you recognize when a problem can be solved by binary search on the answer space?"],
         ["Calculating midpoint using `(left + right) / 2` which can cause integer overflow in languages like C++/Java"]),
        ("trees_binary_search_trees", "Binary Trees & Tree Traversals (DFS / BFS)", "Pre/in/post-order traversals, level-order BFS, BST properties, Lowest Common Ancestor (LCA), diameter", "Core", "core", "essential", "intermediate", 30, ["recursion_backtracking"],
         ["Implement iterative and recursive DFS and queue-based BFS level-order traversals", "Validate binary search trees and find lowest common ancestors in O(H) time"],
         ["Why does an in-order traversal of a Binary Search Tree always yield values in sorted order?"],
         ["Confusing binary trees with binary search trees"]),
        ("heaps_priority_queues", "Heaps & Priority Queues (Top-K Patterns)", "Min-heap vs max-heap, heapify, finding Kth largest, median of a data stream, merge K sorted lists", "Core", "core", "essential", "intermediate", 30, ["trees_binary_search_trees"],
         ["Solve Top-K frequent elements and streaming median problems in O(N log K) time", "Construct heaps from raw arrays in O(N) linear time using bottom-up heapify"],
         ["Why does building a heap take O(N) time while inserting N elements one-by-one takes O(N log N)?"],
         ["Sorting an entire array of N elements in O(N log N) when only top K elements are needed"]),
        ("graphs_traversals_bfs_dfs", "Graph Foundations & Traversals (BFS / DFS)", "Adjacency matrix vs list, connected components, cycle detection in directed/undirected graphs, bipartite graphs", "Core", "core", "essential", "intermediate", 35, ["trees_binary_search_trees"],
         ["Traverse directed and undirected graphs using BFS and DFS while tracking visited states", "Detect cycles in directed graphs using 3-color DFS (unvisited, visiting, visited)"],
         ["What happens if you forget to mark nodes as visited during graph BFS or DFS?"],
         ["Assuming graphs are always connected or acyclic without checking"]),
        ("graph_algorithms_shortest_path", "Shortest Paths & Topological Sort", "Dijkstra's algorithm, Kahn's algorithm (topological sort), course schedule, Bellman-Ford basics", "Advanced", "advanced", "essential", "intermediate", 35, ["graphs_traversals_bfs_dfs", "heaps_priority_queues"],
         ["Implement Dijkstra's algorithm with a priority queue to find shortest paths in weighted graphs", "Detect dependency cycles and establish build orders using Kahn's topological sort"],
         ["Why does Dijkstra's algorithm fail when edges have negative weights?"],
         ["Attempting to use simple BFS to find shortest paths on graphs with varying edge weights"]),
        ("dynamic_programming_1d", "Dynamic Programming: 1D Memoization & Tabulation", "Optimal substructure, overlapping subproblems, top-down memoization vs bottom-up tabulation, space optimization", "Core", "core", "essential", "intermediate", 35, ["recursion_backtracking"],
         ["Identify optimal substructure and overlapping subproblems in recursive formulations", "Transition from exponential recursion to linear O(N) DP with O(1) space optimization (Climbing Stairs, House Robber)"],
         ["Explain how memoization eliminates redundant recursive recalculations."],
         ["Memorizing solutions without writing down the explicit mathematical recurrence relation first"]),
        ("dynamic_programming_2d", "Dynamic Programming: 2D Grids & Strings", "Grid paths, Longest Common Subsequence (LCS), Edit Distance, 0/1 Knapsack, unbounded knapsack", "Advanced", "advanced", "essential", "advanced", 40, ["dynamic_programming_1d"],
         ["Solve 2D grid pathfinding and string edit distance problems using 2D tabulation matrices", "Optimize 2D dynamic programming memory consumption from O(M*N) to O(N) rolling arrays"],
         ["Walk through the recurrence relation for Edit Distance (Insert, Delete, Replace)."],
         ["Mixing up row and column indices when referencing prior subproblem states"]),
        ("intervals_greedy_algorithms", "Interval Scheduling & Greedy Algorithms", "Interval merging, meeting rooms, non-overlapping intervals, greedy choice property vs DP", "Advanced", "advanced", "essential", "intermediate", 30, ["arrays_two_pointers"],
         ["Sort intervals by start or end times to solve interval overlap and consolidation problems", "Determine when a greedy local choice guarantees global optimality versus when DP is required"],
         ["Why must intervals be sorted by end time in the activity selection greedy algorithm?"],
         ["Assuming a greedy algorithm works without proving the greedy-choice property"]),
        ("trie_string_matching", "Trie (Prefix Tree) & String Matching", "Trie node architecture, insert/search/startsWith, autocomplete, Word Search II, KMP overview", "Advanced", "advanced", "recommended", "intermediate", 30, ["trees_binary_search_trees"],
         ["Build prefix trees (Trie) supporting O(L) prefix search, auto-completion, and wildcard matching", "Combine Tries with backtracking DFS to solve multi-word grid search problems efficiently"],
         ["Why is a Trie faster than a hash set for prefix queries like 'startsWith(str)'?"],
         ["Creating unindexed string slices repeatedly, resulting in severe memory allocation"]),
        ("union_find_disjoint_sets", "Disjoint Set Union (DSU) & Union-Find", "Find with path compression, Union by rank/size, Kruskal's Minimum Spanning Tree, redundant connections", "Advanced", "advanced", "essential", "advanced", 35, ["graphs_traversals_bfs_dfs"],
         ["Implement Disjoint Set Union with path compression and union by rank achieving near O(1) alpha(N)", "Detect redundant graph connections and find Minimum Spanning Trees using Kruskal's algorithm"],
         ["Explain how path compression flattens the tree during find operations to achieve amortized O(1)."],
         ["Performing naive union operations without tracking tree rank, creating degenerate O(N) linked lists"]),
        ("dsa_mastery_capstone", "Advanced Problem-Solving Strategy & Interview Mastery", "Pattern recognition taxonomy, space-time trade-offs, edge-case checklist, mock interview performance", "Mastery", "capstone", "essential", "expert", 40, ["dynamic_programming_2d", "union_find_disjoint_sets", "graph_algorithms_shortest_path"],
         ["Rapidly categorize unseen problems into core algorithmic patterns within 3 minutes", "Write clean, bug-free, production-quality code under timed interview pressure with full test verification"],
         ["How do you systematically debug a failing test case during a live coding technical interview?"],
         ["Jumping immediately into writing code before dry-running edge cases and stating complexity"])
    ]

    specs = [
        {
            "id": "roadmap_blockchain",
            "slug": "blockchain",
            "title": "Blockchain Developer",
            "description": "Comprehensive curriculum covering cryptography, EVM architecture, Solidity, ERC standards, Foundry, Web3 frontends, smart contract security, DeFi protocols, L2 rollups, and zero-knowledge proofs.",
            "category": "Web3 & Blockchain",
            "difficulty_level": "advanced",
            "estimated_hours": 90,
            "tags": ["blockchain", "ethereum", "solidity", "evm", "smart-contracts", "defi", "web3", "foundry"],
            "phases": [
                {"title": "Cryptographic & EVM Foundations", "tier": "foundation", "focus": "Cryptography, Merkle Trees, Consensus (PoW/PoS), EVM Gas & State Mechanics", "estimated_weeks": 3},
                {"title": "Smart Contract Core & Tooling", "tier": "core", "focus": "Solidity, ERC Tokens, Foundry/Hardhat, Web3 Frontends & Reentrancy Security", "estimated_weeks": 4},
                {"title": "DeFi, Oracles & Scaling", "tier": "advanced", "focus": "AMMs, Chainlink Oracles, Layer 2 Rollups, ZKPs, Subgraphs & Smart Contract Auditing", "estimated_weeks": 4},
                {"title": "Governance, MEV & Protocol Capstone", "tier": "capstone", "focus": "DAOs, Multi-Sig Security, MEV Searchers, and Production DApp Launch", "estimated_weeks": 2}
            ],
            "nodes": [
                make_node("blockchain", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(bc)
            ]
        },
        {
            "id": "roadmap_game_developer",
            "slug": "game-developer",
            "title": "Game Developer",
            "description": "End-to-end game development: 2D/3D game math, game loops, physics & collisions, engine architecture, input juice, state machines, animations, audio, AI (A* and behavior trees), shaders, optimization, and game publishing.",
            "category": "Game Development",
            "difficulty_level": "intermediate",
            "estimated_hours": 90,
            "tags": ["game-dev", "unity", "unreal", "csharp", "shaders", "physics", "game-ai", "optimization"],
            "phases": [
                {"title": "Game Math & Architecture Foundations", "tier": "foundation", "focus": "Vector Math, Game Loop Timesteps, Collision Detection & Engine Component Hierarchies", "estimated_weeks": 3},
                {"title": "Gameplay Systems & AI Core", "tier": "core", "focus": "Player Input Juice, State Machines, Blend Trees, Adaptive Audio & Behavior Tree AI", "estimated_weeks": 4},
                {"title": "Visuals, Shaders & Optimization", "tier": "advanced", "focus": "HLSL Shaders, GPU Particles, Level Design, Save Systems & Profiling Optimization", "estimated_weeks": 4},
                {"title": "Multiplayer & Commercial Capstone", "tier": "capstone", "focus": "Client-Side Prediction, Responsive Game UI, and Polished Vertical Slice Release", "estimated_weeks": 2}
            ],
            "nodes": [
                make_node("game-developer", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(gd)
            ]
        },
        {
            "id": "roadmap_server_side_game_developer",
            "slug": "server-side-game-developer",
            "title": "Server-Side Game Developer",
            "description": "Master multiplayer backend engineering: authoritative game servers, low-latency UDP protocols, spatial partitioning, lag compensation, matchmaking, Agones Kubernetes orchestration, Redis state, and anti-cheat.",
            "category": "Game Development",
            "difficulty_level": "advanced",
            "estimated_hours": 95,
            "tags": ["game-server", "networking", "udp", "agones", "kubernetes", "matchmaking", "anti-cheat", "low-latency"],
            "phases": [
                {"title": "Network & Physics Foundations", "tier": "foundation", "focus": "Dedicated Servers, Reliable UDP, Binary Delta Compression & Spatial Partitioning Grids", "estimated_weeks": 3},
                {"title": "State Authority & Orchestration", "tier": "core", "focus": "Server Physics Reconciliation, Lag Rewind, Matchmaking MMR, Agones K8s & Redis Presence", "estimated_weeks": 4},
                {"title": "Anti-Cheat, Scale & LiveOps", "tier": "advanced", "focus": "Anti-Cheat Validation, In-Game Chat, Dynamic LiveOps, Telemetry & Headless Bot Testing", "estimated_weeks": 4},
                {"title": "Global Infrastructure Capstone", "tier": "capstone", "focus": "Zero-Downtime Fleets, Multi-Region Anycast Routing, and Multiplayer Backend Capstone", "estimated_weeks": 2}
            ],
            "nodes": [
                make_node("server-side-game-developer", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(ssgd)
            ]
        },
        {
            "id": "roadmap_dsa_problem_solving",
            "slug": "dsa_problem_solving",
            "title": "Data Structures & Algorithms (Problem Solving)",
            "description": "Rigorous mastery of DSA patterns for software engineering interviews: Big-O, two-pointers, sliding window, fast/slow pointers, monotonic stacks, backtracking, binary search, trees, graphs, 1D/2D dynamic programming, and tries.",
            "category": "Computer Science & Problem Solving",
            "difficulty_level": "intermediate",
            "estimated_hours": 90,
            "tags": ["dsa", "algorithms", "data-structures", "dynamic-programming", "graphs", "leetcode", "problem-solving"],
            "phases": [
                {"title": "Complexity & Linear Data Structures", "tier": "foundation", "focus": "Big-O Analysis, Two-Pointers, Sliding Window, Linked Lists & Monotonic Stacks", "estimated_weeks": 3},
                {"title": "Trees, Recursion & Core Algorithms", "tier": "core", "focus": "Backtracking, Hash Tables, Advanced Binary Search, Trees/BFS/DFS & Heaps", "estimated_weeks": 4},
                {"title": "Graphs, DP & Advanced Structures", "tier": "advanced", "focus": "Shortest Paths, 1D & 2D Dynamic Programming, Intervals, Tries & Disjoint Set Union", "estimated_weeks": 4},
                {"title": "Mastery & Technical Interview Capstone", "tier": "capstone", "focus": "Pattern Recognition Taxonomy, Space-Time Trade-offs & Timed Interview Mastery", "estimated_weeks": 2}
            ],
            "nodes": [
                make_node("dsa_problem_solving", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(dsa)
            ]
        }
    ]
    return specs
