"""
Infrastructure and Cloud Track Specifications for SkillTwin.
Contains comprehensive 18-node curricula for:
- devops (18 nodes)
- devsecops (18 nodes)
- cyber-security (18 nodes)
- network-engineer (18 nodes)
- postgresql (18 nodes)
- system_design_cloud (18 nodes)
- software-architect (18 nodes)
"""

from typing import Dict, Any, List
from app.scripts.curriculum_specs.specs_web_mobile import make_node


def get_infra_cloud_specs() -> List[Dict[str, Any]]:
    # 1. DEVOPS (18 nodes)
    devops_nodes = [
        ("linux_fundamentals_shell", "Linux Administration & Bash Scripting", "File systems, permissions, processes, systemd, bash automation, pipe redirection", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Manage Linux system processes and user permissions securely", "Write robust bash automation scripts with error handling (set -euo pipefail)"],
         ["Why should production bash scripts always begin with 'set -euo pipefail'?"],
         ["Running production scripts as root without least-privilege service accounts"]),
        ("networking_dns_ssh", "Networking Fundamentals: DNS, SSH & Firewalls", "TCP/IP, DNS records (A, CNAME, TXT), SSH key pairs, iptables/ufw firewalls, NAT", "Foundations", "foundation", "essential", "beginner", 25, ["linux_fundamentals_shell"],
         ["Configure passwordless SSH authentication and troubleshoot connection failures", "Manage DNS records and configure host-level firewall rules"],
         ["How does asymmetric cryptography secure SSH connections without transmitting private keys?"],
         ["Leaving SSH password authentication enabled on public internet-facing servers"]),
        ("git_automation_workflows", "Git Workflows & Trunk-Based Development", "Git branching models, merge vs rebase, git hooks, commit signing with GPG", "Foundations", "foundation", "essential", "beginner", 25, ["linux_fundamentals_shell"],
         ["Implement trunk-based development with short-lived feature branches", "Automate local pre-commit verification using Git hooks"],
         ["Why does trunk-based development lead to faster release cadence than long-lived GitFlow branches?"],
         ["Maintaining long-lived divergent feature branches that result in merge hell"]),
        ("docker_containerization_mechanics", "Docker Containerization & Linux Namespaces", "Linux namespaces, cgroups, Dockerfile instructions, layer caching, image optimization", "Core", "intermediate", "essential", "intermediate", 30, ["linux_fundamentals_shell"],
         ["Explain how Linux namespaces and cgroups isolate container processes", "Author optimized multi-stage Dockerfiles that maximize build cache efficiency"],
         ["Explain the technical difference between a virtual machine (hypervisor) and a Docker container (namespaces/cgroups)."],
         ["Thinking containers are full virtual machines running separate guest OS kernels"]),
        ("docker_compose_multi_container", "Multi-Container Orchestration with Docker Compose", "Compose specifications, container networking, volumes, environment variables", "Core", "intermediate", "recommended", "beginner", 25, ["docker_containerization_mechanics"],
         ["Orchestrate multi-tier local environments (web, api, database, cache) with Docker Compose", "Manage persistent volume storage and custom bridge networks"],
         ["How does Docker Compose DNS resolution enable containers to communicate by service name?"],
         ["Hardcoding container IP addresses instead of using Docker internal service discovery"]),
        ("ci_cd_github_actions", "CI/CD Pipelines with GitHub Actions", "Workflows, runners, jobs, steps, environment secrets, matrix builds, caching dependencies", "Core", "intermediate", "essential", "intermediate", 30, ["git_automation_workflows"],
         ["Build automated continuous integration pipelines testing PRs on every commit", "Configure dependency caching to cut pipeline execution times"],
         ["What is the fundamental purpose of Continuous Integration (CI) in modern software delivery?"],
         ["Hardcoding cloud deployment credentials directly into workflow YAML files instead of encrypted secrets"]),
        ("kubernetes_core_architecture", "Kubernetes Architecture & Core Concepts", "Control plane, kubelet, API server, etcd, Pods, Deployments, ReplicaSets", "Core", "intermediate", "essential", "intermediate", 35, ["docker_containerization_mechanics"],
         ["Explain how the Kubernetes control plane reconciles desired state against actual state", "Deploy containerized applications declaratively using Pods and Deployments"],
         ["Explain the role of etcd in a Kubernetes cluster and why its high availability is vital."],
         ["Deploying raw individual Pods directly instead of using managed Deployments"]),
        ("kubernetes_networking_services", "Kubernetes Networking, Services & Ingress", "ClusterIP, NodePort, LoadBalancer, Ingress controllers, Ingress routing, cert-manager", "Core", "intermediate", "essential", "intermediate", 35, ["kubernetes_core_architecture"],
         ["Route internal service traffic using ClusterIP and external traffic using Ingress", "Automate TLS certificate issuance and renewal with cert-manager and Let's Encrypt"],
         ["Explain how a Kubernetes ClusterIP Service load balances traffic across multiple backend Pods."],
         ["Exposing internal backend databases directly to the public internet via NodePort"]),
        ("kubernetes_storage_configmaps", "Kubernetes Storage & Configuration", "ConfigMaps, Secrets, PersistentVolumes, PersistentVolumeClaims, StorageClasses", "Applied", "intermediate", "recommended", "intermediate", 30, ["kubernetes_core_architecture"],
         ["Decouple application configuration using ConfigMaps and encrypted Secrets", "Provision dynamic cloud storage using PersistentVolumeClaims and StorageClasses"],
         ["Why should application configuration be injected via ConfigMaps rather than baked into container images?"],
         ["Storing plain base64-encoded Kubernetes Secrets in public Git repositories"]),
        ("infrastructure_as_code_terraform", "Infrastructure as Code (IaC) with Terraform", "HCL syntax, providers, resources, variables, state management, terraform plan/apply", "Applied", "intermediate", "essential", "intermediate", 35, ["networking_dns_ssh"],
         ["Provision cloud infrastructure declaratively using Terraform and HCL", "Manage remote state locking securely using S3 and DynamoDB"],
         ["Why is Terraform state locking essential when multiple engineers collaborate on infrastructure?"],
         ["Manually modifying cloud resources in the web console, causing state drift"]),
        ("terraform_modules_environments", "Terraform Modules & Multi-Environment Deployments", "Reusable modules, outputs, remote backends, dev/staging/prod workspace separation", "Applied", "intermediate", "recommended", "intermediate", 30, ["infrastructure_as_code_terraform"],
         ["Author reusable, parameterized Terraform modules following industry best practices", "Manage separated environments (dev, staging, prod) with isolated state files"],
         ["How do Terraform modules enforce DRY (Don't Repeat Yourself) principles in infrastructure?"],
         ["Sharing a single Terraform state file across development and production environments"]),
        ("cloud_architecture_aws_gcp", "Cloud Infrastructure: VPC, Compute & IAM", "VPCs, public/private subnets, NAT gateways, security groups, IAM least privilege", "Applied", "intermediate", "essential", "intermediate", 35, ["infrastructure_as_code_terraform"],
         ["Architect secure Virtual Private Clouds (VPC) with isolated private database subnets", "Enforce strict least-privilege IAM policies for compute services and users"],
         ["Why should production database instances always reside in private subnets with no public IPs?"],
         ["Assigning broad administrator permissions (AdministratorAccess) to service accounts"]),
        ("observability_prometheus_grafana", "Observability: Metrics with Prometheus & Grafana", "Time-series metrics, PromQL, exporters, Grafana dashboards, alerting rules", "Advanced", "advanced", "essential", "advanced", 35, ["kubernetes_core_architecture"],
         ["Instrument systems and extract metrics using node-exporter and Prometheus", "Design informative Grafana dashboards and configure multi-channel alerting rules"],
         ["What are the Four Golden Signals of monitoring (Latency, Traffic, Errors, Saturation)?"],
         ["Setting up threshold alerts without clear runbooks, resulting in alert fatigue"]),
        ("centralized_logging_loki_elk", "Centralized Logging: Loki & ELK Stack", "Log aggregation, FluentBit, Promtail, Grafana Loki, structured log queries", "Advanced", "advanced", "recommended", "intermediate", 30, ["observability_prometheus_grafana"],
         ["Collect and aggregate container logs across cluster nodes using FluentBit/Promtail", "Query logs with LogQL and correlate log messages with Prometheus metric spikes"],
         ["Why is log aggregation essential in distributed multi-pod Kubernetes clusters?"],
         ["SSHing into individual nodes to view raw log files during production outages"]),
        ("site_reliability_slo_sli", "Site Reliability Engineering: SLIs, SLOs & Error Budgets", "Service Level Indicators (SLIs), Service Level Objectives (SLOs), error budgets, blameless postmortems", "Advanced", "advanced", "recommended", "advanced", 30, ["observability_prometheus_grafana"],
         ["Define measurable SLIs and realistic SLO targets for production services", "Manage release velocity using error budgets and conduct blameless postmortems"],
         ["How does an error budget balance innovation velocity against system reliability?"],
         ["Treating 100% uptime as an SLO, creating prohibitive costs and stifling feature releases"]),
        ("secret_management_vault", "Secret Management with HashiCorp Vault", "Dynamic secrets, encryption-as-a-service, Vault agent injector in Kubernetes, secret rotation", "Production", "advanced", "recommended", "advanced", 35, ["cloud_architecture_aws_gcp"],
         ["Inject dynamic credentials into Kubernetes Pods securely using HashiCorp Vault", "Enforce automatic secret rotation policies across cloud infrastructure"],
         ["Why are dynamic, short-lived secrets safer than long-lived static credentials?"],
         ["Storing long-lived database passwords in static configuration files"]),
        ("gitops_continuous_delivery_argocd", "GitOps & Declarative Delivery with ArgoCD", "GitOps principles, ArgoCD, declarative sync, automated drift detection, rollbacks", "Production", "advanced", "essential", "advanced", 35, ["kubernetes_networking_services"],
         ["Implement GitOps continuous delivery where Git is the single source of truth", "Automate cluster deployment synchronization and handle one-click rollbacks with ArgoCD"],
         ["Explain how GitOps eliminates manual kubectl deployments and prevents configuration drift."],
         ["Modifying live cluster resources using kubectl directly, bypassing Git version control"]),
        ("disaster_recovery_backup_dr", "Disaster Recovery, High Availability & Chaos Engineering", "Multi-region failover, automated backups, RTO/RPO metrics, chaos engineering principles", "Production", "advanced", "essential", "advanced", 35, ["cloud_architecture_aws_gcp"],
         ["Calculate Recovery Time Objective (RTO) and Recovery Point Objective (RPO) for critical services", "Test system resilience and fault-tolerance using chaos engineering experiments"],
         ["What is the difference between RTO (how fast you recover) and RPO (how much data you lose)?"],
         ["Assuming backups work without conducting scheduled disaster recovery restore tests"])
    ]

    # 2. DEVSECOPS (18 nodes)
    devsecops_nodes = [
        ("security_threat_modeling", "DevSecOps Fundamentals & Threat Modeling", "CIA triad, STRIDE threat modeling, shift-left security, security champions model", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Apply STRIDE threat modeling to identify architectural vulnerabilities early", "Integrate security requirements into early product sprint planning"],
         ["How does 'shifting left' reduce the exponential cost of fixing security bugs in production?"],
         ["Treating security as a blocking gate at the very end of the release cycle"]),
        ("secret_scanning_precommit", "Secret Detection & Git Pre-Commit Hooks", "TruffleHog, Gitleaks, pre-commit hooks, secret revocation, entropy analysis", "Foundations", "foundation", "essential", "beginner", 25, ["security_threat_modeling"],
         ["Block accidental secret commits locally using automated pre-commit scanners", "Execute enterprise Git repository scans for historical credential leaks"],
         ["Why is deleting a leaked secret in a new commit insufficient to secure the credential?"],
         ["Assuming private Git repositories are safe for storing hardcoded API credentials"]),
        ("sast_code_analysis", "Static Application Security Testing (SAST)", "Semgrep, SonarQube, abstract syntax tree (AST) rules, finding injection flaws", "Core", "intermediate", "essential", "intermediate", 30, ["security_threat_modeling"],
         ["Automate static source code analysis in CI pipelines using Semgrep/SonarQube", "Differentiate true positives from noise and author custom linting rules"],
         ["How does SAST analyze code without executing it, and what are its limitations regarding runtime context?"],
         ["Relying exclusively on SAST tools without performing dynamic or interactive testing"]),
        ("sca_dependency_vulnerabilities", "Software Composition Analysis (SCA) & SBOM", "Snyk, Dependabot, CVE tracking, CVSS severity scoring, Software Bill of Materials (SBOM)", "Core", "intermediate", "essential", "intermediate", 25, ["sast_code_analysis"],
         ["Scan open-source third-party dependencies for known CVE vulnerabilities", "Generate and verify CycloneDX Software Bill of Materials (SBOM) in CI"],
         ["What is a transitive dependency vulnerability and why is it dangerous?"],
         ["Ignoring CVE alerts with medium severity that can be chained into remote code execution"]),
        ("container_image_scanning", "Container Security & Vulnerability Scanning", "Trivy, Grype, Docker base image hardening, rootless containers, distroless images", "Core", "intermediate", "essential", "intermediate", 30, ["sca_dependency_vulnerabilities"],
         ["Scan Docker container images for OS-level and application CVEs using Trivy", "Harden container images by adopting non-root users and minimal distroless bases"],
         ["Why do distroless container images dramatically reduce an application's attack surface?"],
         ["Using heavy full-OS base images (like ubuntu:latest) with package managers in production"]),
        ("dast_dynamic_scanning", "Dynamic Application Security Testing (DAST)", "OWASP ZAP, DAST automation, active vs passive scans, API vulnerability probing", "Core", "intermediate", "recommended", "intermediate", 30, ["sast_code_analysis"],
         ["Automate dynamic web application vulnerability scanning against staging environments", "Detect runtime vulnerabilities such as SQL injection and cross-site scripting (XSS)"],
         ["How does DAST differ from SAST in detecting runtime authentication and session flaws?"],
         ["Running destructive active DAST scans directly against live production customer databases"]),
        ("iac_security_scanning", "Infrastructure as Code (IaC) Security & Misconfigurations", "tfsec, Checkov, Kube-bench, CIS benchmarks, open security group detection", "Applied", "intermediate", "essential", "intermediate", 30, ["sast_code_analysis"],
         ["Scan Terraform configurations and Kubernetes manifests for security anti-patterns", "Enforce CIS benchmarks on cloud infrastructure before provisioning"],
         ["Why is preventing cloud misconfigurations in Terraform easier than fixing them after cloud deployment?"],
         ["Allowing public 0.0.0.0/0 ingress access to cloud database instances"]),
        ("ci_security_gates", "Automated Security Quality Gates in CI/CD", "GitHub Actions security workflows, SARIF reports, policy-as-code with OPA/Conftest", "Applied", "intermediate", "essential", "intermediate", 30, ["iac_security_scanning"],
         ["Implement automated build-breaking security gates for critical CVSS vulnerabilities", "Centralize vulnerability reporting using standardized SARIF format in GitHub"],
         ["How do automated security quality gates prevent known vulnerabilities from reaching production?"],
         ["Allowing developers to bypass security pipeline failures without security team sign-off"]),
        ("k8s_rbac_admission_control", "Kubernetes Hardening, RBAC & Admission Controllers", "Kubernetes RBAC, ServiceAccounts, OPA Gatekeeper, Kyverno policy enforcement", "Applied", "intermediate", "essential", "advanced", 35, ["iac_security_scanning"],
         ["Enforce strict Kubernetes RBAC policies adhering to least privilege", "Block non-compliant Pods using Kyverno or OPA Gatekeeper admission controllers"],
         ["Why should default ServiceAccounts never be granted cluster-admin permissions?"],
         ["Granting developer Pods hostPath volume mounts that allow root filesystem escape"]),
        ("network_policies_service_mesh", "Container Network Security & Micro-segmentation", "Kubernetes NetworkPolicies, Calico, mTLS service mesh with Istio/Linkerd", "Applied", "intermediate", "recommended", "advanced", 35, ["k8s_rbac_admission_control"],
         ["Isolate sensitive database Pods using restrictive Kubernetes NetworkPolicies", "Enforce mutual TLS (mTLS) encryption for all inter-service microservice communications"],
         ["Why is default flat networking in Kubernetes a major lateral movement risk for attackers?"],
         ["Assuming internal cluster traffic is safe without encrypting network communications via mTLS"]),
        ("cloud_security_cspm", "Cloud Security Posture Management (CSPM)", "AWS Security Hub, GuardDuty, IAM credential auditing, least-privilege cloud roles", "Advanced", "advanced", "essential", "advanced", 35, ["iac_security_scanning"],
         ["Audit cloud environments continuously for IAM privilege escalation vectors", "Automate remediation of non-compliant cloud storage buckets and firewall rules"],
         ["How do attackers exploit AWS IAM role privilege escalation to gain administrative control?"],
         ["Generating long-lived static AWS access keys instead of using temporary IAM roles"]),
        ("runtime_security_falco", "Runtime Container Security & Threat Detection with Falco", "eBPF, Falco runtime rules, detecting shell spawns in containers, anomaly alerts", "Advanced", "advanced", "recommended", "advanced", 35, ["k8s_rbac_admission_control"],
         ["Detect and alert on unexpected runtime container behavior (shell execution, privilege escalation)", "Leverage eBPF kernel instrumentation for non-intrusive container monitoring"],
         ["How does Falco detect unauthorized command executions inside running production containers?"],
         ["Assuming that building secure container images eliminates the need for runtime monitoring"]),
        ("zero_trust_architecture", "Zero Trust Architecture & Identity-Aware Proxies", "Zero Trust principles (Never Trust, Always Verify), BeyondCorp, Cloudflare Access", "Advanced", "advanced", "recommended", "advanced", 30, ["cloud_security_cspm"],
         ["Design corporate and developer network access adhering to Zero Trust principles", "Replace legacy perimeter VPNs with Identity-Aware Proxies and contextual MFA"],
         ["Why is the traditional castle-and-moat network perimeter model obsolete for cloud environments?"],
         ["Trusting internal network connections purely based on IP subnet location"]),
        ("supply_chain_security_cosign", "Software Supply Chain Security & Artifact Signing", "SLSA framework, Sigstore / Cosign, cryptographic image signing, artifact provenance", "Production", "advanced", "essential", "advanced", 35, ["ci_security_gates"],
         ["Sign production container images cryptographically using Sigstore / Cosign", "Verify image provenance and cryptographic signatures at Kubernetes admission time"],
         ["Why is artifact signing essential to defend against software supply chain attacks (e.g., SolarWinds)?"],
         ["Pulling mutable container image tags like :latest without verifying cryptographic digests"]),
        ("compliance_soc2_iso", "Compliance Automation: SOC2, ISO 27001 & HIPAA", "Automated compliance evidence collection, Drata/Vanta integration, continuous audit", "Production", "advanced", "recommended", "intermediate", 30, ["cloud_security_cspm"],
         ["Automate infrastructure compliance evidence gathering for SOC 2 Type II audits", "Map technical cloud controls directly to ISO 27001 and HIPAA security standards"],
         ["What is the difference between a SOC 2 Type I report (point in time) and Type II (operating effectiveness)?"],
         ["Treating compliance as an annual manual screenshot-gathering exercise rather than continuous code"]),
        ("incident_response_forensics", "Incident Response, Cloud Forensics & Postmortems", "Incident classification, compromised instance isolation, memory dumps, blameless postmortems", "Production", "advanced", "essential", "advanced", 35, ["runtime_security_falco"],
         ["Execute structured incident response playbooks for compromised cloud workloads", "Perform forensic analysis on isolated virtual machines and author post-incident remediation plans"],
         ["Why should a compromised cloud instance be isolated via security groups rather than immediately terminated?"],
         ["Shutting down compromised servers immediately, destroying volatile memory evidence"]),
        ("vulnerability_management_triage", "Enterprise Vulnerability Management & Risk Prioritization", "Risk scoring (EPSS vs CVSS), SLA remediation timelines, exception workflows", "Production", "advanced", "recommended", "intermediate", 25, ["ci_security_gates"],
         ["Prioritize security patches using Exploit Prediction Scoring System (EPSS) and reachability", "Establish automated SLA tracking and developer exception review workflows"],
         ["Why does EPSS provide better remediation prioritization than relying solely on raw CVSS scores?"],
         ["Forcing developers to drop critical features to patch low-exploitability theoretical vulnerabilities"]),
        ("devsecops_culture_metrics", "DevSecOps Culture, Metrics & Program Maturation", "MTTR for vulnerabilities, security champion networks, developer security enablement", "Production", "advanced", "recommended", "intermediate", 25, ["security_threat_modeling"],
         ["Measure security program effectiveness using Mean Time to Remediate (MTTR)", "Scale security culture across engineering teams through security champion programs"],
         ["How do security champion networks scale security governance across large engineering organizations?"],
         ["Measuring security success solely by number of blocked PRs, creating friction with product teams"])
    ]

    # 3. CYBER SECURITY (18 nodes)
    cyber_nodes = [
        ("cyber_foundations_networking", "Networking Protocols & Packet Mechanics for Security", "OSI model, TCP/IP handshake, ARP spoofing, ICMP, DNS hijacking, Wireshark packet capture", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Analyze live network packet captures with Wireshark to identify anomalous traffic", "Explain the mechanics of ARP cache poisoning and Man-in-the-Middle (MitM) attacks"],
         ["How does ARP spoofing trick local network hosts into redirecting traffic to an attacker?"],
         ["Assuming encrypted HTTPS traffic cannot be subjected to SNI domain inspection"]),
        ("os_internals_linux_windows", "Operating System Security & Internals", "Linux permissions, setuid, Windows access tokens, registry hives, privilege levels", "Foundations", "foundation", "essential", "beginner", 25, ["cyber_foundations_networking"],
         ["Audit Linux and Windows user privileges, scheduled tasks, and system services", "Identify dangerous setuid binaries and weak Windows service permissions"],
         ["Why does a setuid root binary represent a major privilege escalation risk if not securely written?"],
         ["Running production services under administrative or root accounts without service isolation"]),
        ("cryptography_symmetric_asymmetric", "Applied Cryptography: Ciphers, Hashes & PKI", "Symmetric (AES), Asymmetric (RSA, ECC), hashing (SHA-256, bcrypt), digital certificates, PKI", "Foundations", "foundation", "essential", "intermediate", 30, ["cyber_foundations_networking"],
         ["Select appropriate cryptographic algorithms for data-at-rest and data-in-transit", "Explain the Public Key Infrastructure (PKI) certificate validation chain"],
         ["Why must password hashing algorithms incorporate salt and computational work factors?"],
         ["Attempting to invent custom cryptographic algorithms instead of using proven industry standards"]),
        ("reconnaissance_nmap_osint", "Reconnaissance, Port Scanning & OSINT", "Nmap scanning techniques, service versioning, NSE scripts, OSINT methodologies, Shodan", "Core", "intermediate", "essential", "intermediate", 30, ["cyber_foundations_networking"],
         ["Conduct stealthy network service discovery and banner grabbing using Nmap", "Identify exposed enterprise assets and leaked credentials using open-source intelligence"],
         ["What is the difference between a TCP SYN (half-open) scan and a full TCP connect scan in Nmap?"],
         ["Scanning third-party networks without explicit legal authorization and written rules of engagement"]),
        ("web_vulnerabilities_owasp_deep", "Web Application Attacks: OWASP Deep Dive", "SQLi, XSS, CSRF, SSRF, Command Injection, Insecure Deserialization, XXE", "Core", "intermediate", "essential", "intermediate", 35, ["reconnaissance_nmap_osint"],
         ["Exploit and remediate Server-Side Request Forgery (SSRF) and SQL injection flaws", "Execute blind SQL injection using time-based and boolean-based payloads"],
         ["How does an attacker pivot an SSRF vulnerability into cloud metadata credential theft?"],
         ["Relying on client-side JavaScript input filtering to prevent web application attacks"]),
        ("authentication_identity_attacks", "Authentication, Passwords & Identity Attacks", "Credential stuffing, brute-forcing with Hydra, password spraying, MFA bypass methods", "Core", "intermediate", "essential", "intermediate", 30, ["web_vulnerabilities_owasp_deep"],
         ["Test authentication endpoints against credential stuffing and brute-force attacks", "Analyze the security trade-offs of SMS vs TOTP vs FIDO2 WebAuthn authentication"],
         ["Why is FIDO2 WebAuthn resistant to phishing attacks while TOTP authenticator apps are not?"],
         ["Assuming account lockout policies prevent brute-force attacks without considering password spraying"]),
        ("network_defense_firewalls_ids", "Network Defense: Next-Gen Firewalls & IDS/IPS", "Stateful inspection, Snort / Suricata rule authoring, signature vs anomaly detection", "Core", "intermediate", "essential", "intermediate", 30, ["cyber_foundations_networking"],
         ["Author custom Suricata/Snort detection rules to identify malicious payload patterns", "Configure stateful packet filtering and demilitarized zones (DMZ)"],
         ["What is the operational difference between an Intrusion Detection System (IDS) and an IPS?"],
         ["Relying exclusively on signature detection for zero-day and polymorphic attack vectors"]),
        ("endpoint_detection_edr", "Endpoint Detection, Response (EDR) & Sysmon", "EDR agents, Windows Sysmon logging, Process creation (Event 1), LOLBins, parent-child process analysis", "Applied", "intermediate", "essential", "intermediate", 35, ["os_internals_linux_windows"],
         ["Configure Windows Sysmon to log critical process creation and network connection events", "Identify Living-off-the-Land Binaries (LOLBins) used for stealthy execution"],
         ["How do security analysts use parent-child process relationships (e.g. Word spawning powershell.exe) to detect attacks?"],
         ["Disabling endpoint monitoring because antivirus is already installed"]),
        ("siem_soc_operations", "Security Operations & SIEM Log Analysis", "Splunk, ELK, log parsing, correlation rules, alert triage, false positive reduction", "Applied", "intermediate", "essential", "intermediate", 30, ["endpoint_detection_edr"],
         ["Build correlation searches in Splunk/ELK to detect multi-stage cyber attacks", "Execute structured Tier-1/Tier-2 SOC alert triage and document incident tickets"],
         ["Why is log normalization and correlation critical when analyzing telemetry from 50 disparate tools?"],
         ["Setting up un-tuned SIEM alerts that flood analysts with thousands of false positives daily"]),
        ("privilege_escalation_techniques", "Privilege Escalation: Linux & Windows", "LinPEAS, WinPEAS, kernel exploits, SUID abuse, token impersonation, potato attacks", "Applied", "intermediate", "recommended", "advanced", 35, ["os_internals_linux_windows"],
         ["Identify and exploit misconfigured sudo permissions and vulnerable SUID binaries on Linux", "Execute Windows privilege escalation using unquoted service paths and token manipulation"],
         ["Explain how an unquoted Windows service path with spaces can allow an attacker to gain SYSTEM privileges."],
         ["Assuming low-privilege service account compromise cannot be escalated to full domain control"]),
        ("active_directory_security", "Active Directory Attacks & Defense", "Kerberos authentication, Kerberoasting, AS-REP roasting, BloodHound, Pass-the-Hash", "Applied", "advanced", "essential", "advanced", 35, ["privilege_escalation_techniques"],
         ["Map Active Directory attack paths and Domain Admin escalation routes using BloodHound", "Execute and defend against Kerberoasting attacks targeting service accounts"],
         ["Explain how Kerberoasting extracts service account password hashes without touching target servers."],
         ["Using short, simple passwords for Active Directory service accounts with Service Principal Names"]),
        ("malware_analysis_fundamentals", "Malware Analysis Fundamentals & Sandboxing", "Static analysis with Strings/PEStudio, dynamic analysis in sandboxes, disassembly basics", "Advanced", "advanced", "recommended", "advanced", 35, ["os_internals_linux_windows"],
         ["Extract indicator of compromise (IOC) strings and imported APIs from suspicious binaries", "Execute behavioral malware analysis in isolated sandboxes while monitoring network beacons"],
         ["What is the difference between static malware analysis and dynamic behavioral analysis?"],
         ["Detonating suspicious files on production or corporate workstations instead of isolated labs"]),
        ("threat_hunting_mitre_attack", "Threat Hunting & MITRE ATT&CK Framework", "MITRE ATT&CK matrix, cyber kill chain, hypothesis-driven threat hunting, threat intelligence", "Advanced", "advanced", "recommended", "advanced", 30, ["siem_soc_operations"],
         ["Map observed adversary tactics and techniques directly to the MITRE ATT&CK framework", "Execute hypothesis-driven threat hunts across enterprise telemetry to uncover stealthy persistence"],
         ["Why is hypothesis-driven threat hunting necessary when automated alert rules detect zero anomalies?"],
         ["Focusing only on indicators of compromise (hashes/IPs) instead of adversary TTPs (tactics, techniques, procedures)"]),
        ("cloud_security_aws_azure", "Cloud Security Architecture & Identity Attacks", "AWS IAM policies, metadata service (IMDSv2), Azure AD, cloud privilege escalation", "Advanced", "advanced", "essential", "advanced", 35, ["siem_soc_operations"],
         ["Enforce IMDSv2 across cloud workloads to prevent SSRF cloud credential theft", "Audit cloud tenant permissions for external guest access and excessive wildcard permissions"],
         ["How does IMDSv2 mitigate SSRF attacks that exploit AWS instance metadata endpoints?"],
         ["Allowing IMDSv1 on cloud instances where web application services are deployed"]),
        ("incident_response_containment", "Digital Forensics & Incident Response (DFIR)", "Live response, volatility memory analysis, disk imaging, evidence chain of custody", "Production", "advanced", "essential", "advanced", 35, ["active_directory_security"],
         ["Capture volatile system RAM before shutting down compromised endpoints", "Maintain strict legal chain of custody for digital evidence during forensic investigations"],
         ["Why must volatile system memory be dumped before pulling the power cord on a compromised server?"],
         ["Modifying or browsing files directly on an original compromised forensic evidence disk"]),
        ("penetration_testing_reporting", "Penetration Testing Methodologies & Reporting", "Scope definition, rules of engagement, vulnerability exploitation, executive reporting", "Production", "advanced", "essential", "advanced", 30, ["web_vulnerabilities_owasp_deep"],
         ["Execute structured penetration testing adhering to PTES and OWASP testing standards", "Author clear executive summaries and actionable technical remediation reports for clients"],
         ["Why is an actionable remediation section more valuable to an executive than a list of exploits?"],
         ["Delivering automated vulnerability scanner output as a finalized penetration testing report"]),
        ("security_governance_risk", "Security Governance, Risk & Compliance (GRC)", "NIST Cybersecurity Framework (CSF), risk matrices, vulnerability risk assessments, policies", "Production", "advanced", "recommended", "intermediate", 25, ["penetration_testing_reporting"],
         ["Assess organizational cybersecurity posture using the NIST CSF framework", "Calculate risk impact and likelihood using structured risk assessment matrices"],
         ["What are the five core functions of the NIST Cybersecurity Framework (Identify, Protect, Detect, Respond, Recover)?"],
         ["Viewing security compliance checklists as equivalent to operational cybersecurity resilience"]),
        ("security_automation_soar", "Security Orchestration, Automation & Response (SOAR)", "SOAR playbooks, automated IP blocking, webhook integrations, automated incident triage", "Production", "advanced", "recommended", "advanced", 30, ["incident_response_containment"],
         ["Design automated SOAR playbooks that ingest alerts and quarantine infected endpoints instantly", "Integrate threat intelligence feeds into automated SIEM enrichment workflows"],
         ["How does SOAR automation reduce mean time to respond (MTTR) from hours to seconds?"],
         ["Automating destructive isolation actions without human-in-the-loop approval for critical domain controllers"])
    ]

    # 4. NETWORK ENGINEER (18 nodes)
    net_nodes = [
        ("osi_tcpip_models", "Networking Models: OSI 7-Layer & TCP/IP Architecture", "Physical, data link, network, transport, session, presentation, application layers", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Map real-world network protocols to their respective OSI layers", "Analyze packet encapsulation and decapsulation across network hops"],
         ["Explain how data encapsulation adds headers and footers as data moves down the OSI stack."],
         ["Confusing Layer 2 MAC address frame forwarding with Layer 3 IP packet routing"]),
        ("ip_addressing_subnetting", "IPv4 / IPv6 Addressing, Subnetting & CIDR", "IPv4 classes, CIDR notation, subnet masks, network vs broadcast addresses, IPv6 basics", "Foundations", "foundation", "essential", "beginner", 30, ["osi_tcpip_models"],
         ["Calculate usable host ranges and broadcast addresses from CIDR blocks (/24, /27)", "Design efficient IP addressing schemes that minimize address waste"],
         ["Why does a /28 subnet provide exactly 14 usable host IP addresses?"],
         ["Assigning the network address or broadcast address directly to a host interface"]),
        ("ethernet_switching_vlans", "Ethernet Switching, VLANs & Trunking", "MAC address learning, collision domains, broadcast domains, 802.1Q VLAN trunking", "Foundations", "foundation", "essential", "intermediate", 30, ["ip_addressing_subnetting"],
         ["Segment corporate network traffic using 802.1Q tagged VLANs", "Configure trunk and access ports on managed enterprise switches"],
         ["How do VLANs isolate broadcast domains within the same physical switch?"],
         ["Allowing native VLAN mismatch across trunk links, causing security leaks"]),
        ("spanning_tree_protocol", "Spanning Tree Protocol (STP & RSTP)", "Switching loops, broadcast storms, root bridge election, port states, Rapid STP (802.1w)", "Core", "intermediate", "essential", "intermediate", 30, ["ethernet_switching_vlans"],
         ["Prevent switching loops and broadcast storms in redundant switch topologies", "Optimize root bridge election and configure RSTP portfast for edge hosts"],
         ["Explain how a switching loop causes catastrophic broadcast storms in under 1 second."],
         ["Connecting redundant physical switch links without enabling STP"]),
        ("routing_static_dynamic", "IP Routing: Static Routing & Subnet Forwarding", "Default gateways, routing tables, longest prefix match, administrative distance", "Core", "intermediate", "essential", "beginner", 25, ["ip_addressing_subnetting"],
         ["Configure static routes and default routes (0.0.0.0/0) on enterprise routers", "Diagnose routing black holes using traceroute and route table inspection"],
         ["How does a router determine the next-hop using the longest prefix match rule?"],
         ["Assuming routers forward packets without verifying a valid return route path"]),
        ("ospf_dynamic_routing", "Interior Dynamic Routing: OSPF Architecture", "Link-state routing, Dijkstra shortest path algorithm, OSPF areas, LSA types, DR/BDR", "Core", "intermediate", "essential", "intermediate", 35, ["routing_static_dynamic"],
         ["Deploy single-area and multi-area OSPF routing across enterprise networks", "Configure OSPF hello timers, router IDs, and DR/BDR elections"],
         ["Why does OSPF use link-state advertisements (LSAs) rather than distance-vector metrics?"],
         ["Failing to connect non-backbone OSPF areas to Area 0"]),
        ("bgp_internet_routing", "Exterior Gateway Protocol: BGP & Autonomous Systems", "Autonomous Systems (AS), eBGP vs iBGP, path vector attributes (AS_PATH, Local Pref, MED)", "Core", "intermediate", "essential", "advanced", 35, ["ospf_dynamic_routing"],
         ["Establish eBGP peering sessions and advertise network prefixes to upstream ISPs", "Control outbound traffic flows using BGP Local Preference attributes"],
         ["Explain how BGP prevents routing loops between Autonomous Systems using the AS_PATH attribute."],
         ["Accidentally becoming an open transit AS by leaking private routing tables to public peers"]),
        ("dhcp_dns_core_services", "Core Network Services: DHCP & DNS Infrastructure", "DHCP DORA process, DHCP relay agents, DNS recursive vs iterative queries, authoritative servers", "Core", "intermediate", "essential", "intermediate", 25, ["ip_addressing_subnetting"],
         ["Configure high-availability DHCP scopes and IP helper/relay addresses", "Deploy and troubleshoot enterprise DNS name resolution infrastructure"],
         ["Explain the four-step DORA process (Discover, Offer, Request, Acknowledge) in DHCP."],
         ["Forgetting to configure DHCP relay agents when DHCP servers reside in a different VLAN"]),
        ("nat_pat_address_translation", "Network Address Translation (NAT) & Port Forwarding", "Static NAT, Dynamic NAT, Port Address Translation (PAT / Overload), NAT traversal", "Applied", "intermediate", "essential", "intermediate", 25, ["routing_static_dynamic"],
         ["Configure PAT (NAT overload) allowing thousands of private hosts to share a public IP", "Set up static NAT port forwarding for public-facing servers"],
         ["Why was Port Address Translation (PAT) essential to prevent IPv4 address exhaustion?"],
         ["Assuming NAT provides complete security without explicit stateful firewall rules"]),
        ("network_security_acls_firewalls", "Network Access Control Lists (ACLs) & Firewalls", "Standard vs extended ACLs, stateful firewall inspection, zone-based policy firewalls", "Applied", "intermediate", "essential", "intermediate", 30, ["nat_pat_address_translation"],
         ["Author restrictive extended ACLs filtering by source/dest IP and TCP/UDP ports", "Deploy stateful firewall inspection rules separating untrusted from trusted zones"],
         ["Why should standard ACLs be placed near the destination while extended ACLs go near the source?"],
         ["Placing a permit-all rule before specific deny rules in an ordered ACL"]),
        ("vpn_ipsec_wireguard", "Site-to-Site & Remote Access VPNs (IPsec / WireGuard)", "IPsec Phase 1 (IKE) and Phase 2, ESP, Tunnel vs Transport mode, modern WireGuard", "Applied", "intermediate", "essential", "intermediate", 35, ["network_security_acls_firewalls"],
         ["Establish secure IPsec site-to-site VPN tunnels connecting branch offices to cloud VPCs", "Configure cryptographic transform sets and pre-shared key / certificate authentication"],
         ["What is the difference between IPsec Tunnel mode (new IP header) and Transport mode?"],
         ["Mismatched IKE Phase 1 lifetime or encryption proposals causing tunnel negotiation failures"]),
        ("wireless_networking_wifi", "Enterprise Wireless Networking (Wi-Fi)", "802.11 standards (Wi-Fi 6/6E/7), 2.4GHz vs 5GHz, WPA3 enterprise, Roaming, SSIDs", "Applied", "intermediate", "recommended", "intermediate", 25, ["ethernet_switching_vlans"],
         ["Design enterprise Wi-Fi coverage avoiding co-channel interference", "Implement WPA3 Enterprise authentication with RADIUS and 802.1X"],
         ["Why is channel overlap in the 2.4GHz band (channels 1, 6, 11) a primary cause of Wi-Fi performance drops?"],
         ["Deploying access points with maximum transmit power, causing sticky client roaming issues"]),
        ("snmp_netflow_telemetry", "Network Monitoring: SNMP, NetFlow & Telemetry", "SNMPv3 polling, MIBs, OIDs, NetFlow / sFlow traffic analysis, bandwidth utilization", "Advanced", "advanced", "essential", "intermediate", 30, ["dhcp_dns_core_services"],
         ["Monitor interface link saturation and error discards using SNMPv3", "Analyze top talkers and protocol distribution across WAN links using NetFlow"],
         ["Why should network administrators use SNMPv3 instead of legacy SNMPv1/v2c?"],
         ["Using default 'public' community strings on enterprise network equipment"]),
        ("wireshark_packet_troubleshooting", "Deep Packet Analysis & Troubleshooting with Wireshark", "Packet dissection, TCP windowing, retransmissions, zero window, filtering syntax", "Advanced", "advanced", "essential", "advanced", 35, ["osi_tcpip_models"],
         ["Diagnose application latency bottlenecks by identifying TCP zero window and retransmissions", "Filter and isolate malicious traffic patterns during network outages"],
         ["How do TCP duplicate ACKs and retransmissions indicate packet loss on an intermediate link?"],
         ["Assuming high ping latency always indicates network failure without checking host CPU saturation"]),
        ("quality_of_service_qos", "Quality of Service (QoS) & Traffic Shaping", "Classification & marking (DSCP, CoS), queuing (WFQ, CBWFQ), policing vs shaping, VoIP prioritization", "Advanced", "advanced", "recommended", "advanced", 30, ["routing_static_dynamic"],
         ["Prioritize real-time voice and video packets (VoIP) using Expedited Forwarding (EF)", "Configure traffic shaping to prevent bursty traffic from exceeding ISP committed rates"],
         ["What is the difference between traffic policing (drops excess) and traffic shaping (buffers excess)?"],
         ["Configuring QoS markings that get stripped at the ISP WAN boundary"]),
        ("network_automation_python", "Network Automation with Python & Netmiko", "SSH automation with Netmiko/Paramiko, parsing CLI output with TextFSM, NAPALM, Jinja2 templating", "Production", "advanced", "essential", "intermediate", 35, ["routing_static_dynamic"],
         ["Automate configuration backups and bulk VLAN changes across 50 switches with Python", "Generate standardized device configurations dynamically using Jinja2 templates"],
         ["Why is automated configuration generation using templates superior to manual CLI copy-pasting?"],
         ["Deploying automated configuration scripts across all production switches simultaneously without testing"]),
        ("infrastructure_as_code_ansible_net", "Infrastructure as Code for Networks with Ansible", "Ansible network modules, playbooks, inventory variables, idempotency in networking", "Production", "advanced", "recommended", "advanced", 30, ["network_automation_python"],
         ["Execute idempotent configuration management on Cisco/Juniper devices with Ansible", "Maintain version-controlled network configuration repositories in Git"],
         ["How does Ansible achieve agentless network automation over SSH?"],
         ["Executing raw CLI command tasks instead of using declarative Ansible network modules"]),
        ("cloud_networking_hybrid_connectivity", "Cloud Networking & Hybrid Connectivity", "AWS VPC, transit gateways, direct connect / express route, peering, cloud firewalls", "Production", "advanced", "essential", "advanced", 35, ["vpn_ipsec_wireguard"],
         ["Design multi-region cloud VPC hub-and-spoke topologies with AWS Transit Gateway", "Configure dedicated hybrid interconnects (AWS Direct Connect / Azure ExpressRoute)"],
         ["Why is a Transit Gateway preferred over complex full-mesh VPC peering in large enterprise clouds?"],
         ["Overlapping CIDR blocks across on-premises and cloud VPC subnets, preventing IP routing"])
    ]

    # 5. POSTGRESQL DEVELOPER (18 nodes)
    pg_nodes = [
        ("pg_architecture_processes", "PostgreSQL Architecture & Memory Model", "Postmaster, client backends, shared memory (shared_buffers, wal_buffers), work_mem, maintenance_work_mem", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Explain the role of shared_buffers and OS page cache in PostgreSQL read operations", "Configure work_mem appropriately for complex sorting and hash join queries"],
         ["Why does setting work_mem too high risk out-of-memory (OOM) crashes on high-connection servers?"],
         ["Setting shared_buffers to 90% of system RAM, starving the OS page cache"]),
        ("sql_ddl_data_types", "PostgreSQL Advanced Data Types & Schema DDL", "Numeric, text, UUID, TIMESTAMP WITH TIME ZONE, JSONB, arrays, custom domain constraints", "Foundations", "foundation", "essential", "beginner", 25, ["pg_architecture_processes"],
         ["Choose optimal data types for performance (UUIDv7 vs serial, TIMESTAMPTZ vs TIMESTAMP)", "Enforce database-level data integrity using CHECK and EXCLUDE constraints"],
         ["Why should timestamps always be stored as TIMESTAMP WITH TIME ZONE in production databases?"],
         ["Using VARCHAR(255) arbitrarily when PostgreSQL treats TEXT with equal performance"]),
        ("joins_aggregations_grouping", "Complex Joins, Aggregations & Grouping Sets", "Nested loop, hash join, merge join, GROUP BY, ROLLUP, CUBE, GROUPING SETS", "Foundations", "foundation", "essential", "beginner", 30, ["sql_ddl_data_types"],
         ["Write complex analytical queries using GROUPING SETS, ROLLUP, and CUBE", "Predict when the PostgreSQL optimizer chooses Hash Joins vs Nested Loops vs Merge Joins"],
         ["Explain the difference between a Hash Join and a Nested Loop join in PostgreSQL query execution."],
         ["Writing CROSS JOINs unintentionally due to missing join predicate conditions"]),
        ("window_functions_analytical", "Analytical SQL: Window Functions Mastery", "OVER(), PARTITION BY, ORDER BY, ROW_NUMBER(), RANK(), DENSE_RANK(), LAG(), LEAD(), rolling averages", "Core", "intermediate", "essential", "intermediate", 30, ["joins_aggregations_grouping"],
         ["Calculate moving averages, running totals, and period-over-period growth with window functions", "De-duplicate records and assign sequential row numbers within grouped partitions"],
         ["How do window functions calculate aggregates without collapsing rows like GROUP BY does?"],
         ["Attempting to filter window function results in the WHERE clause instead of using a CTE or subquery"]),
        ("common_table_expressions_recursive", "Common Table Expressions (CTEs) & Recursive SQL", "WITH queries, materialized vs inlined CTEs, recursive CTEs for hierarchical tree traversal", "Core", "intermediate", "essential", "intermediate", 30, ["window_functions_analytical"],
         ["Traverse hierarchical organizational charts and graph structures using recursive CTEs", "Structure multi-stage queries cleanly using readability-enhancing WITH clauses"],
         ["How does a recursive CTE evaluate its anchor member and recursive member until termination?"],
         ["Writing recursive CTEs without termination conditions, resulting in infinite query loops"]),
        ("jsonb_unstructured_data", "JSONB Document Modeling & GIN Indexing", "JSON vs JSONB, jsonb operators (->, ->>, @>, ?), GIN indexes, indexing specific JSON paths", "Core", "intermediate", "recommended", "intermediate", 30, ["sql_ddl_data_types"],
         ["Store and query semi-structured JSON documents with high performance using JSONB", "Accelerate JSONB containment (@>) queries using Generalized Inverted Indexes (GIN)"],
         ["Why is JSONB significantly faster to query than plain JSON in PostgreSQL?"],
         ["Overusing JSONB for deeply relational entity models where foreign keys should be used"]),
        ("btree_indexing_internals", "B-Tree Indexing Mechanics & Leftmost Prefix Rule", "B-Tree page structure, root/branch/leaf pages, composite indexes, index-only scans, include columns", "Core", "intermediate", "essential", "intermediate", 30, ["sql_ddl_data_types"],
         ["Design composite B-Tree indexes adhering to the leftmost prefix rule and query selectivity", "Enable high-speed Index-Only Scans by adding non-key columns using the INCLUDE clause"],
         ["Why does an index on (last_name, first_name) speed up searches for last_name but NOT first_name alone?"],
         ["Creating single-column indexes on every table column and expecting composite queries to be fast"]),
        ("query_planning_explain_analyze", "Query Optimization with EXPLAIN (ANALYZE, BUFFERS)", "Cost estimation, actual vs estimated rows, seq scans, index scans, bitmap index scans, buffers", "Core", "intermediate", "essential", "intermediate", 35, ["btree_indexing_internals"],
         ["Diagnose slow queries using EXPLAIN (ANALYZE, BUFFERS) and identify missing index opportunities", "Resolve discrepancies between estimated rows and actual rows by refreshing table statistics"],
         ["Why does a large discrepancy between estimated and actual rows cause the planner to pick suboptimal join strategies?"],
         ["Running EXPLAIN without ANALYZE and assuming estimated costs equal real-world wall-clock latency"]),
        ("specialized_indexes_gin_gist", "Specialized Indexes: GIN, GiST, BRIN & Partial Indexes", "GIN for arrays/text, GiST for geometry/ranges, BRIN for massive append-only timeseries, partial indexes", "Applied", "intermediate", "recommended", "intermediate", 30, ["btree_indexing_internals"],
         ["Index massive billion-row append-only time-series tables efficiently using lightweight BRIN indexes", "Reduce index storage overhead by 90% using conditional partial indexes (WHERE is_active = true)"],
         ["Why are BRIN indexes exceptionally tiny and fast for sorted time-series data compared to B-Trees?"],
         ["Building standard B-Tree indexes on large text documents instead of using full-text GIN indexes"]),
        ("concurrency_mvcc_isolation", "Multi-Version Concurrency Control (MVCC) & Isolation", "Tuple versions (xmin, xmax), vacuuming dead tuples, Read Committed, Repeatable Read, Serializable", "Applied", "intermediate", "essential", "advanced", 35, ["pg_architecture_processes"],
         ["Explain how MVCC allows readers to never block writers and writers to never block readers", "Prevent non-repeatable reads and serialization anomalies using appropriate isolation levels"],
         ["How does PostgreSQL MVCC mark updated rows as deleted tuples rather than overwriting in place?"],
         ["Assuming that UPDATE statements overwrite existing table disk space directly without generating dead tuples"]),
        ("vacuum_autovacuum_tuning", "VACUUM, Autovacuum Architecture & Bloat Prevention", "Dead tuple cleanup, page freezing, transaction ID wraparound, autovacuum worker tuning, pg_stat_activity", "Applied", "intermediate", "essential", "advanced", 35, ["concurrency_mvcc_isolation"],
         ["Tune autovacuum settings (vacuum_scale_factor, cost_limit) to prevent crippling table bloat", "Monitor and mitigate database-wide transaction ID (txid) wraparound emergencies"],
         ["Why does disabling autovacuum inevitably lead to database outage due to transaction ID wraparound?"],
         ["Running manual VACUUM FULL during peak production hours, locking tables exclusively"]),
        ("table_partitioning_declarative", "Declarative Table Partitioning (Range, List, Hash)", "Declarative partitioning, PARTITION BY RANGE, partition pruning, maintenance automation, pg_partman", "Applied", "intermediate", "essential", "intermediate", 30, ["sql_ddl_data_types"],
         ["Partition massive multi-million row event tables by timestamp range (monthly/daily partitions)", "Verify that queries benefit from automated partition pruning during execution"],
         ["How does partition pruning eliminate entire disk partitions from scan plans during query execution?"],
         ["Partitioning small tables with under 100,000 rows, adding query overhead without performance gain"]),
        ("stored_procedures_plpgsql", "Stored Procedures, Functions & Triggers in PL/pgSQL", "CREATE FUNCTION vs PROCEDURE, transactional control inside procedures, BEFORE/AFTER triggers", "Advanced", "advanced", "recommended", "intermediate", 30, ["sql_ddl_data_types"],
         ["Write high-performance procedural business logic using PL/pgSQL functions and triggers", "Audit table mutations automatically by authoring AFTER INSERT OR UPDATE triggers"],
         ["What is the fundamental difference between a PostgreSQL FUNCTION and a PROCEDURE with respect to transactions?"],
         ["Putting complex application domain business logic inside triggers where it becomes invisible and hard to debug"]),
        ("connection_pooling_pgbouncer", "Connection Pooling with PgBouncer", "Session pooling, transaction pooling, connection overhead, max_connections tuning, auth types", "Advanced", "advanced", "essential", "intermediate", 30, ["pg_architecture_processes"],
         ["Deploy PgBouncer in transaction pooling mode to support 10,000+ concurrent client connections", "Configure application connection pool recycling and server connection limits"],
         ["Why does each direct PostgreSQL backend process consume significant RAM and fork overhead?"],
         ["Using prepared statements with PgBouncer transaction pooling without enabling appropriate protocol support"]),
        ("full_text_search_tsvector", "PostgreSQL Full-Text Search (tsvector & tsquery)", "to_tsvector, to_tsquery, English dictionaries, stemming, GIN text indexing, websearch_to_tsquery", "Advanced", "advanced", "recommended", "intermediate", 25, ["specialized_indexes_gin_gist"],
         ["Build fast, typo-tolerant full-text search engines natively within PostgreSQL using tsvector", "Rank search results by relevance using ts_rank and ts_rank_cd"],
         ["How does linguistic stemming in tsvector allow searches for 'run' to match 'running' and 'ran'?"],
         ["Using slow, un-indexed LIKE '%keyword%' wildcards for user text search queries"]),
        ("replication_high_availability", "Physical & Logical Replication (HA Clusters)", "Streaming replication, write-ahead logs (WAL), replication slots, Patroni HA, failover automation", "Production", "advanced", "essential", "advanced", 35, ["pg_architecture_processes"],
         ["Deploy streaming replication with hot standby read replicas across availability zones", "Automate PostgreSQL primary failover and leader election using Patroni and etcd"],
         ["What is the difference between physical streaming replication (byte-for-byte) and logical replication?"],
         ["Creating replication slots without active standbys, causing WAL disk exhaustion on the primary server"]),
        ("backup_pitr_wal_archiving", "Backup, WAL Archiving & Point-In-Time Recovery (PITR)", "pg_dump vs pg_basebackup, WAL archiving to S3, continuous archiving, Point-In-Time Recovery", "Production", "advanced", "essential", "advanced", 35, ["replication_high_availability"],
         ["Configure continuous WAL archiving and restore a production database to an exact second in time", "Execute automated daily physical backups with pgBackRest or WAL-G"],
         ["Why is Point-In-Time Recovery (PITR) capable of recovering data up to the second before an accidental DROP TABLE?"],
         ["Relying exclusively on logical pg_dump backups for multi-terabyte production databases"]),
        ("database_security_rls", "Database Security, Hardening & Row-Level Security (RLS)", "pg_hba.conf, SSL connections, role inheritance, Row-Level Security (RLS) policies, pgcrypto", "Production", "advanced", "essential", "advanced", 30, ["sql_ddl_data_types"],
         ["Isolate multi-tenant data securely using PostgreSQL Row-Level Security (RLS) policies", "Enforce TLS encrypted connections and least-privilege role permissions via pg_hba.conf"],
         ["How does Row-Level Security enforce tenant data isolation directly at the database engine level?"],
         ["Granting the public database application user SUPERUSER permissions"])
    ]

    # 6. SYSTEM DESIGN & CLOUD ARCHITECTURE (18 nodes)
    sys_nodes = [
        ("scalability_foundations", "Scalability Fundamentals: Vertical vs Horizontal Scaling", "Scale-up vs scale-out, stateful vs stateless servers, latency vs throughput, bottlenecks", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Analyze application bottlenecks and choose between vertical and horizontal scaling strategies", "Design completely stateless web application tiers capable of dynamic auto-scaling"],
         ["Why is designing servers to be stateless essential before horizontal auto-scaling can function?"],
         ["Storing user session data in server local memory, preventing horizontal scaling"]),
        ("load_balancing_reverse_proxies", "Load Balancing & Traffic Distribution", "Layer 4 vs Layer 7 load balancing, round-robin, least connections, IP hash, reverse proxies, health checks", "Foundations", "foundation", "essential", "beginner", 25, ["scalability_foundations"],
         ["Distribute incoming traffic across server fleets using Layer 7 load balancers", "Configure active health checks and implement graceful connection draining during server rollouts"],
         ["What is the functional difference between Layer 4 (TCP) and Layer 7 (HTTP) load balancing?"],
         ["Relying on DNS round-robin alone for load balancing without health checks or failover"]),
        ("database_replication_scaling", "Database Scaling: Read Replicas & Connection Pooling", "Primary-replica topology, read/write splitting, replication lag, connection poolers (PgBouncer)", "Foundations", "foundation", "essential", "intermediate", 30, ["scalability_foundations"],
         ["Route read queries to read replicas while directing writes strictly to the primary database", "Handle replication lag anomalies where a user writes data and reads stale replica data immediately"],
         ["How does replication lag cause 'read-your-own-writes' consistency anomalies for users?"],
         ["Sending all read and write queries to the primary database when 95% of traffic is read-only"]),
        ("caching_strategies_redis", "Distributed Caching Strategies: Redis & Memcached", "Cache-Aside, Write-Through, Write-Behind, TTL, cache invalidation, cache stampede (thundering herd)", "Core", "intermediate", "essential", "intermediate", 30, ["database_replication_scaling"],
         ["Implement the Cache-Aside pattern to reduce database query load by 90%", "Mitigate cache stampede (thundering herd) using probabilistic early expiration or mutex locks"],
         ["What are the trade-offs between Cache-Aside and Write-Through caching patterns?"],
         ["Treating distributed caches as persistent authoritative storage without backing databases"]),
        ("cdn_edge_caching", "Content Delivery Networks (CDNs) & Edge Caching", "Edge points of presence (PoP), static vs dynamic asset caching, Cache-Control headers, stale-while-revalidate", "Core", "intermediate", "essential", "intermediate", 25, ["caching_strategies_redis"],
         ["Accelerate global asset delivery and reduce origin load by configuring CDN edge caching", "Implement optimal Cache-Control headers, ETags, and stale-while-revalidate directives"],
         ["How do CDNs reduce network latency for geographically distributed end users?"],
         ["Caching user-specific private data on public CDN edge nodes without Cache-Control: private"]),
        ("database_sharding_partitioning", "Database Sharding & Horizontal Data Partitioning", "Horizontal sharding, shard keys, range vs hash-based sharding, re-sharding challenges, cross-shard joins", "Core", "intermediate", "essential", "advanced", 35, ["database_replication_scaling"],
         ["Select optimal shard keys that distribute data and traffic evenly without hotspots", "Analyze the operational complexity and trade-offs of cross-shard joins and distributed transactions"],
         ["Why does picking a monotonically increasing shard key (like timestamp) cause write hotspots?"],
         ["Sharding databases prematurely before exhausting index, caching, and read-replica scaling options"]),
        ("cap_theorem_pacelc", "Distributed Systems Theory: CAP & PACELC Theorems", "Consistency, Availability, Partition Tolerance, Eventual Consistency, PACELC model", "Core", "intermediate", "essential", "advanced", 30, ["database_sharding_partitioning"],
         ["Evaluate distributed system trade-offs between strong consistency (CP) and high availability (AP)", "Apply the PACELC theorem to analyze latency vs consistency trade-offs when no partition exists"],
         ["Why does the CAP theorem state that in the presence of a network partition, a system must choose between C and A?"],
         ["Assuming a distributed system can achieve 100% strong consistency and 100% availability during network splits"]),
        ("consistent_hashing", "Consistent Hashing & Distributed Ring Topologies", "Hash ring, virtual nodes, rehashing overhead, distributed key distribution (DynamoDB, Cassandra)", "Core", "intermediate", "recommended", "advanced", 30, ["cap_theorem_pacelc"],
         ["Distribute keys across a dynamically scaling cache cluster using consistent hashing rings", "Mitigate hotspot imbalances on the hash ring by implementing virtual nodes (vnodes)"],
         ["Why does traditional modulo hashing (hash(key) % N) fail catastrophically when a cache server is added or removed?"],
         ["Using naive modulo hashing for distributed cache clusters that resize dynamically"]),
        ("asynchronous_messaging_queues", "Message Queues & Asynchronous Processing", "Message queues (RabbitMQ, SQS), point-to-point, task retries, exponential backoff, dead-letter queues", "Applied", "intermediate", "essential", "intermediate", 30, ["scalability_foundations"],
         ["Decouple synchronous HTTP request handling by offloading heavy work to background message queues", "Handle message processing failures gracefully using exponential backoff and dead-letter queues"],
         ["Why is decoupling via message queues critical for protecting backend systems against bursty traffic spikes?"],
         ["Processing long-running multi-second tasks inside the user's synchronous HTTP request thread"]),
        ("event_driven_streaming_kafka", "Event-Driven Architecture & Streaming with Kafka", "Event streams, Apache Kafka, topics, partitions, consumer groups, offset management, event ordering", "Applied", "intermediate", "essential", "advanced", 35, ["asynchronous_messaging_queues"],
         ["Architect scalable event-driven systems using publish/subscribe event streams in Apache Kafka", "Guarantee in-order event processing within specific entities using Kafka partition keys"],
         ["How do Kafka consumer groups enable parallel processing of partition streams without duplicate consumption?"],
         ["Assuming Kafka guarantees global ordering across all partitions instead of per-partition ordering"]),
        ("rate_limiting_throttling", "Distributed Rate Limiting & Throttling Algorithms", "Token bucket, leaky bucket, fixed window, sliding window log, sliding window counter, Redis rate limiters", "Applied", "intermediate", "essential", "intermediate", 30, ["caching_strategies_redis"],
         ["Protect public APIs against abuse and DDoS using Redis sliding window rate limiters", "Compare the memory efficiency and burst tolerance of Token Bucket vs Sliding Window Counter"],
         ["How does the Token Bucket algorithm handle sudden bursts of traffic while enforcing average rates?"],
         ["Implementing naive in-memory rate limiting that fails when applications scale across multiple server instances"]),
        ("distributed_unique_ids", "Distributed Unique ID Generation (Snowflake / UUIDv7)", "UUIDv4 random vs UUIDv7 time-ordered, Twitter Snowflake ID generation, 64-bit integer IDs", "Applied", "intermediate", "recommended", "intermediate", 25, ["database_sharding_partitioning"],
         ["Generate globally unique, time-sortable 64-bit IDs at high concurrency using Snowflake architecture", "Optimize database B-Tree index locality using time-ordered UUIDv7 instead of random UUIDv4"],
         ["Why does inserting random UUIDv4 primary keys cause catastrophic B-Tree index fragmentation at scale?"],
         ["Relying on single centralized database auto-increment IDs in distributed multi-region databases"]),
        ("microservices_api_gateways", "Microservices Architecture & API Gateways", "Service decomposition, API Gateways (Kong, Envoy), routing, authentication offload, service mesh", "Advanced", "advanced", "essential", "advanced", 35, ["load_balancing_reverse_proxies"],
         ["Decompose monolithic architectures into bounded context microservices", "Centralize cross-cutting concerns (authentication, TLS termination, rate limiting) at the API Gateway"],
         ["Why should an API Gateway handle perimeter authentication rather than duplicating auth logic in every microservice?"],
         ["Creating distributed monoliths where every microservice requires synchronous REST calls to 10 others"]),
        ("distributed_transactions_saga", "Distributed Transactions & The Saga Pattern", "Two-Phase Commit (2PC) limitations, Saga pattern (Choreography vs Orchestration), compensating transactions", "Advanced", "advanced", "essential", "advanced", 35, ["event_driven_streaming_kafka"],
         ["Maintain data consistency across distributed microservice databases using the Saga pattern", "Design and execute idempotent compensating transactions when a distributed step fails"],
         ["Why is Two-Phase Commit (2PC) an anti-pattern in modern cloud architectures due to blocking locks?"],
         ["Assuming traditional ACID transactions can span across separate microservice database boundaries"]),
        ("circuit_breakers_resilience", "System Resilience: Circuit Breakers & Bulkheads", "Cascading failures, Circuit Breaker pattern (Closed, Open, Half-Open), bulkheads, timeout budgets", "Advanced", "advanced", "essential", "advanced", 30, ["microservices_api_gateways"],
         ["Prevent cascading system collapse using Circuit Breakers that fail fast during dependency outages", "Isolate critical resource pools using the Bulkhead pattern to prevent resource exhaustion"],
         ["Explain the state transitions of a Circuit Breaker: Closed -> Open -> Half-Open -> Closed."],
         ["Retrying failed dependency requests infinitely with zero delay, amplifying downstream outages (retry storm)"]),
        ("cloud_storage_blobs", "Cloud Object Storage & Media Pipelines", "Block vs file vs object storage, Amazon S3, presigned upload URLs, multipart uploads, lifecycle policies", "Production", "advanced", "recommended", "intermediate", 25, ["caching_strategies_redis"],
         ["Architect scalable file upload systems using secure client-side S3 presigned URLs", "Manage storage costs effectively using automated object lifecycle transitions to cold storage"],
         ["Why is object storage (S3) dramatically more scalable and cost-effective than block storage for media assets?"],
         ["Uploading multi-gigabyte video files directly through application server memory"]),
        ("distributed_tracing_telemetry", "Distributed Tracing & System Observability", "OpenTelemetry, trace IDs, span contexts, distributed trace propagation, latency heatmaps", "Production", "advanced", "essential", "advanced", 35, ["microservices_api_gateways"],
         ["Track end-to-end user request flows across 20+ microservice boundaries using OpenTelemetry trace IDs", "Diagnose distributed tail latency bottlenecks (p99 latency) using distributed spans"],
         ["How do distributed trace contexts propagate across HTTP and gRPC network boundaries using W3C headers?"],
         ["Relying on isolated server log files without correlation IDs when debugging distributed failures"]),
        ("disaster_recovery_multi_region", "Disaster Recovery & Multi-Region Cloud Architecture", "Active-Passive (Pilot Light, Warm Standby), Active-Active multi-region, DNS failover (Route 53)", "Production", "advanced", "essential", "advanced", 35, ["database_replication_scaling"],
         ["Architect multi-region cloud deployment topologies with automated Route 53 health-check failover", "Balance the extreme cost and complexity of Active-Active systems against business RTO/RPO requirements"],
         ["What are the severe distributed data conflict challenges (split-brain) inherent in multi-region Active-Active setups?"],
         ["Assuming multi-region deployments are trivial without solving multi-master database write conflicts"])
    ]

    # 7. SOFTWARE ARCHITECT (18 nodes)
    arch_nodes = [
        ("software_design_principles_solid", "Software Design Principles: SOLID & GRASP", "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Refactor legacy codebases adhering to SOLID principles to maximize maintainability", "Apply the Dependency Inversion Principle to decouple high-level policy from low-level details"],
         ["Explain why violating the Liskov Substitution Principle causes unexpected runtime crashes when subclassing."],
         ["Treating design patterns as rigid dogma to be forced into every trivial class"]),
        ("domain_driven_design_core", "Domain-Driven Design (DDD): Strategic Design", "Ubiquitous Language, Bounded Contexts, Context Mapping, Core Domain vs Generic Subdomains", "Foundations", "foundation", "essential", "intermediate", 30, ["software_design_principles_solid"],
         ["Establish a shared Ubiquitous Language between domain experts and software engineers", "Decompose enterprise systems into clean, decoupled Bounded Contexts using Context Mapping"],
         ["What is a Bounded Context in DDD and why is sharing a single unified data model across an enterprise toxic?"],
         ["Creating an enormous enterprise-wide 'Canonical Data Model' that attempts to model everything"]),
        ("ddd_tactical_patterns", "DDD Tactical Patterns: Aggregates, Entities & Value Objects", "Entities vs Value Objects, Aggregate Roots, invariant enforcement, Domain Events, Repositories", "Foundations", "foundation", "essential", "intermediate", 30, ["domain_driven_design_core"],
         ["Design rich domain models where Aggregate Roots strictly enforce consistency boundaries", "Model immutable Value Objects that encapsulate business validation rules"],
         ["Why must external services only interact with an Aggregate through its Aggregate Root?"],
         ["Creating anemic domain models that are just bags of getters and setters with zero business logic"]),
        ("architectural_styles_monolith_micro", "Architectural Styles: Modular Monolith vs Microservices", "Monolith First, Modular Monoliths, Microservices trade-offs, Conway's Law, distributed tax", "Core", "intermediate", "essential", "intermediate", 30, ["ddd_tactical_patterns"],
         ["Evaluate the high organizational and operational cost (distributed tax) of microservices", "Architect strict in-process boundaries in a Modular Monolith before splitting into services"],
         ["How does Conway's Law dictate that software architecture inevitably reflects team communication structures?"],
         ["Defaulting to microservices for early-stage startups before product-market fit and domain understanding"]),
        ("clean_architecture_hexagonal", "Clean Architecture & Hexagonal (Ports & Adapters)", "Dependency Rule, Entities, Use Cases, Interface Adapters, Frameworks & Drivers, Ports & Adapters", "Core", "intermediate", "essential", "intermediate", 35, ["software_design_principles_solid"],
         ["Structure enterprise applications where business logic has zero dependencies on databases or web frameworks", "Define clear Input and Output Ports with decoupled infrastructure adapters"],
         ["Explain the Clean Architecture Dependency Rule: source code dependencies must point only inward toward higher-level policies."],
         ["Importing database ORM entities directly into domain business logic Use Cases"]),
        ("event_driven_architecture_eda", "Event-Driven Architecture (EDA) & Event Sourcing", "Events vs commands, publish-subscribe, Event Sourcing, append-only event logs, state reconstruction", "Core", "intermediate", "essential", "advanced", 35, ["ddd_tactical_patterns"],
         ["Design decoupled, event-driven distributed systems using domain events", "Implement Event Sourcing where state changes are recorded as an immutable append-only ledger"],
         ["What is the fundamental difference between storing current state vs storing an immutable history of events (Event Sourcing)?"],
         ["Using events as glorified RPC commands, re-introducing tight temporal coupling between services"]),
        ("cqrs_architectural_pattern", "CQRS: Command Query Responsibility Segregation", "Read models vs Write models, eventual consistency, projection workers, denormalized read views", "Core", "intermediate", "recommended", "advanced", 35, ["event_driven_architecture_eda"],
         ["Separate complex write transaction models from high-performance read projections using CQRS", "Build denormalized read-optimized views that update asynchronously via domain events"],
         ["Why does separating the Command model from the Query model unlock massive read-side scalability?"],
         ["Applying full CQRS and Event Sourcing to simple CRUD applications that don't need it"]),
        ("api_strategy_governance", "API Strategy, Protocols & Contract Governance", "REST, GraphQL, gRPC, Protobuf, versioning strategies (URI, header), backward compatibility, OpenAPI", "Core", "intermediate", "essential", "intermediate", 30, ["architectural_styles_monolith_micro"],
         ["Select optimal communication protocols: REST for public APIs, gRPC for low-latency internal microservices", "Enforce strict backward compatibility and semantic API versioning across teams"],
         ["Why is gRPC significantly faster and more bandwidth-efficient than REST/JSON for microservice-to-microservice traffic?"],
         ["Introducing breaking API schema changes without versioning, crashing downstream client applications"]),
        ("enterprise_integration_patterns", "Enterprise Integration Patterns (EIP)", "Content-based router, message translator, scatter-gather, dead-letter channel, idempotent receiver", "Applied", "intermediate", "recommended", "intermediate", 30, ["event_driven_architecture_eda"],
         ["Apply classic Enterprise Integration Patterns to connect disparate legacy and cloud systems", "Implement scatter-gather patterns to aggregate responses from multiple backend systems in parallel"],
         ["How does an Idempotent Receiver pattern protect systems from duplicate message processing?"],
         ["Assuming network delivery is reliable and failing to design for message duplication or network timeouts"]),
        ("data_architecture_polyglot", "Data Architecture: Polyglot Persistence & Data Mesh", "Relational, document, key-value, graph, time-series, vector databases, Data Mesh principles", "Applied", "intermediate", "essential", "intermediate", 30, ["architectural_styles_monolith_micro"],
         ["Select optimal storage engines for specific access patterns (Polyglot Persistence)", "Apply Data Mesh principles treating data as a product owned by cross-functional domain teams"],
         ["Why is forcing all application data into a single database engine an architectural anti-pattern?"],
         ["Building a single centralized monolithic data lake that becomes an unmaintainable bottleneck"]),
        ("security_architecture_threat_modeling", "Security Architecture & Zero Trust Principles", "Identity providers (OAuth2/OIDC), zero trust network access (ZTNA), defense-in-depth, STRIDE", "Applied", "intermediate", "essential", "advanced", 35, ["clean_architecture_hexagonal"],
         ["Architect enterprise authentication and authorization using OAuth 2.0 and OpenID Connect", "Enforce defense-in-depth where every internal network layer authenticates and encrypts requests"],
         ["Why does Zero Trust require mutual TLS and identity verification even for traffic inside private networks?"],
         ["Assuming the internal corporate or cloud VPC network is trusted and safe from lateral movement"]),
        ("distributed_systems_resilience_architecture", "Resilience Engineering: Fault Tolerance & Chaos", "Blast radius reduction, graceful degradation, circuit breakers, load shedding, chaos engineering", "Applied", "advanced", "essential", "advanced", 35, ["architectural_styles_monolith_micro"],
         ["Minimize failure blast radius so that an outage in one subsystem does not take down the entire business", "Design systems capable of graceful degradation under catastrophic load (dropping non-critical features)"],
         ["How does load shedding intentionally drop low-priority requests to save a server from total collapse?"],
         ["Designing systems where every single component must be 100% operational for any feature to work"]),
        ("c4_model_architecture_documentation", "Architecture Documentation: The C4 Model & ADRs", "C4 Model (Context, Containers, Components, Code), Architecture Decision Records (ADRs)", "Advanced", "advanced", "essential", "intermediate", 30, ["domain_driven_design_core"],
         ["Communicate complex software architectures clearly using C4 Model hierarchical diagrams", "Document architectural rationale, trade-offs, and decisions using Architecture Decision Records (ADRs)"],
         ["Why are Architecture Decision Records (ADRs) critical for preserving institutional architectural memory?"],
         ["Drawing unstandardized architectural boxes-and-arrows diagrams with undefined boundary semantics"]),
        ("legacy_modernization_strangler", "Legacy Modernization & The Strangler Fig Pattern", "Strangler Fig pattern, anti-corruption layers (ACL), branch by abstraction, database migration", "Advanced", "advanced", "essential", "advanced", 35, ["clean_architecture_hexagonal"],
         ["Incrementally replace legacy monolithic systems using the Strangler Fig pattern without downtime", "Isolate new clean systems from legacy domain pollution using Anti-Corruption Layers (ACL)"],
         ["Why is the Strangler Fig pattern vastly superior to risky high-stakes 'big bang' rewrites?"],
         ["Attempting a complete ground-up rewrite of a massive legacy system from scratch in one release"]),
        ("non_functional_requirements_slas", "Architecting for NFRs: Availability, Latency & SLAs", "NFR engineering, 99.9% vs 99.99% availability math, p99 latency budgeting, scalability metrics", "Advanced", "advanced", "essential", "advanced", 30, ["distributed_systems_resilience_architecture"],
         ["Calculate composite availability and downtime allowances for complex multi-tier dependencies", "Translate ambiguous business goals into concrete, measurable Non-Functional Requirements (NFRs)"],
         ["Explain why four nines (99.99%) availability permits only 4.38 minutes of total downtime per month."],
         ["Accepting requirements like 'the system must be fast and never go down' without concrete metrics"]),
        ("cost_engineering_finops", "Cloud Cost Engineering & FinOps Architecture", "Cloud cost optimization, compute right-sizing, spot instances, egress cost architecture, FinOps", "Production", "advanced", "recommended", "intermediate", 25, ["architectural_styles_monolith_micro"],
         ["Architect systems that minimize cloud data transfer and cross-region egress costs", "Establish FinOps visibility matching cloud infrastructure spend directly to business unit revenue"],
         ["How does cross-availability-zone data transfer quietly generate massive unexpected cloud bills?"],
         ["Over-provisioning cloud compute clusters without autoscaling or utilization analysis"]),
        ("technical_governance_evolution", "Technical Governance & Evolutionary Architecture", "Fitness functions, architectural guardrails, RFC review processes, managing technical debt", "Production", "advanced", "essential", "advanced", 30, ["c4_model_architecture_documentation"],
         ["Automate architectural rule compliance using automated fitness functions in CI", "Lead collaborative Request for Comments (RFC) processes that build engineering consensus"],
         ["What is an architectural fitness function and how does it prevent architectural drift over time?"],
         ["Acting as an ivory-tower architect who dictates designs without consulting implementing engineers"]),
        ("ai_system_architecture_llms", "AI & LLM Architecture Integration in Enterprise", "LLM gateways, prompt orchestration, RAG architectures, model evaluation, AI cost & latency controls", "Production", "advanced", "recommended", "advanced", 35, ["clean_architecture_hexagonal"],
         ["Integrate Large Language Models into enterprise architectures using modular RAG pipelines", "Design AI gateways providing rate limiting, cost monitoring, fallback models, and guardrails"],
         ["Why must enterprise architectures isolate LLM calls behind an abstraction gateway rather than direct API calls?"],
         ["Allowing raw un-sanitized user input directly into LLM prompts without validation guardrails"])
    ]

    return [
        {
            "slug": "devops",
            "title": "DevOps Engineer",
            "domain": "DevOps & Cloud Infrastructure",
            "target_role": "Senior DevOps / Platform Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["devops", "kubernetes", "docker", "terraform", "linux", "ci/cd", "cloud", "aws", "observability"],
            "nodes": [
                make_node("devops", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(devops_nodes)
            ]
        },
        {
            "slug": "devsecops",
            "title": "DevSecOps Engineer",
            "domain": "Security & Infrastructure",
            "target_role": "Senior DevSecOps Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["devsecops", "security", "sast", "dast", "kubernetes", "compliance", "trivy", "supply-chain"],
            "nodes": [
                make_node("devsecops", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(devsecops_nodes)
            ]
        },
        {
            "slug": "cyber-security",
            "title": "Cyber Security Specialist",
            "domain": "Information Security",
            "target_role": "Senior Security Analyst / Penetration Tester",
            "difficulty_baseline": "Beginner",
            "tags": ["cyber-security", "security", "penetration-testing", "siem", "networking", "wireshark", "dfir"],
            "nodes": [
                make_node("cyber-security", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(cyber_nodes)
            ]
        },
        {
            "slug": "network-engineer",
            "title": "Network Engineer",
            "domain": "Networking & Telecommunications",
            "target_role": "Senior Network Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["network", "cisco", "routing", "switching", "bgp", "ospf", "wireshark", "subnets", "vpn"],
            "nodes": [
                make_node("network-engineer", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(net_nodes)
            ]
        },
        {
            "slug": "postgresql",
            "title": "PostgreSQL Developer",
            "domain": "Database Engineering",
            "target_role": "Senior PostgreSQL DBA / Database Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["postgresql", "sql", "database", "indexing", "mvcc", "query-optimization", "pgbouncer", "dba"],
            "nodes": [
                make_node("postgresql", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(pg_nodes)
            ]
        },
        {
            "slug": "system_design_cloud",
            "title": "System Design & Cloud",
            "domain": "Systems Architecture",
            "target_role": "Principal Systems Architect",
            "difficulty_baseline": "Intermediate",
            "tags": ["system-design", "scalability", "cloud", "distributed-systems", "microservices", "caching", "kafka"],
            "nodes": [
                make_node("system_design_cloud", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(sys_nodes)
            ]
        },
        {
            "slug": "software-architect",
            "title": "Software Architect",
            "domain": "Systems Architecture",
            "target_role": "Principal Software Architect",
            "difficulty_baseline": "Intermediate",
            "tags": ["architecture", "domain-driven-design", "microservices", "clean-architecture", "cqrs", "event-driven"],
            "nodes": [
                make_node("software-architect", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(arch_nodes)
            ]
        }
    ]
