"""
Web and Mobile Track Specifications for SkillTwin.
Contains comprehensive 16-24 node curricula for:
- frontend (24 nodes)
- backend (22 nodes)
- fullstack_web (20 nodes)
- android (18 nodes)
- ios (18 nodes)
- flutter_mobile (18 nodes)
- python_backend (18 nodes)
"""

from typing import Dict, Any, List


def make_node(slug: str, key: str, title: str, subtitle: str, phase: str, tier: str, imp: str, diff: str, order: int, mins: int, prereqs: List[str], obj: List[str], feyn: List[str], misc: List[str]) -> Dict[str, Any]:
    return {
        "id": f"cnode_{slug}_{key}",
        "concept_id": f"concept_{slug}_{key}",
        "title": title,
        "subtitle": subtitle,
        "phase": phase,
        "tier": tier,
        "importance": imp,
        "difficulty": diff,
        "order": order,
        "estimated_minutes": mins,
        "prerequisites": [f"concept_{slug}_{p}" for p in prereqs],
        "learning_objectives": obj,
        "feynman_prompts": feyn,
        "key_misconceptions": misc,
        "recommended_resources": [],
    }


def get_web_mobile_specs() -> List[Dict[str, Any]]:
    # 1. FRONTEND (24 nodes)
    fe = [
        ("browser_internals", "Internet & Browser Mechanics", "DNS, HTTP/HTTPS, TCP/IP, Browser Rendering Engine, DOM tree vs Render tree", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Explain the journey of a URL from browser request to pixel rendering", "Analyze critical rendering path and repaint/reflow triggers"],
         ["Explain step-by-step what happens in the browser from typing a URL to seeing pixels."],
         ["Believing the browser downloads and executes all HTML/CSS/JS in a single synchronous pass"]),
        ("semantic_html5", "Semantic HTML5 & Accessibility (a11y)", "Accessible markup, ARIA roles, form validations, SEO metadata", "Foundations", "foundation", "essential", "beginner", 25, ["browser_internals"],
         ["Structure pages with proper semantic landmarks (<main>, <nav>, <article>)", "Implement keyboard navigation and ARIA attributes for screen readers"],
         ["Why is a semantic <button> better for assistive technologies than a <div> with an onClick handler?"],
         ["Treating accessibility as an optional post-launch enhancement rather than core web standard"]),
        ("css_box_model", "CSS Box Model & Display Mechanics", "Content-box vs border-box, margin collapsing, inline vs block vs inline-block", "Foundations", "foundation", "essential", "beginner", 25, ["semantic_html5"],
         ["Calculate exact element dimensions using standard vs border-box models", "Prevent and resolve vertical margin collapse issues"],
         ["Explain why margins collapse vertically between sibling elements but paddings do not."],
         ["Assuming width: 100% includes padding and border without box-sizing: border-box"]),
        ("css_flexbox", "Modern CSS: Flexbox 1D Alignment", "Flex container properties, flex-grow, flex-shrink, flex-basis, alignment axes", "Foundations", "foundation", "essential", "beginner", 25, ["css_box_model"],
         ["Build responsive navigation bars and centered hero sections using Flexbox", "Control item resizing dynamics with flex-grow and flex-shrink"],
         ["How do the main axis and cross axis change when flex-direction switches to column?"],
         ["Confusing justify-content (main axis) with align-items (cross axis)"]),
        ("css_grid", "Modern CSS: 2D CSS Grid Mastery", "Grid template columns/rows, fr units, minmax, auto-fill vs auto-fit, grid areas", "Foundations", "foundation", "essential", "intermediate", 30, ["css_flexbox"],
         ["Create fluid two-dimensional dashboard layouts without media queries", "Design template area layouts with named grid lines"],
         ["Explain the practical difference between auto-fill and auto-fit in a minmax grid."],
         ["Over-nesting Flexbox containers where a single CSS Grid would be simpler"]),
        ("css_responsive_vars", "Responsive Design & CSS Custom Properties", "Fluid clamping clamp(), media queries, container queries, CSS variables", "Foundations", "foundation", "essential", "beginner", 25, ["css_grid"],
         ["Implement dynamic theme switching using CSS custom properties", "Create fluid typography without rigid pixel breakpoints using clamp()"],
         ["Why are container queries more modular for reusable components than viewport media queries?"],
         ["Hardcoding fixed pixel widths that break on small mobile devices"]),
        ("tailwind_css", "Utility-First Styling with Tailwind CSS", "Tailwind JIT, design tokens, responsive prefixes, component extraction", "Foundations", "foundation", "recommended", "intermediate", 25, ["css_responsive_vars"],
         ["Build complex responsive interfaces rapidly using Tailwind utility classes", "Configure design theme tokens and dark mode variants"],
         ["What are the performance and maintainability trade-offs of utility classes vs traditional BEM CSS?"],
         ["Copying long repetitive class strings everywhere instead of extracting reusable UI components"]),
        ("js_types_closures", "JavaScript Types, Scopes & Closures", "Primitives vs reference types, execution context, lexical scope, closures", "Core", "foundation", "essential", "beginner", 30, ["browser_internals"],
         ["Differentiate value copying from reference mutation in objects and arrays", "Leverage lexical closures for data encapsulation and factory functions"],
         ["Explain how a closure retains access to its outer scope variables even after the outer function returns."],
         ["Mutating object references unintentionally leading to side-effect bugs"]),
        ("js_es6_arrays", "Modern ES6+ Syntax & Array Methods", "Map, filter, reduce, destructuring, spread/rest, optional chaining, nullish coalescing", "Core", "foundation", "essential", "beginner", 25, ["js_types_closures"],
         ["Transform complex nested datasets declaratively using map, filter, and reduce", "Use destructuring, optional chaining (?.), and nullish coalescing (??) safely"],
         ["What is the difference between the || operator and the ?? (nullish coalescing) operator?"],
         ["Using Array.prototype.map when no return value is needed instead of forEach or for-of"]),
        ("js_event_loop", "JavaScript Event Loop & Concurrency", "Call stack, Web APIs, task queue (macrotasks), microtask queue, Promise resolution", "Core", "intermediate", "essential", "intermediate", 30, ["js_es6_arrays"],
         ["Predict asynchronous code execution order between setTimeout, Promises, and sync code", "Avoid blocking the single thread with heavy computational loops"],
         ["Why does a resolved Promise callback run before a setTimeout(fn, 0) callback?"],
         ["Thinking JavaScript is multi-threaded because of asynchronous async/await keywords"]),
        ("dom_events", "DOM Manipulation & Event Architecture", "querySelector, DOM mutations, event bubbling, event capturing, event delegation", "Core", "foundation", "essential", "beginner", 25, ["js_types_closures"],
         ["Implement high-performance event delegation on dynamic lists with 1,000+ items", "Manipulate the DOM safely without triggering layout thrashing"],
         ["How does event bubbling allow handling clicks on dynamic child elements from a single parent listener?"],
         ["Attaching individual event listeners to hundreds of list items instead of using event delegation"]),
        ("async_fetch_apis", "Asynchronous JavaScript & Fetch API", "Promises, async/await, Fetch API, HTTP headers, status codes, error handling", "Core", "intermediate", "essential", "intermediate", 30, ["js_event_loop"],
         ["Handle asynchronous HTTP requests with robust try/catch and response.ok checks", "Handle parallel requests efficiently using Promise.all and Promise.allSettled"],
         ["Why does fetch() not reject its promise on HTTP 404 or 500 error status codes?"],
         ["Forgetting to check response.ok when using fetch(), assuming HTTP errors throw automatically"]),
        ("browser_storage", "Browser Storage & Client State Persistence", "localStorage, sessionStorage, Cookies (HttpOnly, SameSite), IndexedDB", "Core", "intermediate", "recommended", "intermediate", 25, ["async_fetch_apis"],
         ["Persist user preferences in localStorage with JSON serialization", "Evaluate security implications of storing auth tokens in localStorage vs HttpOnly cookies"],
         ["Why are sensitive auth tokens stored in localStorage vulnerable to XSS attacks?"],
         ["Storing large structured datasets synchronously in localStorage instead of IndexedDB"]),
        ("git_npm_workflow", "Version Control (Git) & Package Managers", "Git branching, merge vs rebase, npm vs pnpm vs yarn, semantic versioning", "Applied", "foundation", "essential", "beginner", 25, ["js_es6_arrays"],
         ["Manage feature branches and resolve merge conflicts using Git", "Manage dependencies and lockfiles using pnpm/npm with semantic versioning"],
         ["What is the difference between dependencies and devDependencies in package.json?"],
         ["Manually deleting or editing package-lock.json when resolving dependency conflicts"]),
        ("react_architecture", "React Component Architecture & JSX", "Virtual DOM, JSX compilation, unidirectional data flow, pure components, props", "Applied", "intermediate", "essential", "intermediate", 30, ["js_es6_arrays"],
         ["Structure reusable component hierarchies with clean separation of concerns", "Pass data and callbacks cleanly through props without prop drilling"],
         ["Why must React components and render outputs be pure functions with respect to their props?"],
         ["Directly mutating state variables instead of calling setState or dispatch"]),
        ("react_hooks", "React Hooks: useState, useEffect & useRef", "Reactivity, dependency array rules, cleanup functions, DOM references", "Applied", "intermediate", "essential", "intermediate", 30, ["react_architecture"],
         ["Manage local component state with useState and useReducer", "Manage side-effects and cleanup subscriptions correctly with useEffect"],
         ["Why does omitting a reactive variable from the useEffect dependency array lead to stale closure bugs?"],
         ["Using useEffect for data transformation that could be calculated synchronously during render"]),
        ("typescript_react", "TypeScript Fundamentals for UI Engineers", "Type inference, interfaces vs types, generics, typing React props and events", "Applied", "intermediate", "recommended", "intermediate", 30, ["react_hooks"],
         ["Type React components, custom hooks, and synthetic browser events strictly", "Use generics to build type-safe UI components like dropdowns and tables"],
         ["What is the difference between a TypeScript interface and a type alias when building component props?"],
         ["Overusing 'any' type to silence compiler errors instead of writing proper type definitions"]),
        ("client_routing", "Client-Side Routing & SPA Architecture", "HTML5 History API, React Router / TanStack Router, route parameters, protected routes", "Applied", "intermediate", "recommended", "intermediate", 25, ["react_hooks"],
         ["Configure client-side routing with nested layouts and dynamic URL parameters", "Implement route guards and redirect unauthenticated users cleanly"],
         ["How does client-side routing manipulate browser history without reloading the page from the server?"],
         ["Using <a> tags instead of <Link> components, causing full page refreshes"]),
        ("tanstack_query", "Server State & Caching with TanStack Query", "Query keys, staleTime vs gcTime, mutations, optimistic updates, query invalidation", "Advanced", "intermediate", "recommended", "intermediate", 30, ["client_routing"],
         ["Decouple remote server data caching from local client UI state", "Implement optimistic updates with automatic rollback on network failure"],
         ["Why is it an anti-pattern to copy server response data into global Redux/Zustand state stores?"],
         ["Refetching data manually in useEffect instead of using declarative query caching"]),
        ("global_state", "Global Client State: Zustand & Context API", "Context API trade-offs, Zustand stores, selectors, immutable state updates", "Advanced", "intermediate", "recommended", "intermediate", 30, ["tanstack_query"],
         ["Manage cross-cutting client UI state (modals, active themes, cart) with Zustand", "Optimize rendering performance using fine-grained store selectors"],
         ["Why does updating React Context trigger re-renders in all consuming components regardless of selector?"],
         ["Putting high-frequency server data into global client stores"]),
        ("build_bundlers", "Build Tools, Bundlers & Vite", "ES modules in development, Rollup production bundling, tree-shaking, code splitting", "Advanced", "intermediate", "recommended", "intermediate", 25, ["typescript_react"],
         ["Configure code-splitting using dynamic import() for faster initial page loads", "Analyze and reduce production bundle sizes using bundle analyzer tools"],
         ["Explain how tree-shaking removes dead exports from production JavaScript bundles."],
         ["Importing an entire monolithic library when only a single utility function is needed"]),
        ("frontend_testing", "Frontend Testing: Unit & Component Testing", "Vitest, React Testing Library, testing accessible roles, mocking network calls", "Production", "advanced", "recommended", "intermediate", 30, ["react_hooks"],
         ["Write resilient component tests querying elements by accessible roles (getByRole)", "Mock network API responses cleanly with Mock Service Worker (MSW)"],
         ["Why should component tests verify user behavior rather than internal component implementation details?"],
         ["Testing implementation details like internal state variable names that break on refactors"]),
        ("web_vitals", "Web Performance & Core Web Vitals", "LCP, INP, CLS, critical rendering path, image optimization, font display swap", "Production", "advanced", "advanced", "advanced", 35, ["build_bundlers"],
         ["Diagnose and eliminate layout shifts (CLS) caused by unsized media", "Optimize Largest Contentful Paint (LCP) with priority resource hints"],
         ["How do unsized image elements cause Cumulative Layout Shift (CLS)?"],
         ["Loading heavy third-party tracking scripts synchronously in the document <head>"]),
        ("web_security", "Web Security: XSS, CSRF, CSP & CORS", "Cross-Site Scripting (XSS), CSRF tokens, Content Security Policy, CORS preflight", "Production", "advanced", "essential", "advanced", 30, ["browser_storage"],
         ["Sanitize user-generated content to prevent stored and reflected XSS attacks", "Configure strict Content Security Policy (CSP) headers and understand CORS preflight requests"],
         ["What is the difference between CORS (browser-enforced policy) and actual server-side authentication?"],
         ["Assuming CORS prevents malicious attackers from querying backend APIs with tools like curl"]),
    ]

    # 2. BACKEND (22 nodes)
    be = [
        ("protocols_networking", "Internet Protocols & Networking Fundamentals", "TCP/IP, UDP, DNS resolution, HTTP/1.1 vs HTTP/2 vs HTTP/3, TLS/SSL handshake", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Explain how TCP provides reliable, ordered transmission compared to UDP", "Analyze the phases of an HTTPS TLS 1.3 handshake"],
         ["Why does TCP require a 3-way handshake before transmitting data while UDP does not?"],
         ["Assuming HTTPS encrypts IP addresses and domain names during DNS lookup without DoH"]),
        ("runtime_concurrency", "Backend Language Runtime & Concurrency Models", "Process memory model, threads, async event loop vs thread pool, I/O multiplexing", "Foundations", "foundation", "essential", "intermediate", 30, ["protocols_networking"],
         ["Differentiate CPU-bound from I/O-bound bottlenecks in backend services", "Implement non-blocking asynchronous request handlers"],
         ["Explain why a single-threaded event loop can handle 10,000 concurrent I/O connections."],
         ["Running long CPU-intensive algorithms directly on the asynchronous event loop thread"]),
        ("project_structure", "Dependency Management & Project Architecture", "Virtual environments, package managers, configuration management, 12-factor app", "Foundations", "foundation", "essential", "beginner", 25, ["runtime_concurrency"],
         ["Structure clean multi-layered backend projects (controller, service, repository)", "Manage environment variables and secrets following Twelve-Factor principles"],
         ["Why should configuration and secrets never be committed into source code repositories?"],
         ["Hardcoding database connection strings and secrets in application source files"]),
        ("sql_foundations", "Relational Databases & SQL Foundations", "PostgreSQL/MySQL, tables, primary/foreign keys, joins, aggregations, schema design", "Foundations", "foundation", "essential", "beginner", 30, ["project_structure"],
         ["Design normalized relational database schemas with foreign key constraints", "Write efficient SQL queries using INNER, LEFT, and FULL OUTER joins"],
         ["Explain the difference between WHERE (row filter) and HAVING (group filter) in SQL queries."],
         ["Assuming database foreign keys are purely for documentation without checking constraint costs"]),
        ("indexing_optimization", "Database Indexing & Query Execution Plans", "B-Tree indexes, composite indexes, EXPLAIN ANALYZE, table scans vs index scans", "Core", "intermediate", "essential", "intermediate", 30, ["sql_foundations"],
         ["Diagnose slow queries using EXPLAIN ANALYZE and inspect execution plans", "Create composite indexes adhering to the leftmost prefix rule"],
         ["Why does adding an index speed up SELECT queries but slow down INSERT and UPDATE operations?"],
         ["Adding indexes to every single column blindly, degrading write throughput"]),
        ("acid_transactions", "ACID Transactions & Concurrency Isolation Levels", "Atomicity, Consistency, Isolation, Durability, dirty reads, non-repeatable reads, phantom reads", "Core", "intermediate", "essential", "intermediate", 30, ["indexing_optimization"],
         ["Execute multi-step database operations safely inside transactional boundaries", "Select appropriate isolation levels (Read Committed, Repeatable Read, Serializable)"],
         ["How does a database prevent dirty reads in the Read Committed isolation level?"],
         ["Assuming transactions are completely isolated by default without checking the database isolation level"]),
        ("orm_migrations", "ORM Patterns & Database Migration Strategies", "SQLAlchemy/Prisma/Hibernate, active record vs data mapper, schema migrations, N+1 problem", "Core", "intermediate", "recommended", "intermediate", 30, ["acid_transactions"],
         ["Execute safe, versioned database schema migrations with zero-downtime rollback", "Detect and eliminate the N+1 query problem using eager loading / joins"],
         ["Explain how the N+1 query problem occurs and how eager loading solves it."],
         ["Relying on ORM auto-generated queries without inspecting the underlying SQL in production"]),
        ("rest_architecture", "RESTful API Architecture & HTTP Contracts", "HTTP verbs, idempotent operations, status codes, OpenAPI/Swagger, error formats", "Core", "foundation", "essential", "beginner", 25, ["project_structure"],
         ["Design intuitive REST endpoints adhering to standard HTTP semantics", "Format structured error responses following RFC 7807 problem details"],
         ["Why is an HTTP PUT request idempotent while an HTTP POST request is not?"],
         ["Returning HTTP 200 OK with an error message in the JSON response payload"]),
        ("request_validation", "Request Validation & Serialization", "Schema validation, Pydantic/Zod, input sanitization, type coercion, payload validation", "Core", "intermediate", "essential", "intermediate", 25, ["rest_architecture"],
         ["Enforce strict schema validation on all incoming API request payloads", "Sanitize and reject untrusted input before it reaches service business logic"],
         ["Why must API request validation happen at the perimeter before calling business services?"],
         ["Trusting client data types without server-side validation"]),
        ("jwt_auth", "Authentication: JWT, Sessions & Password Hashing", "Stateful sessions vs stateless JWTs, bcrypt/argon2 hashing, refresh token rotation", "Applied", "intermediate", "essential", "intermediate", 30, ["request_validation"],
         ["Hash passwords securely using bcrypt with appropriate work factor / cost", "Implement stateless JWT authentication with short-lived access tokens and refresh tokens"],
         ["Why is it dangerous to hash user passwords with fast algorithms like MD5 or SHA-256?"],
         ["Storing sensitive claims (passwords, PII) inside unencrypted JWT payloads"]),
        ("rbac_authz", "Authorization: RBAC & Policy Enforcement", "Role-Based Access Control (RBAC), Attribute-Based Access Control (ABAC), middleware guards", "Applied", "intermediate", "essential", "intermediate", 25, ["jwt_auth"],
         ["Enforce granular user role and permission checks on API routes", "Protect resources against Broken Object Level Authorization (BOLA/IDOR)"],
         ["Explain the difference between Authentication (who you are) and Authorization (what you can do)."],
         ["Relying only on UI button hiding for access control without backend route authorization"]),
        ("redis_caching", "Caching Strategies with Redis", "In-memory caching, Cache-Aside pattern, Write-Through, TTL expiration, cache invalidation", "Applied", "intermediate", "essential", "intermediate", 30, ["orm_migrations"],
         ["Implement the Cache-Aside pattern with Redis to reduce primary database load", "Set appropriate TTLs and handle cache invalidation on resource updates"],
         ["What is a Cache Stampede (Thundering Herd) and how can it be mitigated?"],
         ["Treating Redis as a permanent database without persistence or eviction configurations"]),
        ("nosql_stores", "NoSQL Databases: Document & Key-Value Stores", "MongoDB, Redis, eventual consistency, denormalization, CAP theorem trade-offs", "Applied", "intermediate", "recommended", "intermediate", 25, ["redis_caching"],
         ["Model denormalized document schemas for read-heavy application workflows", "Evaluate the CAP theorem trade-offs between consistency and partition tolerance"],
         ["When should you choose a relational database over a document-oriented NoSQL database?"],
         ["Using document databases for deeply interconnected multi-table relational data"]),
        ("websockets_realtime", "Real-Time Systems: WebSockets & SSE", "Full-duplex WebSockets, Server-Sent Events (SSE), connection management, heartbeats", "Applied", "intermediate", "recommended", "intermediate", 30, ["rest_architecture"],
         ["Implement low-latency bidirectional communication using WebSockets", "Handle socket reconnections, heartbeats, and client disconnect cleanup"],
         ["When should you use Server-Sent Events (SSE) instead of full-duplex WebSockets?"],
         ["Polling a REST API every 500ms instead of using a WebSocket or SSE connection"]),
        ("async_workers", "Background Tasks & Asynchronous Queues", "Celery, BullMQ, Redis Streams, task serialization, retries, dead-letter queues", "Applied", "intermediate", "essential", "intermediate", 30, ["redis_caching"],
         ["Offload heavy report generation and external API calls to background worker pools", "Configure exponential backoff retries and dead-letter queues for failed jobs"],
         ["Why is a dead-letter queue (DLQ) essential when processing background messages?"],
         ["Executing multi-minute processing tasks synchronously inside HTTP request threads"]),
        ("message_brokers", "Message Brokers & Event-Driven Architecture", "RabbitMQ, Apache Kafka, pub/sub, message persistence, consumer groups, idempotency", "Advanced", "advanced", "recommended", "advanced", 35, ["async_workers"],
         ["Architect decoupled event-driven microservices using publish/subscribe patterns", "Design idempotent event consumers that handle duplicate message deliveries safely"],
         ["Why must event consumers be designed to be idempotent in distributed systems?"],
         ["Assuming message brokers guarantee exactly-once delivery without consumer deduplication"]),
        ("docker_containers", "Containerization with Docker", "Dockerfiles, layers, multi-stage builds, container networking, docker-compose", "Advanced", "intermediate", "essential", "intermediate", 30, ["project_structure"],
         ["Author secure, lightweight multi-stage Dockerfiles for backend services", "Orchestrate multi-container local development environments with Docker Compose"],
         ["Why do multi-stage Docker builds produce significantly smaller and more secure images?"],
         ["Running production Docker containers as the default root user"]),
        ("nginx_proxies", "Web Servers & Reverse Proxies (Nginx)", "Nginx, reverse proxying, SSL termination, load balancing, rate limiting, gzip/brotli", "Advanced", "intermediate", "recommended", "intermediate", 30, ["docker_containers"],
         ["Configure Nginx as a reverse proxy for upstream application servers", "Implement IP-based rate limiting and SSL termination at the edge"],
         ["Why should an application server run behind a reverse proxy like Nginx rather than exposed directly?"],
         ["Exposing backend application ports directly to the public internet"]),
        ("scalability_loadbalancing", "System Scalability & Load Balancing", "Horizontal vs vertical scaling, round-robin, least connections, sticky sessions, statelessness", "Production", "advanced", "essential", "advanced", 35, ["nginx_proxies"],
         ["Design stateless backend architectures capable of horizontal auto-scaling", "Configure load balancing algorithms and handle database connection pooling at scale"],
         ["Why is session state storage inside application server memory an obstacle to horizontal scaling?"],
         ["Storing uploaded user files on local server disks instead of cloud object storage"]),
        ("owasp_backend", "Backend Security & OWASP Top 10", "SQL injection, SSRF, IDOR, command injection, rate limiting, security headers", "Production", "advanced", "essential", "advanced", 30, ["rbac_authz"],
         ["Prevent SQL injection using parameterized queries and ORM binding", "Protect against Server-Side Request Forgery (SSRF) and Insecure Direct Object References (IDOR)"],
         ["How does parameterized SQL query execution guarantee immunity against SQL injection?"],
         ["Concatenating user string input directly into SQL query statements"]),
        ("observability_telemetry", "Observability: Logging, Metrics & Tracing", "Structured JSON logging, OpenTelemetry, Prometheus metrics, distributed trace IDs", "Production", "advanced", "recommended", "advanced", 30, ["scalability_loadbalancing"],
         ["Implement structured logging with correlation IDs across microservice requests", "Instrument golden metrics (latency, traffic, errors, saturation) with Prometheus"],
         ["Why is p99 latency a far more critical metric for SLAs than average response time?"],
         ["Printing unstructured string logs without request IDs or contextual timestamps"]),
        ("cicd_deployment", "CI/CD Pipelines & Production Deployment", "GitHub Actions, automated test pipelines, health checks, zero-downtime rolling deploys", "Production", "advanced", "essential", "intermediate", 30, ["docker_containers"],
         ["Automate unit testing and container image publishing via GitHub Actions", "Configure readiness and liveness health checks for zero-downtime deployments"],
         ["What is the difference between a container liveness probe and a readiness probe?"],
         ["Deploying new code versions to production without automated regression testing"])
    ]

    # 3. FULLSTACK WEB (20 nodes)
    fs = [
        ("web_foundations", "Semantic Web Foundations & Modern CSS", "HTML5 structure, accessibility (a11y), CSS Box Model, Flexbox and Grid layouts", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Structure accessible semantic HTML markup", "Build responsive layouts using CSS Flexbox and Grid"],
         ["Why is semantic HTML critical for assistive technologies and search engine indexing?"],
         ["Using non-semantic <div> elements for all layout and interaction buttons"]),
        ("js_async_core", "Modern JavaScript & Asynchronous Foundations", "ES6+ syntax, closures, event loop, Promises, async/await, Fetch API", "Foundations", "foundation", "essential", "beginner", 30, ["web_foundations"],
         ["Write clean asynchronous code using Promises and async/await", "Handle network requests and responses using the native Fetch API"],
         ["How does the JavaScript event loop handle non-blocking asynchronous I/O?"],
         ["Mutating shared object state unexpectedly across asynchronous functions"]),
        ("fullstack_typescript", "Full-Stack TypeScript Development", "Type system, interfaces, generics, shared types between client and server", "Foundations", "foundation", "recommended", "intermediate", 30, ["js_async_core"],
         ["Define shared data contracts (DTOs) used by both frontend and backend", "Enforce strict type checking to eliminate runtime null/undefined crashes"],
         ["What are the advantages of end-to-end type safety across the frontend and backend?"],
         ["Using 'any' as a quick bypass for TypeScript compiler errors"]),
        ("react_ui_arch", "React Component & State Architecture", "JSX, component decomposition, useState, useEffect, custom hooks", "Core", "intermediate", "essential", "intermediate", 30, ["fullstack_typescript"],
         ["Build modular component hierarchies following unidirectional data flow", "Manage component state and side effects with custom hooks"],
         ["Why must React state updates be treated as immutable?"],
         ["Directly mutating state variables instead of using setter functions"]),
        ("backend_apis", "Backend API Development with Node / Python", "Server architecture, Express/FastAPI, routing, request validation, middleware", "Core", "intermediate", "essential", "intermediate", 30, ["js_async_core"],
         ["Implement structured REST API routes with request validation middleware", "Handle errors gracefully and return standardized HTTP error responses"],
         ["Why should API route controllers delegate business logic to separate service layers?"],
         ["Putting all database queries and business logic inside the route handler"]),
        ("database_sql_design", "Relational Database Design & SQL", "PostgreSQL schema design, primary/foreign keys, joins, normalization, transactions", "Core", "intermediate", "essential", "beginner", 30, ["backend_apis"],
         ["Design normalized relational database schemas with data integrity rules", "Execute complex SQL queries with joins, groupings, and transactions"],
         ["Explain the difference between primary keys, foreign keys, and unique indexes."],
         ["Storing unstructured JSON strings in relational tables where foreign keys should be used"]),
        ("orm_migrations", "ORMs & Schema Migrations", "Prisma / SQLAlchemy, data modeling, versioned migrations, query optimization", "Core", "intermediate", "recommended", "intermediate", 30, ["database_sql_design"],
         ["Define application data models and execute automated schema migrations", "Detect and resolve N+1 query performance issues using eager loading"],
         ["What is the N+1 query problem and how does eager loading prevent it?"],
         ["Running destructive schema migrations directly against production databases without testing"]),
        ("authentication_security", "Full-Stack Authentication & Session Management", "JWT tokens, HTTP-only secure cookies, password hashing with bcrypt, CSRF protection", "Core", "intermediate", "essential", "intermediate", 30, ["orm_migrations"],
         ["Implement secure user authentication using HTTP-only cookies and JWTs", "Hash user passwords securely using bcrypt with work factors"],
         ["Why are HTTP-only cookies safer for storing auth tokens than browser localStorage?"],
         ["Storing sensitive auth tokens in localStorage where they are vulnerable to XSS attacks"]),
        ("tanstack_query_sync", "Client Data Fetching & Caching with TanStack Query", "Server cache synchronization, optimistic updates, query invalidation, error handling", "Applied", "intermediate", "recommended", "intermediate", 30, ["react_ui_arch"],
         ["Synchronize client UI with remote server data using declarative query hooks", "Implement optimistic updates to make UI feel instant during mutations"],
         ["Why is it an anti-pattern to copy server response data into local client state stores?"],
         ["Refetching data manually using useEffect on every render"]),
        ("nextjs_fullstack", "Full-Stack Web Frameworks: Next.js App Router", "Server Components, Client Components, SSR, SSG, Server Actions, route handlers", "Applied", "intermediate", "recommended", "intermediate", 35, ["tanstack_query_sync"],
         ["Leverage React Server Components (RSC) to reduce client JavaScript bundle sizes", "Build fullstack features using Server Actions with automatic revalidation"],
         ["What is the difference between a Server Component and a Client Component in Next.js?"],
         ["Marking every component with 'use client' and losing the benefits of server rendering"]),
        ("redis_caching_fullstack", "Caching & Performance with Redis", "In-memory caching, Cache-Aside pattern, session stores, rate limiting", "Applied", "intermediate", "recommended", "intermediate", 30, ["backend_apis"],
         ["Accelerate slow database queries by implementing Cache-Aside with Redis", "Protect backend API endpoints against abuse using Redis rate limiters"],
         ["Explain how the Cache-Aside pattern handles cache misses and cache updates."],
         ["Caching data infinitely without setting appropriate Time-To-Live (TTL) expirations"]),
        ("docker_fullstack", "Docker Containerization for Full-Stack Apps", "Dockerfiles, multi-stage builds, docker-compose for app + db + redis", "Applied", "intermediate", "essential", "intermediate", 30, ["nextjs_fullstack"],
         ["Containerize frontend and backend applications using multi-stage Dockerfiles", "Orchestrate full local development environments with Docker Compose"],
         ["Why are multi-stage Docker builds recommended for production web applications?"],
         ["Including local node_modules or secret .env files inside Docker images"]),
        ("testing_unit_integration", "Full-Stack Automated Testing", "Vitest/Jest for unit tests, React Testing Library, API integration tests, Playwright E2E", "Production", "advanced", "recommended", "intermediate", 35, ["docker_fullstack"],
         ["Write comprehensive unit tests for business logic and component behavior", "Automate end-to-end user workflows using Playwright cross-browser tests"],
         ["Why does testing user behavior by accessible role create more durable tests than testing implementation details?"],
         ["Testing trivial implementation details like internal state variable names"]),
        ("owasp_web_security", "Full-Stack Web Security: OWASP Top 10", "XSS sanitization, SQL injection prevention, CORS, Content Security Policy, rate limiting", "Production", "advanced", "essential", "advanced", 30, ["authentication_security"],
         ["Sanitize user input and enforce strict Content Security Policy headers", "Prevent injection vulnerabilities and validate cross-origin resource sharing"],
         ["What is Cross-Site Scripting (XSS) and how does output encoding prevent it?"],
         ["Assuming frontend validation is sufficient to prevent malicious database attacks"]),
        ("cicd_cloud_deployment", "CI/CD & Cloud Deployment Pipelines", "GitHub Actions, automated test workflows, Vercel/Render/AWS deployment, zero-downtime deploys", "Production", "advanced", "essential", "intermediate", 30, ["testing_unit_integration"],
         ["Automate build and test pipelines using GitHub Actions workflows", "Deploy fullstack applications to cloud platforms with environment configurations"],
         ["Why is continuous integration (CI) essential for maintaining code quality in teams?"],
         ["Deploying unverified code directly to production without automated test verification"]),
        ("observability_error_tracking", "Observability, Structured Logging & Error Tracking", "Structured JSON logging, Sentry error monitoring, health checks, performance metrics", "Production", "advanced", "recommended", "advanced", 30, ["cicd_cloud_deployment"],
         ["Capture and trace production runtime errors with context using Sentry", "Instrument API response latency metrics and liveness health checks"],
         ["Why are correlation IDs necessary when tracing errors across client and server logs?"],
         ["Using console.log() statements in production code without structured context"]),
        ("graphql_api_contracts", "GraphQL APIs & Schema Federation", "GraphQL schemas, queries, mutations, resolvers, DataLoader for N+1 batching", "Advanced", "advanced", "recommended", "advanced", 30, ["backend_apis"],
         ["Design GraphQL APIs providing precise client data fetching without overfetching", "Prevent N+1 database queries using DataLoader batching"],
         ["How does GraphQL DataLoader batch multiple field resolver queries into a single database SQL query?"],
         ["Permitting arbitrary unbounded nested GraphQL queries in production without query complexity limits"]),
        ("websockets_notifications", "Real-Time Push & WebSocket Notifications", "WebSockets, Socket.io, pub/sub presence channels, reconnection handling", "Advanced", "intermediate", "recommended", "intermediate", 30, ["react_ui_arch"],
         ["Implement live chat and collaborative updates using WebSockets", "Handle connection drops gracefully with reconnection backoff"],
         ["When should you choose WebSockets over Server-Sent Events for client notifications?"],
         ["Holding open un-authenticated WebSocket connections indefinitely"]),
        ("system_design_fundamentals", "System Design & Distributed Data Patterns", "Horizontal scaling, read replicas, database sharding, CAP theorem, CDN edge caching", "Production", "advanced", "essential", "advanced", 35, ["redis_caching_fullstack"],
         ["Design high-availability systems with read-replica database routing", "Evaluate CAP theorem trade-offs for distributed web applications"],
         ["Why is asynchronous read-replica replication subject to replication lag?"],
         ["Attempting to shard databases prematurely before vertical and index optimizations"]),
        ("cloud_storage_cdn", "Cloud Object Storage & CDN Asset Delivery", "AWS S3 / Cloudflare R2, presigned upload URLs, CDN caching, image optimization", "Production", "advanced", "recommended", "intermediate", 25, ["docker_fullstack"],
         ["Upload large user files directly to S3 using secure presigned URLs", "Distribute static assets and optimized images via CDN edge caches"],
         ["Why should large file uploads bypass backend web servers using presigned cloud URLs?"],
         ["Buffering 500MB file uploads in backend server memory before writing to disk"])
    ]

    # 4. ANDROID (18 nodes)
    android_nodes = [
        ("kotlin_basics", "Kotlin Language Fundamentals & Idioms", "Variables, null safety, data classes, extension functions, lambdas, smart casts", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Leverage Kotlin null safety (?., ?:, !!) to eliminate NullPointerExceptions", "Write expressive code using extension functions, lambdas, and data classes"],
         ["How does Kotlin's compile-time null safety guarantee zero NullPointerExceptions at runtime?"],
         ["Overusing the !! force-unwrap operator, reintroducing crash risks"]),
        ("coroutines_flows", "Kotlin Coroutines & Reactive Flows", "Coroutines, dispatchers (Main, IO, Default), viewModelScope, StateFlow vs SharedFlow", "Foundations", "foundation", "essential", "intermediate", 30, ["kotlin_basics"],
         ["Execute background asynchronous operations without blocking the main UI thread", "Stream reactive state updates using StateFlow and SharedFlow"],
         ["Explain the difference between Dispatchers.Main and Dispatchers.IO in Android."],
         ["Launching long-running network or database calls on Dispatchers.Main, freezing the UI"]),
        ("lifecycles_viewmodel", "Android Architecture & Lifecycle Mechanics", "Activity & Fragment lifecycle, ViewModel, SavedStateHandle, process death", "Foundations", "foundation", "essential", "intermediate", 30, ["kotlin_basics"],
         ["Manage screen rotation and configuration changes safely using ViewModel", "Restore UI state across system process death with SavedStateHandle"],
         ["Why does ViewModel survive device configuration changes (rotations) while Activities are destroyed?"],
         ["Storing Activity Context references inside ViewModels, causing permanent memory leaks"]),
        ("jetpack_compose_ui", "Jetpack Compose: Declarative UI Foundations", "Composables, modifier system, Row, Column, Box, LazyColumn for dynamic lists", "Core", "intermediate", "essential", "intermediate", 30, ["lifecycles_viewmodel"],
         ["Build modern declarative Android user interfaces with Jetpack Compose", "Implement performant scrollable lists with LazyColumn and itemsIndexed"],
         ["How does declarative UI in Compose differ from the legacy imperative XML View system?"],
         ["Creating un-memoized heavy objects inside composable functions that re-execute on every recomposition"]),
        ("compose_state", "Compose State & Recomposition Optimization", "remember, mutableStateOf, derivedStateOf, recomposition scopes, state hoisting", "Core", "intermediate", "essential", "intermediate", 30, ["jetpack_compose_ui"],
         ["Manage unidirectional data flow with state hoisting in composables", "Optimize performance by minimizing unnecessary recompositions using derivedStateOf"],
         ["Explain why state hoisting makes composables reusable, testable, and previewable."],
         ["Mutating standard Kotlin variables directly, expecting Compose to detect changes without mutableStateOf"]),
        ("navigation_compose", "Jetpack Navigation & Deep Linking", "Navigation Compose, NavHost, type-safe route arguments, deep link handling", "Core", "intermediate", "recommended", "intermediate", 25, ["compose_state"],
         ["Configure type-safe navigation graphs and handle screen back stacks cleanly", "Handle incoming deep links and route directly into nested application screens"],
         ["How does Navigation Compose maintain separate ViewModel instances per destination back stack entry?"],
         ["Passing complex large objects through navigation arguments instead of passing unique IDs"]),
        ("hilt_di", "Dependency Injection with Hilt", "@HiltAndroidApp, @AndroidEntryPoint, @Inject, @Module, scopes (@Singleton, @ViewModelScoped)", "Core", "intermediate", "essential", "intermediate", 30, ["lifecycles_viewmodel"],
         ["Decouple application components using compile-time dependency injection with Hilt", "Scope dependencies accurately to ViewModels and application lifecycles"],
         ["Why is dependency injection essential for writing unit tests in Android applications?"],
         ["Injecting Activity-scoped dependencies into Singleton services, causing memory leaks"]),
        ("room_sqlite", "Offline Persistence with Room Database", "Entities, DAOs, RoomDatabase, type converters, migrations, reactive Flow queries", "Applied", "intermediate", "essential", "intermediate", 30, ["hilt_di"],
         ["Persist structured application data offline using Room SQLite abstractions", "Observe real-time database changes reactively using Kotlin Flows"],
         ["Why should Room database queries always be executed off the main thread?"],
         ["Accessing Room database instances synchronously on the main thread, causing ANR crashes"]),
        ("retrofit_networking", "Networking: Retrofit, OkHttp & Serialization", "Retrofit interfaces, OkHttp interceptors, Kotlinx.serialization, error handling", "Applied", "intermediate", "essential", "intermediate", 30, ["hilt_di"],
         ["Define clean REST API interfaces and deserialize JSON payloads", "Implement OkHttp interceptors for auth token injection and retry policies"],
         ["How do OkHttp interceptors enable centralized authentication header management?"],
         ["Parsing JSON payloads manually inside UI composables"]),
        ("workmanager_tasks", "Background Work with WorkManager", "PeriodicWorkRequest, OneTimeWorkRequest, constraints (network, battery), chaining tasks", "Applied", "intermediate", "recommended", "intermediate", 25, ["room_sqlite"],
         ["Schedule guaranteed background synchronization tasks that survive device reboots", "Enforce battery and network constraints on background workers"],
         ["Why is WorkManager preferred for deferrable guaranteed work over Foreground Services?"],
         ["Using raw background threads for tasks that must complete even if the app process is terminated"]),
        ("material3_theming", "Material Design 3 & Dynamic Theming", "Material 3 design tokens, dynamic color, typography, shape schemes, dark mode", "Applied", "intermediate", "recommended", "beginner", 25, ["compose_state"],
         ["Implement Material Design 3 dynamic theming adapting to Android 12+ wallpaper colors", "Support seamless light and dark mode switching with high accessibility contrast"],
         ["How does Material Design 3 dynamic color generation work on modern Android devices?"],
         ["Hardcoding static hex color codes directly into composable UI widgets"]),
        ("clean_architecture_mvvm", "Clean Architecture & MVVM Repository Pattern", "Presentation, Domain (Use Cases), Data layers, repository pattern, boundary separation", "Advanced", "advanced", "essential", "intermediate", 35, ["retrofit_networking"],
         ["Structure enterprise Android codebases into Clean Architecture layers", "Encapsulate complex multi-source business logic inside reusable Use Cases / Interactors"],
         ["Why should the Domain layer have zero dependencies on Android framework classes (android.*)?"],
         ["Calling repository database methods directly from UI composable functions"]),
        ("unit_testing_viewmodel", "Android Unit Testing: ViewModels & Use Cases", "JUnit5, Mockk, kotlinx-coroutines-test, TestDispatcher, Turbine for Flows", "Advanced", "advanced", "recommended", "intermediate", 30, ["clean_architecture_mvvm"],
         ["Write fast deterministic unit tests for ViewModels using TestDispatcher", "Test reactive StateFlow emissions deterministically with Turbine"],
         ["Why is StandardTestDispatcher necessary to control virtual time in coroutine unit tests?"],
         ["Running unit tests against real live network endpoints"]),
        ("compose_ui_testing", "Compose UI & End-to-End Testing", "createComposeRule, onNodeWithText, performClick, SemanticsNode assertions", "Advanced", "advanced", "recommended", "intermediate", 30, ["compose_state"],
         ["Write automated UI tests that verify composable hierarchy behavior", "Assert semantics node states and simulate user tap and text input flows"],
         ["How do Compose semantic properties allow testing UI without relying on fragile view IDs?"],
         ["Testing internal implementation state instead of visible user UI elements"]),
        ("performance_leakcanary", "Performance Profiling & Memory Leak Detection", "Android Profiler, LeakCanary, baseline profiles, frame drops (jank), memory allocations", "Production", "advanced", "advanced", "advanced", 35, ["clean_architecture_mvvm"],
         ["Detect and eliminate memory leaks using LeakCanary", "Analyze jank and slow frames using Android Studio CPU & Memory Profilers"],
         ["How do static Activity context references cause out-of-memory (OOM) crashes in Android?"],
         ["Ignoring memory allocation churn inside LazyColumn item composables"]),
        ("security_keystore", "Android Security & Keystore Encryption", "Android Keystore, EncryptedSharedPreferences, biometric prompt, certificate pinning", "Production", "advanced", "essential", "advanced", 30, ["retrofit_networking"],
         ["Store sensitive API tokens securely using hardware-backed Android Keystore", "Implement biometric authentication prompts for sensitive user actions"],
         ["Why is hardware-backed Keystore storage immune to extraction even on rooted devices?"],
         ["Storing unencrypted API keys or auth tokens in standard SharedPreferences"]),
        ("multi_module_architecture", "Multi-Module Android Architecture", "Feature modules, core modules, api/impl separation, build time optimization", "Production", "advanced", "advanced", "advanced", 35, ["clean_architecture_mvvm"],
         ["Decompose monolithic Android apps into decoupled Gradle feature modules", "Improve incremental build times and enforce strict architectural boundaries"],
         ["What are the benefits of decoupling feature modules using an api/impl module pattern?"],
         ["Creating circular dependencies between Gradle feature modules"]),
        ("play_store_publishing", "ProGuard, R8 & Google Play Deployment", "R8 code shrinking, obfuscation rules, App Bundles (.aab), Google Play Console", "Production", "advanced", "essential", "intermediate", 30, ["multi_module_architecture"],
         ["Configure R8 ProGuard rules to shrink and obfuscate production APKs safely", "Generate signed Android App Bundles (.aab) and prepare Play Store releases"],
         ["Why is code obfuscation and resource shrinking critical before shipping production Android apps?"],
         ["Disabling R8 minification to avoid fixing keep rules, shipping bloated and reverse-engineerable apps"])
    ]

    # 5. IOS (18 nodes)
    ios_nodes = [
        ("swift_language_core", "Swift Language Fundamentals & Type System", "Optionals, optional binding, guard, value types (structs) vs reference types (classes)", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Leverage Swift optionals and guard statements to write crash-free code", "Choose appropriately between value types (structs) and reference types (classes)"],
         ["Why does Swift prefer structs (value semantics) over classes (reference semantics) for data models?"],
         ["Force-unwrapping optionals with ! instead of using if-let or guard-let"]),
        ("protocols_generics", "Protocols & Protocol-Oriented Programming", "Protocols, protocol extensions, associated types, generics, type constraints", "Foundations", "foundation", "essential", "intermediate", 30, ["swift_language_core"],
         ["Design flexible architectures using Protocol-Oriented Programming (POP)", "Implement generic algorithms and reusable data structures with type constraints"],
         ["How does Protocol-Oriented Programming differ from traditional single-inheritance OOP?"],
         ["Using heavy class inheritance hierarchies instead of composable protocols"]),
        ("swift_memory_arc", "Memory Management & ARC Mechanics", "Automatic Reference Counting (ARC), strong, weak, and unowned references, retain cycles", "Foundations", "foundation", "essential", "intermediate", 30, ["swift_language_core"],
         ["Identify and eliminate retain cycles between closures and view controllers", "Use [weak self] capture lists safely to prevent memory leaks"],
         ["Explain how a retain cycle occurs when a closure captures self strongly."],
         ["Using [unowned self] when an object can outlive the closure, causing runtime memory crashes"]),
        ("swiftui_declarative_ui", "SwiftUI: Declarative UI & Layout System", "Views, modifiers, VStack, HStack, ZStack, List, LazyVStack, view composition", "Core", "intermediate", "essential", "intermediate", 30, ["swift_language_core"],
         ["Build modern declarative user interfaces using SwiftUI view hierarchies", "Design performant scrollable lists using List and LazyVStack"],
         ["How does SwiftUI declarative view rendering differ from imperative UIKit layout?"],
         ["Building monolithic 500-line body properties instead of decomposing into small reusable subviews"]),
        ("swiftui_state_management", "SwiftUI State & Observation Framework", "@State, @Binding, @Observable, @Environment, unidirectional data flow", "Core", "intermediate", "essential", "intermediate", 30, ["swiftui_declarative_ui"],
         ["Manage local and shared reactive state using the modern @Observable macro", "Pass read-write state bindings down view hierarchies with @Binding"],
         ["What is the difference between @State (local view ownership) and @Binding (two-way reference)?"],
         ["Creating global singletons for view-specific transient state"]),
        ("swiftui_navigation_stack", "Navigation & Deep Linking with NavigationStack", "NavigationStack, navigationDestination, path binding, deep linking", "Core", "intermediate", "recommended", "intermediate", 25, ["swiftui_state_management"],
         ["Implement programmatic navigation using NavigationPath and type-safe destinations", "Handle universal deep links to route directly into specific view destinations"],
         ["How does NavigationPath enable programmatic multi-step pop and push transitions?"],
         ["Relying on deprecated NavigationView instead of modern NavigationStack"]),
        ("swift_concurrency_async", "Modern Swift Concurrency: async/await & Actors", "async/await, Task, TaskGroup, MainActor, thread-safe data isolation with Actors", "Core", "intermediate", "essential", "intermediate", 35, ["protocols_generics"],
         ["Write structured asynchronous code using modern Swift async/await", "Protect mutable state against data races using Actors and MainActor"],
         ["Why does Swift compile-time actor isolation eliminate race conditions without manual mutex locks?"],
         ["Executing heavy background data processing on @MainActor, freezing the UI"]),
        ("networking_urlsession_decodable", "Networking: URLSession & Codable Serialization", "URLSession, Codable, Decodable, async data fetching, error handling", "Applied", "intermediate", "essential", "intermediate", 30, ["swift_concurrency_async"],
         ["Fetch remote API data asynchronously using URLSession and modern async/await", "Deserialize nested JSON responses into strongly-typed Swift models using Decodable"],
         ["How does the Codable protocol automate JSON parsing with compile-time type safety?"],
         ["Parsing raw JSON dictionaries manually without type-safe Codable models"]),
        ("swiftdata_core_data", "Local Persistence: SwiftData & Core Data", "SwiftData @Model, ModelContext, queries with @Query, relationships, migrations", "Applied", "intermediate", "essential", "intermediate", 30, ["swiftui_state_management"],
         ["Persist structured application data offline using the modern SwiftData framework", "Define model relationships and perform efficient predicate queries with @Query"],
         ["How does SwiftData leverage Swift macros to simplify schema definitions compared to legacy Core Data?"],
         ["Mutating ModelContext data on background threads without proper actor isolation"]),
        ("uikit_interoperability", "UIKit Interoperability in SwiftUI", "UIViewRepresentable, UIViewControllerRepresentable, Coordinator pattern", "Applied", "intermediate", "recommended", "intermediate", 25, ["swiftui_declarative_ui"],
         ["Bridge legacy UIKit components into modern SwiftUI view hierarchies", "Manage delegate callbacks and two-way communication using Coordinators"],
         ["Why is the Coordinator pattern necessary when wrapping UIKit views with delegates in SwiftUI?"],
         ["Re-creating expensive UIKit view instances on every SwiftUI body re-evaluation"]),
        ("clean_architecture_ios", "iOS Architecture: MVVM & Clean Architecture", "MVVM pattern, view models, domain interactor use cases, repository abstractions", "Advanced", "advanced", "essential", "intermediate", 35, ["networking_urlsession_decodable"],
         ["Decouple UI views from business logic and data sources using MVVM", "Write testable view models with mocked repository protocols"],
         ["Why should SwiftUI Views contain zero networking or database persistence logic?"],
         ["Making direct network URLSession requests inside SwiftUI view body computed properties"]),
        ("xctest_unit_testing", "Automated Testing: XCTest & View Model Verification", "XCTestCase, expectation, mocking protocols, testing async code, code coverage", "Advanced", "advanced", "recommended", "intermediate", 30, ["clean_architecture_ios"],
         ["Write deterministic unit tests for business logic and ViewModels using XCTest", "Test asynchronous methods safely using expectation(description:) and async testing"],
         ["Why is protocol-based dependency injection essential for mocking dependencies in XCTest?"],
         ["Writing unit tests that depend on real live network responses, leading to flaky CI runs"]),
        ("xctest_ui_testing", "UI Testing & Accessibility Auditing", "XCUIApplication, accessibilityIdentifier, UI assertions, automated user flows", "Advanced", "advanced", "recommended", "intermediate", 30, ["swiftui_declarative_ui"],
         ["Automate user journey testing across screens using XCUIApplication", "Assign accessibilityIdentifiers to enable reliable UI element querying"],
         ["Why are accessibilityIdentifiers superior to localized UI text for automated UI testing?"],
         ["Querying UI test elements by user-visible text that breaks when localizing into other languages"]),
        ("instruments_performance", "Performance Optimization with Instruments", "Xcode Instruments, Time Profiler, Allocations, Leaks, view body churn", "Production", "advanced", "advanced", "advanced", 35, ["swift_memory_arc"],
         ["Identify CPU bottlenecks and main thread hangs using Xcode Time Profiler", "Pinpoint memory retain cycles and allocation leaks using the Leaks instrument"],
         ["How do you identify which SwiftUI views are undergoing unnecessary re-evaluation churn?"],
         ["Assuming that code running smoothly in the Xcode Simulator will run at 60/120fps on physical devices"]),
        ("keychain_ios_security", "iOS Security & Keychain Services", "Keychain Services, LocalAuthentication (Face ID / Touch ID), certificate pinning", "Production", "advanced", "essential", "advanced", 30, ["networking_urlsession_decodable"],
         ["Store sensitive user tokens and private credentials securely in the iOS Keychain", "Protect app access using biometric Face ID / Touch ID authentication"],
         ["Why is UserDefaults insecure for storing auth tokens, and why is Keychain required?"],
         ["Storing auth tokens and API keys in plain text inside UserDefaults"]),
        ("app_extensions_widgets", "App Extensions & WidgetKit", "WidgetKit, TimelineProvider, dynamic widgets, App Groups for shared data", "Production", "advanced", "recommended", "intermediate", 30, ["swiftdata_core_data"],
         ["Build glanceable iOS Home Screen widgets using WidgetKit and TimelineProvider", "Share data between the main app and widget extensions using App Groups"],
         ["How does TimelineProvider schedule widget updates without running continuously in the background?"],
         ["Attempting to execute network calls directly in widget view rendering instead of the timeline provider"]),
        ("spm_modularization", "Swift Package Manager & Modular Architecture", "Swift Package Manager (SPM), multi-package architecture, build time reduction", "Production", "advanced", "recommended", "advanced", 30, ["clean_architecture_ios"],
         ["Decompose monolithic iOS applications into lightweight Swift Packages", "Enforce strict module boundaries and dramatically improve incremental build times"],
         ["What are the modularity benefits of managing local feature modules via Swift Package Manager?"],
         ["Creating circular dependencies between Swift Packages"]),
        ("app_store_testflight", "CI/CD & App Store Distribution", "Fastlane, TestFlight distribution, App Store Connect, signing certificates & provisioning", "Production", "advanced", "essential", "intermediate", 30, ["spm_modularization"],
         ["Automate build signing and TestFlight deployment using Fastlane pipelines", "Configure App Store metadata, screenshots, and privacy nutrition labels"],
         ["Why is automated code signing (Fastlane Match) critical when collaborating on iOS teams?"],
         ["Manually managing development provisioning profiles on individual team laptops"])
    ]

    # 6. FLUTTER MOBILE (18 nodes)
    flutter_nodes = [
        ("dart_type_system_oop", "Dart Language Core & Type System", "Sound null safety, extension methods, records & patterns, mixins, factory constructors", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Leverage Dart sound null safety to prevent runtime null dereference exceptions", "Use records, pattern matching, and mixins for clean data modeling"],
         ["Explain how Dart sound null safety guarantees that non-nullable variables never contain null."],
         ["Overusing the ! operator instead of handling nullable states with if-case patterns"]),
        ("dart_async_streams", "Dart Asynchronous Programming & Streams", "Futures, async/await, Streams, StreamControllers, generators (sync*, async*)", "Foundations", "foundation", "essential", "intermediate", 30, ["dart_type_system_oop"],
         ["Manage asynchronous operations cleanly with Futures and Streams", "Create reactive data pipelines using StreamTransformers and broadcast streams"],
         ["What is the fundamental architectural difference between a Future and a Stream in Dart?"],
         ["Using single-subscription streams when multiple UI listeners are required"]),
        ("widget_tree_render_objects", "Flutter Architectural Mechanics: The Three Trees", "Widget Tree, Element Tree, RenderObject Tree, layout & paint phases", "Foundations", "foundation", "essential", "intermediate", 30, ["dart_type_system_oop"],
         ["Explain the distinct responsibilities of the Widget, Element, and RenderObject trees", "Diagnose and resolve common layout constraints (BoxConstraints) errors"],
         ["Why does Flutter rebuild lightweight Widgets frequently while reusing persistent RenderObjects?"],
         ["Assuming Widget rebuilds are expensive, confusing them with heavy DOM reflows"]),
        ("responsive_layouts_constraints", "Responsive Layouts & Constraint Architecture", "Constraints go down, sizes go up, parent sets position; LayoutBuilder, MediaQuery", "Foundations", "foundation", "essential", "beginner", 25, ["widget_tree_render_objects"],
         ["Build responsive layouts adapting seamlessly to mobile, tablet, and desktop screens", "Debug RenderFlex overflow errors using Flexible, Expanded, and SingleChildScrollView"],
         ["Explain Flutter's golden layout rule: Constraints go down, sizes go up, parent sets position."],
         ["Wrapping unbounded widgets inside unbounded parents, triggering layout crashes"]),
        ("riverpod_state_management", "Reactive State Management with Riverpod 2.x", "NotifierProvider, AsyncNotifier, ref.watch vs ref.read, family, autoDispose", "Core", "intermediate", "essential", "intermediate", 35, ["dart_async_streams"],
         ["Manage global reactive application state cleanly using Riverpod Notifiers", "Handle asynchronous loading, error, and data states declaratively with AsyncValue"],
         ["Why should ref.watch be used inside build() methods while ref.read is reserved for event callbacks?"],
         ["Calling ref.read inside build() methods, causing UI to miss state updates"]),
        ("gorouter_navigation", "Declarative Navigation & Deep Linking with GoRouter", "GoRoute, ShellRoute, redirect guards, path parameters, nested tab navigation", "Core", "intermediate", "essential", "intermediate", 30, ["riverpod_state_management"],
         ["Configure type-safe declarative routing with nested bottom navigation ShellRoutes", "Implement authentication redirect guards to protect private screens"],
         ["How does declarative routing with GoRouter simplify deep linking and web URL synchronization?"],
         ["Navigating imperatively with Navigator.push() without URL state synchronization"]),
        ("dio_networking_interceptors", "Networking with Dio & REST Architecture", "Dio client, interceptors, auth token refresh, retry policies, JSON serialization", "Core", "intermediate", "essential", "intermediate", 30, ["dart_async_streams"],
         ["Implement robust API communication with centralized auth interceptors", "Handle automatic JWT token refresh on HTTP 401 Unauthorized responses"],
         ["How do Dio interceptors enable centralized auth injection and automatic retry policies?"],
         ["Parsing raw JSON maps directly in UI widgets without strongly-typed data models"]),
        ("offline_persistence_sqlite_hive", "Offline Persistence: SQLite, Drift & Hive", "Local database design, Drift type-safe SQL, Hive / SharedPreferences caching", "Applied", "intermediate", "essential", "intermediate", 30, ["riverpod_state_management"],
         ["Persist structured data offline using type-safe SQLite abstractions with Drift", "Cache user settings and authentication tokens with SharedPreferences/Hive"],
         ["Why should relational data with queries be stored in SQLite rather than flat key-value files?"],
         ["Storing large structured datasets in SharedPreferences, causing UI freezes on startup"]),
        ("custom_painter_canvas", "Custom Painting, Canvas & Path Animations", "CustomPainter, Canvas API, Path operations, Paint objects, CustomPaint widget", "Applied", "intermediate", "recommended", "intermediate", 30, ["widget_tree_render_objects"],
         ["Draw custom geometric shapes, graphs, and winding roadmap paths using Canvas", "Optimize repainting by implementing shouldRepaint accurately"],
         ["Why is returning false from shouldRepaint essential when CustomPainter properties haven't changed?"],
         ["Allocating heavy Paint or Path objects inside the paint() method on every frame"]),
        ("animations_implicit_explicit", "Flutter Animations: Implicit vs Explicit", "AnimatedContainer, AnimationController, CurvedAnimation, Hero transitions", "Applied", "intermediate", "recommended", "intermediate", 25, ["widget_tree_render_objects"],
         ["Create fluid UI micro-interactions using implicit animated widgets", "Build orchestrated multi-stage animations with AnimationControllers and TickerProvider"],
         ["What is the difference between an implicit animation widget and an explicit AnimationController?"],
         ["Forgetting to dispose AnimationControllers in State.dispose(), leaking memory"]),
        ("clean_architecture_flutter", "Clean Architecture & Feature-First Project Structure", "Domain (Entities, Use Cases), Data (Repositories, Data Sources), Presentation layers", "Applied", "advanced", "essential", "intermediate", 35, ["dio_networking_interceptors"],
         ["Organize scalable Flutter applications using feature-first domain-driven design", "Decouple domain business logic completely from Flutter UI widgets and external packages"],
         ["Why should domain entities and repository interfaces have zero dependencies on Flutter UI packages?"],
         ["Calling API HTTP clients directly from widget build methods"]),
        ("flutter_automated_testing", "Automated Testing: Unit, Widget & Integration", "flutter_test, testWidgets, WidgetTester, Finder, Mockito / Mocktail, Golden tests", "Advanced", "advanced", "recommended", "intermediate", 30, ["clean_architecture_flutter"],
         ["Write comprehensive unit tests for Riverpod notifiers and domain use cases", "Test widget interactions and verify visual regression using golden tests"],
         ["How does testWidgets simulate user taps, gestures, and frame pump ticks?"],
         ["Running widget tests that perform real HTTP calls without mocking the network layer"]),
        ("platform_channels_native", "Platform Channels: Native Android & iOS Integration", "MethodChannel, EventChannel, native Kotlin and Swift code integration", "Advanced", "advanced", "recommended", "advanced", 35, ["dart_async_streams"],
         ["Communicate bidirectionally between Dart and native Android (Kotlin) / iOS (Swift) code", "Stream continuous native sensor or battery data to Flutter using EventChannels"],
         ["Explain how the binary messenger serializes data across the platform channel boundary."],
         ["Passing massive binary payloads across MethodChannels synchronously, blocking the main UI thread"]),
        ("performance_devtools_profiling", "Performance Profiling & Memory Leak Optimization", "Flutter DevTools, CPU Profiler, Memory Allocations, RepaintBoundary, DevTools timeline", "Production", "advanced", "advanced", "advanced", 35, ["widget_tree_render_objects"],
         ["Profile and fix UI jank and dropped frames (120fps optimization) using Flutter DevTools", "Isolate expensive custom drawings using RepaintBoundary widgets"],
         ["How does RepaintBoundary prevent expensive subtree repainting during animations?"],
         ["Rebuilding the entire screen when only a single text label needs updating"]),
        ("push_notifications_fcm", "Push Notifications with Firebase Cloud Messaging (FCM)", "FCM tokens, background message handlers, local notifications, payload navigation", "Production", "advanced", "recommended", "intermediate", 30, ["gorouter_navigation"],
         ["Configure Firebase Cloud Messaging for foreground and background push alerts", "Handle user notification taps and deep-link directly into relevant feature screens"],
         ["Why must background message handlers be top-level or static entry points (@pragma('vm:entry-point'))?"],
         ["Accessing Flutter UI context inside background notification handlers"]),
        ("security_biometrics_storage", "Mobile Security: Biometrics & Secure Storage", "flutter_secure_storage, Keychain / Keystore encryption, local_auth biometrics", "Production", "advanced", "essential", "advanced", 30, ["offline_persistence_sqlite_hive"],
         ["Encrypt and store sensitive auth tokens using hardware-backed platform keystores", "Enforce biometric Face ID / Fingerprint verification for sensitive app actions"],
         ["Why is flutter_secure_storage safer for access tokens than standard SharedPreferences?"],
         ["Storing plain unencrypted API secrets or tokens in local SQLite databases"]),
        ("ci_cd_fastlane_github", "CI/CD & Mobile Automation with Fastlane", "Fastlane match, App Store Connect API, Google Play publishing, GitHub Actions workflows", "Production", "advanced", "essential", "intermediate", 30, ["flutter_automated_testing"],
         ["Automate building and signing iOS IPAs and Android AABs with Fastlane", "Publish automated TestFlight and Play Store internal track releases on PR merges"],
         ["Why is automated mobile build signing via CI essential for engineering team velocity?"],
         ["Manually building and uploading APKs/IPAs from personal developer machines"]),
        ("app_store_play_store_launch", "App Store & Play Store Launch Readiness", "App icons, splash screens, permissions rationale, store review guidelines, analytics", "Production", "advanced", "essential", "intermediate", 25, ["ci_cd_fastlane_github"],
         ["Configure production app bundle identifiers, splash screens, and adaptive icons", "Comply with Apple App Store and Google Play privacy nutrition and permission guidelines"],
         ["What are the most common rejection reasons during App Store review and how do you avoid them?"],
         ["Requesting sensitive runtime permissions without user context or explanatory UI"])
    ]

    # 7. PYTHON BACKEND (18 nodes)
    py_nodes = [
        ("python_data_model_dunder", "Python Data Model & Dunder Methods", "__init__, __str__, __repr__, __eq__, __hash__, __len__, custom container protocols", "Foundations", "foundation", "essential", "beginner", 25, [],
         ["Leverage Python dunder methods to build intuitive, pythonic classes", "Implement custom collection classes supporting indexing and iteration"],
         ["What is the fundamental difference between __str__ and __repr__ in Python?"],
         ["Defining mutable default arguments in functions (def fn(items=[])), creating shared state bugs"]),
        ("iterators_generators_memory", "Iterators, Generators & Memory Optimization", "Iterables, iterators, yield statements, generator expressions, memory efficiency", "Foundations", "foundation", "essential", "beginner", 25, ["python_data_model_dunder"],
         ["Stream and process massive datasets lazily without exhausting RAM using generators", "Implement custom iterable classes using __iter__ and __next__"],
         ["Why do generator expressions consume significantly less memory than list comprehensions?"],
         ["Converting large database query streams into full lists with list(), exhausting server memory"]),
        ("decorators_context_managers", "Decorators & Context Managers", "Closures, functools.wraps, parameterized decorators, with statement, contextlib", "Foundations", "foundation", "essential", "intermediate", 30, ["iterators_generators_memory"],
         ["Author reusable function and method decorators preserving metadata with functools.wraps", "Manage external resources (sockets, files, DB sessions) safely using context managers"],
         ["Explain how the with statement guarantees cleanup even if an unexpected exception occurs."],
         ["Forgetting to use @functools.wraps on decorators, erasing the original function name and docstring"]),
        ("type_hinting_mypy", "Type Hinting & Static Analysis with Mypy", "Typing module, Union, Optional, Literal, TypedDict, Generics, strict mypy checks", "Foundations", "foundation", "recommended", "beginner", 25, ["python_data_model_dunder"],
         ["Annotate Python codebases with comprehensive type hints to catch bugs before runtime", "Configure strict mypy static type checking in continuous integration pipelines"],
         ["Why does type hinting improve code maintainability and IDE auto-completion in large teams?"],
         ["Assuming Python type hints enforce runtime type validation without runtime libraries like Pydantic"]),
        ("asyncio_concurrency_event_loop", "Asynchronous Programming with Asyncio", "async/await, event loop, Tasks, asyncio.gather, asyncio.run, non-blocking I/O", "Core", "intermediate", "essential", "intermediate", 30, ["decorators_context_managers"],
         ["Write high-concurrency asynchronous code using Python asyncio", "Execute parallel asynchronous tasks cleanly with asyncio.gather and TaskGroups"],
         ["Why does calling time.sleep() inside an async function freeze the entire asyncio event loop?"],
         ["Calling synchronous blocking I/O functions inside async def endpoints instead of running in a thread pool"]),
        ("fastapi_architecture", "FastAPI Framework & Modern Web APIs", "Path operations, query/path parameters, status codes, OpenAPI docs, Starlette core", "Core", "intermediate", "essential", "beginner", 25, ["asyncio_concurrency_event_loop"],
         ["Build production RESTful APIs using FastAPI with automatic OpenAPI Swagger documentation", "Handle HTTP errors and custom exceptions cleanly with HTTPException handlers"],
         ["How does FastAPI achieve high performance comparable to Node.js and Go?"],
         ["Returning internal Python traceback strings to clients on server errors instead of clean JSON"]),
        ("pydantic_v2_validation", "Data Modeling & Validation with Pydantic v2", "BaseModel, Field validation, computed fields, model serializers, Rust core speed", "Core", "intermediate", "essential", "intermediate", 30, ["fastapi_architecture"],
         ["Enforce strict request and response schema validation using Pydantic v2 models", "Write custom field validators and root validators to enforce business constraints"],
         ["How does Pydantic v2's Rust-powered validation engine improve API serialization speed?"],
         ["Using raw Python dictionaries instead of strongly-typed Pydantic schemas across service boundaries"]),
        ("fastapi_dependency_injection", "FastAPI Dependency Injection System", "Depends(), yield dependencies, database session injection, auth guards, sub-dependencies", "Core", "intermediate", "essential", "intermediate", 30, ["fastapi_architecture"],
         ["Decouple services and inject database sessions cleanly using FastAPI Depends()", "Implement reusable authentication and permission guards across API routes"],
         ["Why is dependency injection via Depends() superior to importing global database session objects?"],
         ["Sharing a single database session across multiple concurrent asynchronous requests"]),
        ("sqlalchemy2_async_orm", "SQLAlchemy 2.0 Async ORM & Alembic Migrations", "declarative_base, async_sessionmaker, select(), joins, relationships, Alembic migrations", "Applied", "intermediate", "essential", "intermediate", 35, ["fastapi_dependency_injection"],
         ["Model relational database schemas using modern SQLAlchemy 2.0 declarative syntax", "Execute versioned schema migrations safely using Alembic"],
         ["How does SQLAlchemy 2.0 select() syntax provide type-safe asynchronous database queries?"],
         ["Running database migrations manually with raw SQL files instead of versioned Alembic revisions"]),
        ("postgresql_optimization_python", "PostgreSQL Indexing, Performance & EXPLAIN", "B-Tree indexes, composite indexes, query analysis with EXPLAIN ANALYZE, connection pooling", "Applied", "intermediate", "essential", "intermediate", 30, ["sqlalchemy2_async_orm"],
         ["Analyze slow database queries and optimize indexes using EXPLAIN ANALYZE", "Configure asynchronous connection pooling with asyncpg and pool recycling"],
         ["Why is connection pooling essential for high-concurrency FastAPI applications?"],
         ["Opening and closing a new database connection on every single HTTP request"]),
        ("redis_caching_python", "Caching & In-Memory Data with Redis", "redis-py, async Redis client, Cache-Aside pattern, serialization, key expiration", "Applied", "intermediate", "recommended", "intermediate", 30, ["fastapi_dependency_injection"],
         ["Implement fast in-memory caching using asynchronous Redis clients", "Cache expensive query results with automatic TTL invalidation"],
         ["How does caching reduce database load and improve p99 API response latency?"],
         ["Caching un-serialized Python object references instead of standardized JSON strings"]),
        ("background_tasks_celery", "Background Tasks with Celery & Redis", "Celery app, worker processes, broker & backend, task retries, dead-letter queues", "Applied", "intermediate", "essential", "intermediate", 30, ["redis_caching_python"],
         ["Offload long-running background jobs (emails, report generation) to Celery workers", "Configure automatic task retries with exponential backoff and dead-letter queues"],
         ["Why should heavy computational or external network calls never run inside the HTTP request thread?"],
         ["Passing massive database entity objects into Celery tasks instead of passing object IDs"]),
        ("pytest_automated_testing", "Automated Testing with Pytest & Fixtures", "pytest, pytest-asyncio, fixtures, mocking with unittest.mock / respx, test coverage", "Advanced", "advanced", "essential", "intermediate", 30, ["fastapi_dependency_injection"],
         ["Write deterministic unit and integration tests using pytest and async fixtures", "Mock external HTTP APIs and database sessions cleanly with respx and mock fixtures"],
         ["Why are pytest fixtures superior to traditional xUnit setUp/tearDown methods?"],
         ["Writing tests that run against live third-party external APIs"]),
        ("authentication_jwt_oauth2", "Authentication: JWT, OAuth2 & Password Hashing", "passlib / bcrypt, OAuth2PasswordBearer, JWT tokens, refresh tokens, scopes", "Advanced", "advanced", "essential", "intermediate", 30, ["fastapi_dependency_injection"],
         ["Hash passwords securely using bcrypt with appropriate salt work factor", "Issue and verify asymmetric JWT access tokens with expiration timestamps"],
         ["Why should password hashing algorithms intentionally be computationally expensive?"],
         ["Storing unencrypted plain passwords in database columns"]),
        ("docker_python_production", "Dockerizing Python Applications for Production", "Multi-stage Dockerfiles, non-root user, slim base images, poetry/uv dependency caching", "Production", "advanced", "essential", "intermediate", 30, ["fastapi_architecture"],
         ["Author lean, secure multi-stage Docker images for Python applications", "Optimize Docker build layer caching using modern package managers like uv or poetry"],
         ["Why should production Python containers use lightweight slim/alpine base images?"],
         ["Running production Docker containers as root without a dedicated application user"]),
        ("production_server_uvicorn_gunicorn", "Production Deployment: Uvicorn & Gunicorn", "Uvicorn ASGI server, Gunicorn process manager, worker processes, graceful shutdown", "Production", "advanced", "essential", "intermediate", 25, ["docker_python_production"],
         ["Deploy FastAPI services using Gunicorn with Uvicorn worker processes", "Handle graceful server shutdown and configure worker lifecycle management"],
         ["What is the role of Gunicorn as a process manager in front of Uvicorn ASGI workers?"],
         ["Running the development reloader (uvicorn --reload) in production environments"]),
        ("observability_python_telemetry", "Observability: OpenTelemetry & Prometheus", "OpenTelemetry Python SDK, trace context propagation, Prometheus FastAPI instrumentator", "Production", "advanced", "recommended", "advanced", 35, ["production_server_uvicorn_gunicorn"],
         ["Instrument distributed tracing across microservices with OpenTelemetry", "Export real-time API latency and error metrics to Prometheus"],
         ["Why are distributed trace IDs essential when debugging microservice call chains?"],
         ["Relying only on print() statements instead of structured JSON log formatters"]),
        ("system_security_owasp_python", "Web Security & Hardening (OWASP Top 10)", "SQL injection prevention, CORS middleware, rate limiting, security headers, bandit audit", "Production", "advanced", "essential", "advanced", 30, ["authentication_jwt_oauth2"],
         ["Protect FastAPI services against common OWASP vulnerabilities", "Audit Python dependencies and codebases for known security vulnerabilities with bandit/safety"],
         ["How do parameterized queries in SQLAlchemy prevent SQL injection attacks?"],
         ["Allowing unrestricted CORS origins (origins=['*']) with allow_credentials=True"])
    ]

    return [
        {
            "slug": "frontend",
            "title": "Frontend Developer",
            "domain": "Frontend Web Development",
            "target_role": "Senior Frontend Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["frontend", "web", "html", "css", "javascript", "react", "typescript", "tailwind", "vite", "ui"],
            "nodes": [
                make_node("frontend", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(fe)
            ]
        },
        {
            "slug": "backend",
            "title": "Backend Developer",
            "domain": "Backend Development",
            "target_role": "Senior Backend Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["backend", "api", "databases", "sql", "postgresql", "redis", "docker", "microservices", "rest"],
            "nodes": [
                make_node("backend", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(be)
            ]
        },
        {
            "slug": "fullstack_web",
            "title": "Full Stack Developer",
            "domain": "Full-Stack Web Development",
            "target_role": "Senior Full Stack Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["fullstack", "frontend", "backend", "react", "nodejs", "typescript", "sql", "docker", "api"],
            "nodes": [
                make_node("fullstack_web", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(fs)
            ]
        },
        {
            "slug": "android",
            "title": "Android Developer",
            "domain": "Mobile Development",
            "target_role": "Senior Android Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["android", "kotlin", "jetpack compose", "mobile", "coroutines", "hilt", "room", "architecture"],
            "nodes": [
                make_node("android", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(android_nodes)
            ]
        },
        {
            "slug": "ios",
            "title": "iOS Developer",
            "domain": "Mobile Development",
            "target_role": "Senior iOS Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["ios", "swift", "swiftui", "mobile", "swiftdata", "combine", "apple", "app store"],
            "nodes": [
                make_node("ios", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(ios_nodes)
            ]
        },
        {
            "slug": "flutter_mobile",
            "title": "Flutter & Dart Mobile Architecture",
            "domain": "Mobile Development",
            "target_role": "Lead Mobile Architect",
            "difficulty_baseline": "Beginner",
            "tags": ["flutter", "dart", "mobile", "riverpod", "cross-platform", "ios", "android", "custompainter"],
            "nodes": [
                make_node("flutter_mobile", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(flutter_nodes)
            ]
        },
        {
            "slug": "python_backend",
            "title": "Python Backend & Systems",
            "domain": "Backend Systems",
            "target_role": "Senior Python Backend Engineer",
            "difficulty_baseline": "Beginner",
            "tags": ["python", "fastapi", "backend", "sqlalchemy", "asyncio", "celery", "redis", "postgresql"],
            "nodes": [
                make_node("python_backend", key, t, sub, ph, tr, imp, diff, idx + 1, mins, pre, obj, feyn, misc)
                for idx, (key, t, sub, ph, tr, imp, diff, mins, pre, obj, feyn, misc) in enumerate(py_nodes)
            ]
        }
    ]
